// The Hindi half of the studio's copy table, its own file and its own
// chunk (the WS-R71 merge, 2026-09-05). `src/studio/copy.ts` holds the
// interfaces, the helpers and the English table; this file holds ONLY the
// Hindi table, and nothing imports it statically: `loadStudioCopy("hi")` in
// copy.ts is the one caller, through a dynamic `import()`, so Vite ships it
// as a separate chunk the English studio never downloads. Why: after ten
// workstreams of Hindi copy the studio's signed-out entry measured 186.1 KB
// of gzipped JS against WS-R49's 180 KB budget, and 142 KB of the copy
// source (31 KB gzipped) was this table - see
// context/decisions.md#studio-hindi-table-is-its-own-chunk.
//
// The file's basename ends in "Copy.ts" on purpose: scripts/check-copy.mjs's
// `COPY_FILES` pattern treats every string literal in a file named that way
// as user-visible, which every string here is. Key parity with the English
// table is asserted by evals/studio-locale/run.mjs, which loads this file
// through `loadStudioCopy` exactly as the app does.
import type { StudioCopy } from "./copy";

export const HI: StudioCopy = {
  classLabels: { you: "आप पर निर्भर", us: "हम पर निर्भर" },

  shell: {
    languageGroupLabel: "हिन्दी / English",
    tabsAriaLabel: "आपका AI, तीन टैब में",
    tabTitle: { feed: "फ़ीड", meet: "मीट", share: "शेयर" },
    tabPromise: {
      feed: "अपनी सामग्री लाएं।",
      meet: "अपने AI से मिलें: सुनें, ठीक करें, देखें यह कितना तैयार है।",
      share: "अपना रूम पब्लिश करें और तय करें कि इसे कहां पहुंचाया जा सकता है।",
    },
    allPanelsLink: "सभी पैनल (पूरी बेंच)",
    oneVideoTitle: "एक वीडियो, लिंक से",
    oneVideoBlurb: "अभी बन रहा प्रवेश का चौथा तरीका।",
    stillLockedTitle: "मीट पर अभी भी लॉक",
    forYou: "{n} आप पर",
    onUsCount: "{n} हम पर",
  },

  creatorPath: {
    eyebrow: "आपके रूम के पब्लिश होने तक का रास्ता",
    stepLabel: {
      account_created: "आपका वर्कस्पेस",
      studio_opened: "आपने स्टूडियो खोला",
      first_source_uploaded: "आपका पहला सोर्स",
      processing_finished: "हमने इसे प्रोसेस कर लिया",
      first_preview_heard: "आपने अपना AI सुना",
      readiness_first_measured: "हमने तैयारी मापी",
      readiness_passed_lock: "तैयारी ने सीमा पार की",
      disclosure_approved: "आपने मंज़ूरी दी कि फॉलोअर को क्या बताया जाता है",
      room_created: "आपने अपना रूम बनाया",
      publish_clicked: "आपने इसे पब्लिश किया",
      room_published: "आपका रूम लाइव है",
      first_follower_joined: "आपका पहला फॉलोअर जुड़ा",
    },
    currentSentence: {
      account_created: "आपका वर्कस्पेस तैयार है।",
      studio_opened: "आप अभी स्टूडियो में हैं।",
      first_source_uploaded: "शुरू करने के लिए एक फ़ाइल, वीडियो, या लिंक जोड़ें।",
      processing_finished: "हम अभी भी आपकी दी हुई चीज़ें प्रोसेस कर रहे हैं।",
      first_preview_heard: "जाकर पहली बार अपना AI सुनें।",
      readiness_first_measured: "अपने AI से बात करें ताकि हम तैयारी माप सकें।",
      readiness_passed_lock: "हर हिस्से को {n} तक और पूरे को {n2} तक पहुंचाएं।",
      disclosure_approved: "पढ़ें और मंज़ूरी दें कि हर फॉलोअर को पहले क्या बताया जाता है।",
      room_created: "अपना रूम बनाएं।",
      publish_clicked: "तैयार होने पर अपना रूम पब्लिश करें।",
      room_published: "आपका रूम अभी लाइव हुआ।",
      first_follower_joined: "आपके पहले फॉलोअर का इंतज़ार है।",
    },
    currentButton: {
      account_created: "जारी रखें",
      studio_opened: "जारी रखें",
      first_source_uploaded: "अपना पहला सोर्स जोड़ें",
      processing_finished: "देखें क्या हो रहा है",
      first_preview_heard: "अपना AI सुनें",
      readiness_first_measured: "अपने AI से बात करें",
      readiness_passed_lock: "तैयारी सुधारें",
      disclosure_approved: "पढ़ें और मंज़ूरी दें",
      room_created: "अपना रूम बनाएं",
      publish_clicked: "अपना रूम पब्लिश करें",
      room_published: "अपना रूम खोलें",
      first_follower_joined: "अपना रूम खोलें",
    },
    stateLabel: { done: "पूरा हुआ", current: "अभी", ahead: "बाद में" },
    pausedSentence: "आपका रूम रुका हुआ है, इसलिए अभी कोई इस तक नहीं पहुंच सकता।",
    pausedButton: "जाकर अपना रूम फिर शुरू करें",
  },

  wizardRail: {
    railLabel: "आपका AI, तीन चरणों में",
    navAriaLabel: "स्टूडियो के चरण",
    nothingOpenDone: "इस चरण पर कुछ भी खुला नहीं है।",
    nothingOpenNotDone: "इस चरण पर अभी कुछ भी खुला नहीं है।",
    seeWhatIsHappening: "देखें क्या हो रहा है",
    goThere: "वहां जाएं",
    whatIsStillOpen: "इस चरण पर अभी क्या खुला है",
    everythingElse: "इस चरण पर बाकी सब",
    youCanActOn: "{n} जिन पर आप कर सकते हैं",
    onUsCount: "{n} हम पर",
    hideWhy: "वजह छुपाएं",
    whyThisStep: "यह चरण क्यों",
    movedTo: "{label} पर पहुंचे।",
    theSection: "इस हिस्से",
  },

  readiness: {
    eyebrow: "तैयारी",
    workingOut: "पता लगाया जा रहा है कि आपका AI कहां खड़ा है।",
    onUsHeadline: "यह हमारी वजह से है।",
    couldNotRead: "अभी आपकी तैयारी पढ़ी नहीं जा सकी",
    tryAgain: "फिर कोशिश करें",
    stillApprenticeOne: "अभी भी अप्रेंटिस। एक हिस्सा अभी तक मापा नहीं गया, इसलिए कोई स्कोर नहीं दिया जा सकता।",
    stillApprenticeMany: "अभी भी अप्रेंटिस। {n} हिस्से अभी तक मापे नहीं गए, इसलिए कोई स्कोर नहीं दिया जा सकता।",
    outOf100: "100 में से, नीचे दिए पांच हिस्सों में",
    notMeasuredYet: "अभी मापा नहीं गया",
    how: "कैसे",
    sample: "नमूना",
    measured: "मापा गया",
    publishingLocked: "पब्लिश करना लॉक है।",
    publishingOpen: "पब्लिश करना खुला है।",
    lockedWhyWeakest: "सबसे कमज़ोर: {name}। पब्लिश करने के लिए, हर हिस्से को {n} और पूरे को {n2} चाहिए।",
    lockedWhyNoWeakest: "पब्लिश करने के लिए, हर हिस्से को {n} और पूरे को {n2} चाहिए।",
    openWhy: "आपका AI अगले चरण में आपके चुने हुए लोगों तक पहुंच सकता है।",
    trustLine: "आपकी आवाज़ कभी लिस्ट या शेयर नहीं होती।",
    partHelp: {
      knows_your_material: "क्या यह आपकी दी हुई सामग्री से जवाब दे सकता है।",
      sounds_like_you: "क्या आपकी आवाज़ आपकी जैसी ही वापस आती है।",
      thinks_like_you: "क्या आप इसके जवाब रखते हैं या ठीक करते हैं।",
      knows_what_not_to_say: "वे लाइनें जो आपने इसे कभी पार न करने को कहा है।",
      up_to_date: "क्या यह जो जानता है वह अभी भी सच है।",
    },
  },

  driftWatch: {
    eyebrow: "ड्रिफ्ट वॉच",
    onUsHeadline: "यह हमारी वजह से है।",
    couldNotCheck: "अभी ड्रिफ्ट की जांच नहीं हो सकी",
    tryAgain: "फिर कोशिश करें",
    notMeasuredHeadline: "अभी मापा नहीं गया।",
    notMeasuredLede: "हमने आपकी आवाज़ को आपकी अपनी रिकॉर्डिंग से हाल ही में इतना नहीं मिलाया कि बता सकें कि यह अभी भी आपकी जैसी लगती है या नहीं।",
    movedHeadline: "कुछ बदल गया।",
    steadyHeadline: "अभी भी आपकी जैसी लगती है।",
    ofYourOwn100: " आपके अपने 100 में से, {label} को मापा गया",
    ofYourOwn100Bare: " आपके अपने 100 में से",
    last30Days: "पिछले 30 दिन",
    engineChanged: "इसके पीछे की वॉइस इंजन आखिरी बार {label} को बदली थी।",
    engineUnchanged: "जब से हमने देखना शुरू किया, इसके पीछे की वॉइस इंजन नहीं बदली।",
    anchorFallback: "इसके लिए हमारा अपना अलार्म अभी अपडेट नहीं है।",
    movedReasons: {
      model_commitment_changed: "आपके AI के पीछे की वॉइस इंजन हाल ही में बदली।",
      score_dropped: "आपका वॉइस स्कोर सामान्य रोज़ के बदलाव से ज़्यादा गिरा।",
    },
    prosodyReasons: {
      prosody_baseline_unavailable: "हम यह जांच नहीं सके कि इसके लिए हमारा अपना अलार्म अपडेट है या नहीं।",
      prosody_baseline_never_established: "इसके लिए हमारा अपना अलार्म कभी सेट नहीं हुआ।",
      prosody_baseline_last_run_alarmed: "इसके लिए हमारा अपना अलार्म पिछली जांच में बजा और अभी तक साफ़ नहीं हुआ।",
      prosody_baseline_overdue: "इसके लिए हमारा अपना अलार्म काफी समय से नहीं चला।",
    },
    trendAriaOne: "{d1} को {v1} से {d2} को {v2} तक का रुझान, {n} मापे गए बिंदु पर।",
    trendAriaMany: "{d1} को {v1} से {d2} को {v2} तक का रुझान, {n} मापे गए बिंदुओं पर।",
  },

  reviewQueue: {
    eyebrow: "समीक्षा",
    title: "देखें आपका AI क्या कहता है",
    lede: "एक बार में एक जवाब। बताएं कि यह आपकी तरह लगता है, अपने शब्दों में ठीक करें, या इसे पूरी तरह रोक दें।",
    cardOf: "कार्ड {n} में से {n2}",
    dismiss: "हटाएं",
    kindLabel: {
      question: "एक सवाल जो लोग पूछेंगे",
      claim: "कुछ जो हमें लगता है हमने सीखा",
      delta: "कॉल पर सुनी गई एक आदत",
      follower_declined: "एक सवाल जिसका आपका AI जवाब नहीं देगा",
    },
    noAnswerYet: "आपके AI ने अभी इसका जवाब नहीं दिया। लिखें कि आप क्या कहेंगे और वही जवाब बन जाएगा।",
    buttonSoundsRight: "सही लगा",
    buttonFixed: "करीब है, ठीक करें",
    buttonNever: "यह कभी न कहें",
    emptyTitle: "अभी समीक्षा के लिए कुछ नहीं।",
    emptyBody: "आपका रूम खुलते ही यह असली बातचीत से खुद भर जाता है।",
    looking: "देखा जा रहा है...",
    lookForSomething: "समीक्षा के लिए कुछ ढूंढें",
    fixQuestionLabel: "आप असल में क्या कहेंगे?",
    fixPlaceholder: "जैसे आप जवाब देंगे, वैसे ही जवाब दें।",
    fixNote: "यह आपके अपने सोर्स के रूप में सेव होता है और इसका हवाला दिया जाता है। यह कभी आपके AI में स्क्रिप्ट की तरह नहीं डाला जाता।",
    saving: "सेव हो रहा है...",
    saveThisAnswer: "यह जवाब सेव करें",
    listening: "सुन रहे हैं, हो जाए तो छोड़ें",
    savingHold: "सेव हो रहा है...",
    holdToSayIt: "कहने के लिए दबाए रखें",
    back: "वापस",
    micDenied: "आपके ब्राउज़र ने माइक्रोफ़ोन नहीं दिया। इसके बजाय ठीक करके टाइप करें।",
    noticeFixed: "सेव हो गया। पुराने जवाब से बना कुछ भी अब दोबारा बनाया जाएगा, पैच नहीं किया जाएगा।",
    noticeNever: "सेव हो गया। आपका AI अब हर जगह यह कहने से रोका गया है।",
    noticeSaved: "सेव हो गया।",
    errorLoad: "समीक्षा कतार पढ़ी नहीं जा सकी",
    errorSave: "वह फैसला सेव नहीं हो सका",
    errorCorrection: "वह सुधार सेव नहीं हो सका",
    errorRecording: "वह रिकॉर्डिंग सेव नहीं हो सकी",
    errorFill: "कतार भरी नहीं जा सकी",
    nothingRecorded: "कुछ भी रिकॉर्ड नहीं हुआ। बोलते समय बटन दबाए रखें।",
    addedWithGenerator: "{n} जोड़े गए। इस डिप्लॉयमेंट पर सवाल जनरेटर अभी उपलब्ध नहीं है, इसलिए केवल आपकी अपनी सामग्री इस्तेमाल हुई।",
    addedPlain: "{n} जोड़े गए।",
    blockedAnswerOne: "{n} रोका गया जवाब हर जगह लागू है।",
    blockedAnswerMany: "{n} रोके गए जवाब हर जगह लागू हैं।",
    flaggedRepliesOne: "फ़ॉलोअर्स ने {n} जवाब को फ़्लैग किया है।",
    flaggedRepliesMany: "फ़ॉलोअर्स ने {n} जवाबों को फ़्लैग किया है।",
  },

  payouts: {
    title: "पेआउट",
    intro: "महीने में एक स्टेटमेंट, एक नंबर जिसे आप अपनी बैंक लाइन से मिला सकते हैं: फॉलोअर्स ने क्या दिया, प्लेटफ़ॉर्म ने क्या रखा, टैक्स के लिए क्या रोका गया, और आप तक क्या पहुंचता है।",
    fundAccountLabel: "फंड अकाउंट रेफरेंस (आपके पेमेंट प्रोवाइडर से, यहां कभी बैंक की जानकारी न डालें)",
    save: "सेव करें",
    saving: "सेव हो रहा है...",
    fundAccountNote: "यह प्लेटफ़ॉर्म कभी आपका बैंक अकाउंट नंबर या UPI आईडी नहीं मांगता। आपका पेमेंट प्रोवाइडर अपना ऑनबोर्डिंग पूरा होते ही एक रेफरेंस जारी करता है, और यहां सिर्फ वही रेफरेंस सेव होता है।",
    saved: "फंड अकाउंट रेफरेंस सेव हो गया।",
    hideStatement: "स्टेटमेंट छुपाएं",
    showStatement: "स्टेटमेंट दिखाएं",
    gross: "कुल",
    platformTake: "प्लेटफ़ॉर्म का हिस्सा",
    tdsWithheld: "TDS रोका गया",
    netToYou: "आपको मिलने वाली राशि",
    followerSubsThisPeriod: "इस अवधि में फॉलोअर सदस्यताएं: {n}।",
    suiteShare: "{name} से एक Suite सीट हिस्सा शामिल है: {label}।",
    suiteShareNoName: "एक Suite सीट हिस्सा शामिल है: {label}।",
    tdsNote: "TDS वह दर दिखाता है जो प्लेटफ़ॉर्म ऑपरेटर ने सेट की है। अभी वह दर 0% है, इसलिए कुछ भी नहीं रोका जाता। ऑपरेटर मानता है कि भारत के इनकम टैक्स एक्ट की धारा 194J क्रिएटर के रूम की कमाई पर लागू होती है, लेकिन किसी अकाउंटेंट ने इसकी पुष्टि नहीं की है, और कोई असली पेआउट भेजे जाने से पहले यह दर बदल सकती है।",
    stateLine: "स्थिति: {label}",
    providerRef: ", प्रोवाइडर रेफरेंस {label}",
    settledLine: "सेटल हुआ: {label}",
    failureReasonLine: "असफलता का कारण: {label}",
    downloadJson: "JSON के रूप में डाउनलोड करें",
    downloadText: "टेक्स्ट के रूप में डाउनलोड करें",
    couldNotLoadStatement: "यह स्टेटमेंट लोड नहीं हो सका।",
    loadingStatement: "स्टेटमेंट लोड हो रहा है।",
    noPayoutYet: "अभी आपके लिए कोई पेआउट नहीं बना। कमाई के साथ कोई अवधि बंद होते ही यह भर जाता है।",
    stateLabel: {
      built: "बना, अभी भेजा नहीं गया",
      pending_account: "फंड अकाउंट का इंतज़ार",
      queued: "प्रोवाइडर के पास कतार में",
      sent: "भेजा गया",
      settled: "निपटाया गया",
      failed: "विफल",
    },
    netLabel: "{label} नेट - {label2}",
    statementDocTitle: "पेआउट स्टेटमेंट, {label}",
    statementDocBuilt: "बना",
  },

  checkins: {
    title: "चेक-इन",
    intro: "एक पेड फॉलोअर खुद इसमें शामिल होता है और अपना समय चुनता है; आपका AI उसी समय पर फॉलो-अप करता है, कभी इसलिए नहीं कि वे चुप हो गए। यहां जो जांचना है वह अपने AI के लिए एक नोट की तरह लिखें, कोई लाइन नहीं जो वह पढ़कर सुनाए; यह हर बार अपने ही शब्दों में कहेगा।",
    working: "हो रहा है...",
    pause: "रोकें",
    resume: "फिर शुरू करें",
    emptyList: "अभी तक कोई चेक-इन नहीं। यहां जोड़ा गया पहला चेक-इन ही वह है जिसमें कोई फॉलोअर शामिल हो सकता है।",
    titleLabel: "शीर्षक",
    titlePlaceholder: "शाम की सैर",
    shapeLabel: "क्या जांचना है (अपने AI के लिए एक नोट: यह इसे खुद अपने शब्दों में कहेगा)",
    shapePlaceholder: "पूछें कि क्या उन्होंने आज शाम की सैर की; हां हो तो थोड़ा जश्न मनाएं, न हो तो कोई शर्मिंदगी नहीं",
    cadenceLabel: "समय-संकेत (फॉलोअर को दिखता है, जैसे \"रोज़ाना\")",
    cadencePlaceholder: "रोज़ाना",
    saving: "सेव हो रहा है...",
    addCheckin: "चेक-इन जोड़ें",
  },

  handoff: {
    title: "हैंडऑफ़",
    intro: "डिफ़ॉल्ट रूप से बंद। जब यह चालू हो, तो एक फॉलोअर सीधे आपसे सुनने को कह सकता है - वे तय करते हैं कि क्या भेजा जाए, भेजने से पहले उसे शब्द दर शब्द देखते हैं, और आपका जवाब सिर्फ उनके अपने थ्रेड में पहुंचता है, आपके नाम से, कभी आपके AI के नाम से नहीं।",
    on: "चालू",
    off: "बंद",
    forThisRoom: "इस रूम के लिए",
    working: "हो रहा है...",
    turnOff: "बंद करें",
    turnOn: "चालू करें",
    capLabel: "एक फॉलोअर महीने में जितनी रिक्वेस्ट भेज सकता है (0-50)",
    waiting: "इंतज़ार में",
    answered: "जवाब दिया गया",
    whatTheySent: "उन्होंने जो भेजा, बिल्कुल वैसे ही जैसे भेजा",
    yourReply: "आपका जवाब",
    replyPlaceholder: "अपने शब्दों में जवाब दें - यह सिर्फ उन्हीं तक पहुंचता है, आपके नाम से।",
    sending: "भेजा जा रहा है...",
    sendReply: "जवाब भेजें",
    nothingWaiting: "अभी कुछ भी इंतज़ार में नहीं है।",
  },

  inviteCreator: {
    title: "एक क्रिएटर को न्योता दें",
    intro: "आप तीन और क्रिएटर को अपना AI बनाने के लिए न्योता दे सकते हैं। एक कोड एक बार चलता है, उस व्यक्ति के लिए जिसे आप देते हैं, और यह स्क्रीन ही एकमात्र जगह है जहां यह पूरा दिखता है।",
    publishFirst: "दूसरे क्रिएटर को न्योता देना शुरू करने के लिए अपना रूम पब्लिश करें।",
    copied: "कॉपी हो गया",
    copyCode: "कोड कॉपी करें",
    sendNow: "इसे अभी उस व्यक्ति को भेजें जिसे आप न्योता दे रहे हैं। यह दोबारा नहीं दिखाया जाएगा।",
    creating: "बनाया जा रहा है...",
    createCode: "न्योता कोड बनाएं",
    quota: "{n2} में से {n} इस्तेमाल हुए।",
    quotaExhausted: " आप तीनों इस्तेमाल कर चुके हैं।",
    usedAll: "आप तीनों न्योते इस्तेमाल कर चुके हैं, या आपका रूम अभी पब्लिश नहीं हुआ है।",
    stateLabel: {
      unused: "अभी इस्तेमाल नहीं हुआ",
      redeemed: "भुनाया गया",
      expired: "खत्म हो गया",
    },
  },

  inviteGate: {
    eyebrow: "फिलहाल सिर्फ न्योते से",
    headline: "जब तक पहले रूम हाथ से बनाए जा रहे हैं, Vyakti सिर्फ न्योते से खुलता है।",
    lede: "अगर यहां किसी ने आपको पहले ही कोड भेजा है, तो नीचे डालें। नहीं तो आप आवेदन कर सकते हैं, और हम संपर्क करेंगे।",
    codeLabel: "न्योता कोड",
    codePlaceholder: "XXXX-XXXX-XXXX",
    checking: "जांचा जा रहा है",
    continueLabel: "जारी रखें",
    noCodeYet: "अभी कोड नहीं है?",
    applyLink: "पहले रूम में से एक के लिए आवेदन करें",
  },

  suite: {
    title: "Suites",
    intro: "एक Suite एक संस्था है जो सीटों के लिए भुगतान करती है - हर रूम की एक सीट। कई रूम (एक कोच, एक टीचर, एक डॉक्टर) को एक ही रोस्टर में लाने के लिए एक बनाएं; एक एडमिन हर रूम के सिर्फ आंकड़े देखता है, कभी यह नहीं कि किसी फॉलोअर ने क्या कहा।",
    creating: "आपका Suite बनाया जा रहा है।",
    starting: "इसकी सीट सदस्यता शुरू की जा रही है।",
    seatsUsedAdmin: "{n2} में से {n} सीटें इस्तेमाल हुईं - आप इस Suite के एडमिन हैं",
    seatsUsedMember: "{n2} में से {n} सीटें इस्तेमाल हुईं - आप इसके सदस्य हैं",
    working: "हो रहा है...",
    inviteCreator: "एक क्रिएटर को न्योता दें",
    hideMembers: "सदस्य छुपाएं",
    showMembers: "सदस्य दिखाएं",
    hideMoney: "पैसे छुपाएं",
    showMoney: "पैसे दिखाएं",
    attachThisRoom: "इस रूम को जोड़ें",
    noSeatFree: "कोई सीट खाली नहीं",
    removeFromSuite: "इस रूम को इस Suite से हटाएं",
    loadingMembers: "सदस्य लोड हो रहे हैं।",
    memberAdmin: "एडमिन",
    memberCreator: "क्रिएटर",
    loadingMoney: "पैसे लोड हो रहे हैं।",
    seatsAtPrice: "{n} सीटें {label} प्रति महीना हर एक - स्थिति: {label2}।",
    willNotRenew: "{label} के बाद नवीनीकृत नहीं होगी। हर जुड़ा हुआ रूम तब तक अपनी सीट रखता है।",
    nextCharge: "अगला भुगतान: {label} को {label2}।",
    platformTake: "Vyakti का प्लेटफ़ॉर्म हिस्सा {n}% है, हर रूम की अपनी फॉलोअर कीमत जितना ही।",
    cancel: "रद्द करें",
    updateSeats: "सीटें अपडेट करें",
    noSubscriptionYet: "अभी कोई Suite सदस्यता नहीं है। जब तक एक शुरू नहीं होती, सीटें इस Suite की अपनी मुफ़्त सीट सीमा तक ही रहती हैं।",
    startSubscription: "Suite सदस्यता शुरू करें",
    noSuitesYet: "अभी कोई Suite नहीं है। नीचे एक बनाएं, या किसी Suite एडमिन के न्योते से जुड़ें।",
    newSuiteName: "नए Suite का नाम",
    namePlaceholder: "North Coaching",
    plan: "प्लान",
    planStarter: "Starter",
    planInstitute: "Institute",
    seats: "सीटें",
    saving: "सेव हो रहा है...",
    createSuite: "Suite बनाएं",
    joinSuite: "एक Suite से जुड़ें (एडमिन ने जो आईडी शेयर की, वह पेस्ट करें)",
    joinPlaceholder: "Suite आईडी",
    join: "जुड़ें",
    noticeCreated: "Suite बन गया। आप इसके एडमिन हैं।",
    inviteNotice: "इस Suite की आईडी क्रिएटर के साथ शेयर करें: {orgId}।",
    noticeJoined: "आप इस Suite से एक क्रिएटर के रूप में जुड़ गए हैं।",
    noticeAttached: "यह रूम अब इस Suite का हिस्सा है।",
    noticeDetached: "यह रूम अब उस Suite का हिस्सा नहीं है।",
    noticeSubscriptionStarted: "Suite सदस्यता शुरू हो गई।",
    noticeSeatsUpdated: "सीटें अपडेट हो गईं।",
    noticeWillNotRenewSimple: "मौजूदा अवधि खत्म होने के बाद नवीनीकृत नहीं होगी।",
    autoStartLiveStarted: "\"{name}\" लाइव है, और इसकी सीट सदस्यता शुरू हो गई है।",
    autoStartLivePending: "\"{name}\" लाइव है। जब सीटों के लिए भुगतान लेने के लिए तैयार हों, तब नीचे इसकी सदस्यता शुरू करें।",
  },

  roomStudio: {
    eyebrow: "आपका रूम",
    loadingTitle: "आपका रूम लोड हो रहा है",
    checkingExists: "जांचा जा रहा है कि आपका रूम अभी है या नहीं।",
    setupTitle: "वह जगह बनाएं जहां आपका AI रहता है",
    setupIntro:
      "एक रूम हर फॉलोअर के लिए, जो आपके AI से बात करता है, एक निजी, लगातार चलने वाला पता है। यह हर एक को खुद " +
      "याद रखता है, और कभी एक फॉलोअर को दूसरे को नहीं दिखाता। इसे एक बार बना लें, फिर जब नीचे के गेट खुल जाएं तो " +
      "इसे पब्लिश करें।",
    settingUp: "बनाया जा रहा है...",
    setupButton: "अपना रूम बनाएं",
    liveTitle: "वह जगह जहां आपका AI रहता है",
    liveIntro:
      "एक निजी, लगातार चलने वाला पता। हर फॉलोअर जो जुड़ता है, आपके AI के साथ अपना ही याद रखा हुआ रिश्ता पाता है, " +
      "और उनमें से कोई भी कभी किसी और फॉलोअर की बातचीत, या आपकी, नहीं देखता।",
    statusPaused: "रुका हुआ",
    statusLive: "लाइव",
    statusDraft: "पब्लिश नहीं हुआ",
    addressCardTitle: "आपके रूम का पता",
    copied: "कॉपी हो गया",
    copyLink: "लिंक कॉपी करें",
    downloadStoryCard: "स्टोरी कार्ड डाउनलोड करें",
    partOf: "{label} का हिस्सा।",
    suiteCoversRoom: "{label} में आपकी सीट इस रूम को कवर करती है।",
    yourSuite: "आपका Suite",
    tierGroupAriaLabel: "टियर",
    tierFreeLabel: "आपका टियर: मुफ़्त क्षमता।",
    working: "हो रहा है...",
    upgradeToRoom: "Room में अपग्रेड करें ({label}/माह)",
    upgradeToStudio: "Studio में अपग्रेड करें ({label}/माह)",
    tierLabel: "आपका टियर: {label}।",
    tierRoom: "Room",
    tierStudio: "Studio",
    willNotRenewOn: " {label} के बाद नवीनीकृत नहीं होगा।",
    renewsOn: " {label} को नवीनीकृत होगा।",
    cancel: "रद्द करें",
    changeAddressLabel: "पता बदलें",
    saving: "सेव हो रहा है...",
    saveAddress: "पता सेव करें",
    enterAddress: "अपने रूम के लिए एक पता डालें।",
    addressInvalid: "3 से 40 अक्षर, अंक, या डैश के बीच।",
    willReadAs: "यह ऐसे दिखेगा: {label}",
    telegramCardTitle: "Telegram पर आपका रूम",
    open: "खोलें",
    telegramNotConnected:
      "अभी नहीं जुड़ा। फॉलोअर्स फिर भी ऊपर वाले पते पर आपके रूम तक पहुंच सकते हैं; Telegram पहुंचने का एक दूसरा " +
      "तरीका है, कोई ज़रूरत नहीं।",
    ownSiteCardTitle: "अपनी खुद की साइट पर",
    ownSiteIntro:
      "इसे किसी भी पेज पर पेस्ट करें जो आप नियंत्रित करते हैं: एक कोचिंग साइट, एक Linktree, एक ब्लॉग पोस्ट। यह " +
      "नीचे आपके रूम का डिस्क्लोज़र दिखाते हुए एक बटन दिखाता है, और क्लिक करने पर आपका रूम एक नए टैब में खोलता है। " +
      "यह कोई कुकी सेट नहीं करता और आपके विज़िटर से कुछ नहीं मांगता।",
    embedSnippetAriaLabel: "एम्बेड स्निपेट",
    copySnippet: "स्निपेट कॉपी करें",
    ownSiteFooter:
      "विज़िटर वही भाषा में डिस्क्लोज़र देखते हैं जिसमें आपका रूम पहले दिखता है, अंग्रेज़ी या हिन्दी, और यह बटन " +
      "आपके रूम को कभी उनके पेज के अंदर नहीं रखता। यह हमेशा आपके रूम का अपना पता खोलता है।",
    publishCardTitlePublished: "पब्लिशिंग",
    publishCardTitleUnpublished: "अपना रूम पब्लिश करें",
    publishing: "पब्लिश हो रहा है...",
    publishButton: "अपना रूम पब्लिश करें",
    resume: "फिर शुरू करें",
    pause: "रोकें",
    liveSince:
      "{label} से लाइव है। आपके रूम का पता रखने वाला कोई भी जुड़ सकता है और आपके AI के साथ अपना याद रखा हुआ " +
      "रिश्ता शुरू कर सकता है।",
    recently: "हाल ही में",
    pausedNotice: "रुका हुआ है। जब तक आप इसे फिर शुरू नहीं करते, कोई भी आपके रूम तक नहीं पहुंच सकता।",
    listMyRoomTitle: "मेरा रूम लिस्ट करें",
    listMyRoomIntro:
      "लिस्ट करने पर आपका रूम क्रिएटर डायरेक्टरी में दिखता है: आपका नाम, नीचे की एक-लाइन जानकारी, और जिस भाषा " +
      "में आपके रूम की स्क्रीन बोलती हैं। यह कभी नहीं दिखाता कि आपके कितने फॉलोअर हैं।",
    oneLineDescriptionLabel: "एक-लाइन जानकारी",
    oneLineDescriptionPlaceholder: "आप किस बारे में बात करते हैं, एक लाइन में",
    save: "सेव करें",
    listedNote: "लिस्टेड है। डायरेक्टरी देखने वाला कोई भी आपका रूम ढूंढ सकता है।",
    notListedNote: "लिस्टेड नहीं है। आपका रूम फिर भी लिंक रखने वाले किसी के लिए भी काम करता है।",
    publishFirstNote: "पहले अपना रूम पब्लिश करें, फिर आप इसे लिस्ट कर सकते हैं।",
    removeFromDirectory: "डायरेक्टरी से हटाएं",
    listMyRoom: "मेरा रूम लिस्ट करें",
    freeFollowersTitle: "मुफ़्त फॉलोअर्स",
    freeFollowersIntro:
      "जिस फॉलोअर ने भुगतान नहीं किया है उसे महीने में इतने मैसेज मिलते हैं, कोई वॉइस नहीं, कोई चेक-इन नहीं। " +
      "आप इसे कभी भी बदल सकते हैं।",
    freeMonthlyMessagesAriaLabel: "मुफ़्त मासिक मैसेज",
    roomLanguageTitle: "रूम की भाषा",
    roomLanguageIntro:
      "आपका AI वही बोलता रहता है जो आप उससे बोलते हैं - यह सिर्फ ऐप की अपनी स्क्रीन चुनता है: बटन, डिस्क्लोज़र " +
      "लाइन, मेन्यू। जो फॉलोअर पहले जुड़ चुका है, या जिसके अपने ब्राउज़र ने कोई भाषा बताई है, वह इसके बजाय वही " +
      "देखता है; यह बाकी सबके लिए सिर्फ पहली स्क्रीन है।",
    defaultRoomLanguageAriaLabel: "डिफ़ॉल्ट रूम भाषा",
    paidFollowersTitle: "पेड फॉलोअर्स",
    paidFollowersIntroPre: "फेयर-यूज़ सीमा के भीतर लगभग असीमित चैट, साथ ही वॉइस जवाब जब",
    paidFollowersIntroPost: "चालू हो। दोनों नंबर प्लान की सीमा के भीतर आपके तय करने के लिए हैं।",
    messagesAMonthLabel: "महीने में मैसेज",
    paidMonthlyMessagesAriaLabel: "पेड मासिक मैसेज",
    voiceMinutesAMonthLabel: "महीने में वॉइस मिनट",
    paidMonthlyVoiceMinutesAriaLabel: "पेड मासिक वॉइस मिनट",
    priceTitle: "कीमत",
    priceIntro:
      "ऊपर के मुफ़्त मैसेज के बाद, फेयर-यूज़ के भीतर असीमित के लिए एक फॉलोअर महीने में क्या देता है। {min} और " +
      "{max} के बीच। Vyakti एक फॉलोअर के भुगतान का {pct}% रखता है; बाकी आपका है।",
    followerPriceAriaLabel: "फॉलोअर कीमत",
    noPriceYet: "अभी कोई कीमत तय नहीं है। जब तक आप एक तय नहीं करते, फॉलोअर्स सदस्यता नहीं ले सकते।",
    moneyTitle: "पैसा",
    subscribers: "सब्सक्राइबर्स",
    leftThisMonth: "इस महीने छोड़ा",
    yourShareThisMonth: "इस महीने आपका हिस्सा",
    noSubscribersYet: "अभी कोई सब्सक्राइबर नहीं।",
    lastPayout: "पिछला पेआउट: {label} ({label2}), {label3} से {label4} तक के लिए।",
    noPayoutYet: "अभी कोई पेआउट नहीं है।",
    howDoingTitle: "आपका रूम कैसा कर रहा है",
    noFollowersYet: "अभी कोई फॉलोअर नहीं। इसे बदलने के लिए अपने रूम का पता शेयर करें।",
    followers: "फॉलोअर्स",
    activeToday: "आज सक्रिय",
    messagesThisMonth: "इस महीने के मैसेज",
    couldNotLoadCounts: "अभी आपके आंकड़े लोड नहीं हो सके। अगली बार लोड होने पर ये दिखेंगे।",
    weekSixTitle: "छठा हफ़्ता",
    weekSixIntro:
      "किसी हफ़्ते में जुड़े फॉलोअर्स में से, छह हफ़्ते बाद भी आपके AI से बात कर रहे लोगों का हिस्सा। यह वह नंबर " +
      "है जो सबसे ज़्यादा मायने रखता है, भेजे गए मैसेज या आज कितने आए उससे भी ज़्यादा।",
    noCohortsYet: "अभी कोई कोहॉर्ट नहीं। आपके रूम के पहले फॉलोअर मिलते ही यह भरना शुरू होगा।",
    weekOf: "{label} का हफ़्ता",
    noFollowersThatWeek: "उस हफ़्ते कोई फॉलोअर नहीं",
    stillTalkingPct: "{n}% अभी भी बात कर रहे हैं",
    notMeasurableUntil: "{label} तक मापने लायक नहीं",
    notMeasurableYetVerdict: "अभी मापने लायक नहीं। इसके लिए कम से कम छह हफ़्ते पुराना कोहॉर्ट चाहिए।",
    belowGateBand: "25% के उस गेट से नीचे जो इस प्रोडक्ट को बिल्कुल काम करने के लिए चाहिए",
    aboveCategoryBand: "40% की उस लाइन से ऊपर जहां यह एक श्रेणी बन जाता है",
    betweenBand: "25% के गेट और 40% की श्रेणी लाइन के बीच",
    cohortVerdictSentence: "आपका सबसे पुराना मापने लायक कोहॉर्ट, {label} के हफ़्ते का, {n}% वापस आया। यह {label2} है।",
    soon: "जल्द",
    gateLine: "गेट 25% या उससे ज़्यादा है। 40% या उससे ज़्यादा वह जगह है जहां यह एक फ़ीचर होना बंद कर एक श्रेणी बन जाता है।",
    couldNotLoadRetry: "अभी यह लोड नहीं हो सका। अगली बार लोड होने पर यह दिखेगा।",
    loading: "लोड हो रहा है।",
    pulseTitle: "Pulse",
    pulseIntro:
      "आपके फॉलोअर्स किस बारे में बात कर रहे हैं, सिर्फ आंकड़ों के रूप में, और सिर्फ उन बातचीत से जिन्हें किसी " +
      "फॉलोअर ने खुद गिनने देना चुना। कभी कोई मैसेज नहीं, कभी कोई नाम नहीं, और जब तक किसी नंबर के पीछे कम से कम " +
      "पांच अलग-अलग फॉलोअर न हों, तब तक कभी नहीं दिखाया जाता।",
    pulseTopicsAriaLabel: "Pulse विषय",
    removeTopicAriaLabel: "विषय {label} हटाएं",
    addTopicPlaceholder: "एक विषय जोड़ें, जैसे परीक्षा का तनाव",
    add: "जोड़ें",
    notEnoughOptins: "अभी तक पर्याप्त लोगों ने ऑप्ट-इन नहीं किया।",
    enoughOptinsNoBucket: "पर्याप्त फॉलोअर्स ने ऑप्ट-इन किया है, लेकिन अभी किसी के पीछे पांच नहीं हैं।",
    suppressedOne: "{n} संयोजन इस हफ़्ते रोका गया क्योंकि दिखाने से किसी का नाम पता चल जाता।",
    suppressedMany: "{n} संयोजन इस हफ़्ते रोके गए क्योंकि दिखाने से किसी का नाम पता चल जाता।",
    showMe: "मुझे दिखाएं",
    noticeRoomSetup: "आपका रूम बन गया है। जब तैयार हों तब इसे पब्लिश करें।",
    noticeAddressSaved: "पता सेव हो गया।",
    noticeRoomLive: "आपका रूम लाइव है।",
    noticeResumed: "फिर शुरू हुआ। आपका रूम फिर से लाइव है।",
    noticeDefaultLocaleHi: "जिन नए फॉलोअर्स ने भाषा तय नहीं की, वे पहले हिन्दी देखेंगे।",
    noticeDefaultLocaleEn: "जिन नए फॉलोअर्स ने भाषा तय नहीं की, वे पहले अंग्रेज़ी देखेंगे।",
    noticeBioSaved: "आपकी एक-लाइन जानकारी सेव हो गई।",
    noticeListed: "लिस्टेड है। आपका रूम अब क्रिएटर डायरेक्टरी में दिखता है।",
    noticeUnlisted: "अनलिस्टेड है। आपका रूम डायरेक्टरी में नहीं है; ऊपर वाला लिंक फिर भी काम करता है।",
    noticeFreeCap: "मुफ़्त फॉलोअर्स को अब महीने में {n} मैसेज मिलते हैं।",
    noticePaidCeilings: "पेड फॉलोअर्स को अब महीने में {n} मैसेज और {n2} वॉइस मिनट मिलते हैं।",
    noticePrice: "फॉलोअर्स अब महीने में {label} देते हैं।",
    noticeTierStarted: "आपकी टियर सदस्यता शुरू हो गई है।",
    noticeTierCancel: "मौजूदा अवधि खत्म होने के बाद नवीनीकृत नहीं होगी।",
    dormancyTitle: "सीमित समय के लिए रखें",
    dormancyIntro:
      "डिफ़ॉल्ट रूप से बंद: फॉलोअर की बातचीत हमेशा के लिए रखी जाती है, ठीक वैसे ही जैसे आज है। इसे चालू करें और " +
      "किसी शांत फॉलोअर को कुछ भी भुलाए जाने से पहले एक साफ़ सूचना मिलती है, लौटने का समय देकर।",
    dormancyFloorNote: "कम से कम {n} दिन।",
    dormancyOff: "बंद - हमेशा रखें",
    dormancyDaysAriaLabel: "फॉलोअर को भुलाए जाने से पहले निष्क्रियता के दिन",
    noticeDormancyOn: "किसी शांत फॉलोअर को उनकी आख़िरी विज़िट के {n} दिन बाद, पहले सूचना देकर भुला दिया जाता है।",
    noticeDormancyOff: "बंद कर दिया गया। हर फॉलोअर की बातचीत फिर से हमेशा के लिए रखी जाएगी।",
    friendReferralTitle: "इस हफ़्ते दोस्तों ने लाए",
  },

  videoLinkMount: {
    eyebrow: "जल्द आ रहा है",
    title: "एक वीडियो, लिंक से",
    blurb:
      "एक लेक्चर का URL पेस्ट करें और हम ऑडियो निकालते हैं, उसे ट्रांसक्राइब करते हैं, और बताते हैं कि यह आपके " +
      "समझाने के तरीके के बारे में हमें क्या सिखाता है। यह हिस्सा अभी बन रहा है और अभी जुड़ा नहीं है।",
    noBoxNote:
      "अभी जानबूझकर यहां पेस्ट करने के लिए कोई बॉक्स नहीं है। एक फ़ील्ड जो लिंक ले ले और उसका कुछ न करे, आपसे " +
      "पेस्ट और इंतज़ार दोनों लेगी, और आपको कुछ सच नहीं बताएगी।",
    worksTodayNote:
      "वीडियो के लिए आज क्या काम करता है: नीचे अपना चैनल जोड़ें, और हम आपकी दी हुई अनुमति से नए अपलोड देखते " +
      "हैं। वह हिस्सा जो भी निकालता है, वह आपको बताया जाता है, खुद से लागू नहीं किया जाता।",
  },

  runtimeGate: {
    labels: {
      self_replica_only: "सिर्फ़-खुद की नीति",
      replica_not_ready: "मंज़ूर आवाज़ और व्यवहार",
      self_identity_not_bound: "अकाउंट-से-व्यक्ति की पुष्टि हुई बाइंडिंग",
      adult_verification_required: "जीवित-वयस्क सत्यापन",
      identity_verification_required: "पहचान सत्यापन",
      liveness_verification_required: "लाइव एंटी-रीप्ले जांच",
      inference_consent_required: "इन्फ़रेंस अनुमति",
      person_profile_not_approved: "मंज़ूर: हमने आपके बारे में क्या सीखा",
      calibration_not_approved: "मंज़ूर व्यवहार कैलिब्रेशन",
      voice_genome_not_approved: "मंज़ूर आवाज़",
      voice_not_ready: "प्रोडक्शन वॉइस मैपिंग",
      production_voice_required: "गैर-टेस्ट वॉइस प्रोवाइडर",
      qualification_incomplete: "सात-सुइट क्वालिफ़िकेशन",
    },
    eyebrow: "रनटाइम",
    title: "आपका AI किसी से बात कर सके, उससे पहले क्या पास होना चाहिए",
    intro:
      "लॉन्च हमने आपके बारे में जो सीखा उसका सटीक वर्शन, सटीक आवाज़, प्रोवाइडर वॉइस, रिश्ते का नेमस्पेस, और " +
      "मूल्यांकन सेट को बांधता है। नए ड्राफ्ट चुपचाप किसी सक्रिय AI को नहीं बदल सकते।",
    sealActive: "सक्रिय",
    sealSealed: "सील्ड",
    sealSubActive: "सिर्फ़ निजी इस्तेमाल",
    sealSubSealed: "कोई जनरेशन एक्सेस नहीं",
    checkingGates: "हर लॉन्च गेट जांचा जा रहा है...",
    retry: "फिर कोशिश करें",
    qualificationSuitesPassed: "क्वालिफ़िकेशन सुइट पास हुए",
    whatWeLearnedVersion: "हमने क्या सीखा: वर्शन",
    calibrationVersion: "कैलिब्रेशन वर्शन",
    voiceVersion: "आवाज़ वर्शन",
    gatesClosedOne: "{n} लॉन्च गेट अभी भी बंद है",
    gatesClosedMany: "{n} लॉन्च गेट अभी भी बंद हैं",
    actionNote:
      "आपके AI की कॉल सिर्फ़ सुरक्षित कैस्केड स्पीच इस्तेमाल करती हैं। किसी और क्लाउड वॉइस या डिवाइस टेक्स्ट " +
      "टू स्पीच पर कोई फ़ॉलबैक नहीं है।",
    freezing: "क्षमता फ़्रीज़ की जा रही है...",
    runtimeActive: "रनटाइम सक्रिय है",
    activateButton: "निजी रनटाइम सक्रिय करें",
    readinessUnavailable: "रनटाइम की तैयारी अभी उपलब्ध नहीं है",
    activationRefused: "रनटाइम सक्रिय करना अस्वीकार हुआ",
  },

  turnFeedback: {
    dimensionLabel: {
      wording: "शब्द चयन",
      behavior: "व्यवहार",
      relationship: "रिश्ता",
      memory: "याददाश्त",
      delivery: "डिलीवरी",
      voice_identity: "आवाज़",
    },
    dimensionDescription: {
      wording: "वाक्यांश और वाक्य की बनावट",
      behavior: "आप कैसे प्रतिक्रिया देते और फैसले लेते हैं",
      relationship: "इस व्यक्ति के साथ यह कैसा लगता है",
      memory: "तथ्य, पुरानी बातें, और अनिश्चितता",
      delivery: "गति, भाव, और बिना-शब्दों वाले संकेत",
      voice_identity: "वह सुरक्षित ऑडियो जो आपने असल में सुना",
    },
    ratingLabel: { exact: "बिल्कुल सही", close: "करीब", off: "गलत" },
    reasonLabel: {
      too_generic: "बहुत सामान्य",
      wrong_fact: "गलत तथ्य",
      wrong_relationship: "गलत रिश्ता",
      wrong_tone: "गलत लहजा",
      wrong_wording: "गलत शब्द चयन",
      too_long: "बहुत लंबा",
      too_short: "बहुत छोटा",
      voice_mismatch: "आवाज़ नहीं मिली",
      emotion_mismatch: "भाव नहीं मिला",
      unsafe_or_boundary: "एक सीमा पार की",
      other: "कुछ और",
    },
    playVoiceFirst: "पहले सुरक्षित आवाज़ चलाएं",
    savedRevision: "रिविज़न {n} सुरक्षित",
    didThisFeelLikeYou: "क्या यह आपकी तरह लगा?",
    thisIsMe: "यह मैं हूं",
    tuneThis: "इसे ठीक करें",
    teachDifference: "फ़र्क सिखाएं",
    close: "बंद करें",
    gradeOnlyNote: "सिर्फ़ वही रेट करें जो आपने देखा। बिना रेट किए हिस्से अनजान ही रहते हैं।",
    whatMissed: "क्या चूक गया?",
    correctionLabel: "आप असल में क्या कहेंगे?",
    correctionOptionalNote: "वैकल्पिक, सेव होने से पहले एन्क्रिप्टेड",
    correctionPlaceholder: "वह वर्शन लिखें जो आपकी तरह लगे।",
    layersRatedOne: "{n} हिस्सा रेट किया गया",
    layersRatedMany: "{n} हिस्से रेट किए गए",
    chooseAtLeastOne: "कम से कम एक हिस्सा चुनें",
    securing: "सुरक्षित किया जा रहा है...",
    saveEvidence: "सबूत सेव करें",
    errorFallback: "यह सटीकता नोट सुरक्षित नहीं हो सका",
  },

  replicaDialogueLab: {
    eyebrow: "निजी बातचीत",
    title: "अपने AI से निजी तौर पर, टेक्स्ट में बात करें",
    intro:
      "हर जवाब उस पर बनता है जो हमने आपके बारे में सीखा, आपके अपने कैलिब्रेशन, इस रिश्ते की निजी स्थिति, और " +
      "हाल के टर्न। वॉइस प्लेबैक सिर्फ़ वही सर्वर-जारी जवाब बोल सकती है।",
    statusPrivateLive: "निजी · लाइव",
    statusSealed: "सील्ड",
    lockedHeadline: "जब तक निजी रनटाइम हर गेट पास न करे, बातचीत उपलब्ध नहीं होगी।",
    lockedNote: "कोई फ़ॉलबैक AI, सामान्य आवाज़, या आधा सक्रिय होना इस्तेमाल नहीं होता।",
    stopVoice: "आवाज़ रोकें",
    playProtectedVoice: "सुरक्षित आवाज़ चलाएं",
    emptyHeadline: "कुछ ऐसा शुरू करें जो सिर्फ़ आप ही नोटिस करेंगे।",
    emptyNote: "पहला टर्न एक निजी, वर्शन-बद्ध सेशन खोलता है।",
    thinking: "सबूत-आधारित जवाब बनाया जा रहा है...",
    messageLabel: "अपने AI को मैसेज करें",
    messagePlaceholder: "यहां मैं क्या कहूंगा?",
    sendPrivately: "निजी तौर पर भेजें",
    dismiss: "हटाएं",
    trustNote:
      "ऑडियो के लिए सिंथेटिक डिस्क्लोज़र और वॉटरमार्किंग हमेशा ज़रूरी रहती है। बातचीत के लॉग निजी और मिटाए " +
      "जा सकने वाले हैं; यह स्क्रीन कभी AI, एजेंट, व्यक्ति, स्टोरेज, या प्रोवाइडर की पहचान नहीं दिखाती।",
    errorReadinessUnavailable: "निजी बातचीत की तैयारी अभी उपलब्ध नहीं है",
    errorReconcileRequired:
      "यह जवाब पूरा हो गया, लेकिन अगले पेड टर्न से पहले Azure इस्तेमाल को ऑपरेटर की तरफ़ से मिलाना ज़रूरी है।",
    errorCouldNotAnswer: "आपका AI जवाब नहीं दे सका",
    errorVoicePlayback: "सुरक्षित आवाज़ चलाई नहीं जा सकी",
  },

  calibrationStudio: {
    layers: {
      delivery: "डिलीवरी",
      language: "भाषा",
      behaviour: "व्यवहार",
      memory: "याददाश्त",
      relationship: "रिश्ता",
    },
    blockers: {
      approved_person_profile_required: "पहले हमने आपके बारे में जो सीखा उसे मंज़ूर करें",
      delivery_calibration_required: "कम से कम एक डिलीवरी तुलना चुनें",
      language_calibration_required: "कम से कम एक भाषा तुलना चुनें",
      behaviour_calibration_required: "कम से कम एक व्यवहार तुलना चुनें",
      memory_calibration_required: "कम से कम एक याददाश्त तुलना चुनें",
      relationship_calibration_required: "कम से कम एक रिश्ता तुलना चुनें",
      calibration_depth_required: "कम से कम सात तुलनाएं हल करें",
    },
    eyebrow: "व्यवहार कैलिब्रेशन",
    title: "इसे दिखाएं कि आप असल में कैसे जवाब देंगे",
    intro:
      "सुरक्षित व्यवहार तुलनाओं में से चुनें। हर सुधार वर्शन वाला प्राथमिकता सबूत बनता है, कभी किसी प्रॉम्प्ट " +
      "में चिपकाया गया एक और वाक्य नहीं।",
    approvedPolicyLabel: "मंज़ूर नीति",
    preparingContrasts: "कैलिब्रेशन तुलनाएं तैयार की जा रही हैं...",
    retry: "फिर कोशिश करें",
    contrastsReviewedAriaLabel: "{n2} में से {n} तुलनाएं देखी गईं",
    contrastsReviewed: "तुलनाएं देखी गईं",
    calibrationScenariosAriaLabel: "कैलिब्रेशन परिदृश्य",
    openContrastAriaLabel: "{label} तुलना {n} खोलें",
    orWord: "या",
    bothFeelLikeMe: "दोनों मेरी जैसी लगती हैं",
    neitherIsMe: "कोई भी मेरी जैसी नहीं",
    freeTextNote:
      "फ़्री-टेक्स्ट नोट कभी व्यवहार में नहीं जोड़े जाते। सिर्फ़ देखी गई, सर्वर की अपनी रणनीतियां ही किसी " +
      "फ़्रीज़ की गई रनटाइम क्षमता में जा सकती हैं।",
    checkingChoices: "चुनाव जांचे जा रहे हैं...",
    approveCalibrationVersion: "कैलिब्रेशन v{n} मंज़ूर करें",
    buildingPolicy: "नीति बनाई जा रही है...",
    buildCalibrationPolicy: "कैलिब्रेशन नीति बनाएं",
    errorCouldNotLoad: "कैलिब्रेशन लोड नहीं हो सका",
    errorChoiceNotSaved: "आपका कैलिब्रेशन चुनाव सेव नहीं हुआ",
    errorBuildRefused: "कैलिब्रेशन बनाना अस्वीकार हुआ",
    errorApproveChanged: "कैलिब्रेशन बदल गई और मंज़ूर नहीं हो सकी",
  },

  candidateEvaluationLab: {
    dimensionCopy: {
      overall: { label: "कुल मिलाकर", hint: "कौन-सा आपकी जैसा ज़्यादा लगता है?" },
      wording: { label: "शब्द चयन", hint: "वाक्यांश, वाक्य की बनावट, और लंबाई" },
      behavior: { label: "व्यवहार", hint: "प्रतिक्रिया, समझ, और जवाब देने का तरीका" },
      relationship: { label: "रिश्ता", hint: "इस सटीक रिश्ते में आप कैसे बोलेंगे" },
      memory: { label: "याददाश्त", hint: "तथ्य, पुरानी बातें, और ईमानदार अनिश्चितता" },
      delivery: { label: "डिलीवरी", hint: "गति, ऊर्जा, और भाव की बनावट" },
    },
    choiceLabel: { a: "A ज़्यादा करीब है", tie: "कोई फ़र्क नहीं", b: "B ज़्यादा करीब है" },
    loadErrorFallback: "यह तुलना लोड नहीं हो सकी",
    eyebrow: "अंधी तुलना",
    title: "बिना बताए, ज़्यादा करीब वाली आवाज़ चुनें",
    intro: "दो छिपे हुए आउटपुट को परत दर परत मिलाएं। पूरी समीक्षा पूरी होने तक इनकी पहचान छिपी रहती है।",
    sealAriaLabel: "समीक्षा की गोपनीयता स्थिति",
    blindedLabel: "छिपा हुआ",
    mappingNote: "A/B मैपिंग सिर्फ़ सर्वर पर रहती है",
    loadingAriaLabel: "अंधी समीक्षा लोड हो रही है",
    comparisonUnavailable: "तुलना उपलब्ध नहीं है",
    tryAgain: "फिर कोशिश करें",
    emptyHeadline: "अभी समीक्षा के लिए कोई योग्य उम्मीदवार नहीं है।",
    emptyNote: "यह तभी खुलता है जब एक फ़्रीज़ किया टेस्ट सेट और दो एन्क्रिप्टेड उम्मीदवार आउटपुट कम से कम 30 तुलनाओं के लिए मौजूद हों।",
    completeHeadline: "अंधी समीक्षा पूरी हुई",
    completeNote: "{n} तुलनाएं सील हो गई हैं। सुरक्षा, निजता, और सांख्यिकी गेट तय करते हैं कि यह उम्मीदवार आगे बढ़ सकता है या नहीं।",
    comparisonOfLabel: "तुलना {n2} में से {n}",
    sealedCountLabel: "{n} सील हुईं",
    situationLabel: "स्थिति",
    optionsAriaLabel: "गुमनाम जवाब विकल्प",
    anonymousOutput: "गुमनाम आउटपुट",
    orWord: "या",
    judgeEveryLayer: "हर परत परखें",
    judgeInstruction: "सिर्फ़ इस स्थिति के आधार पर चुनें। बराबरी भी एक उपयोगी सबूत है।",
    layersJudged: "{n2} में से {n} परतें परखी गईं",
    sealingComparison: "तुलना सील की जा रही है...",
    sealAndContinue: "सील करें और आगे बढ़ें",
  },

  processingReview: {
    reasonLabel: {
      accepted: {
        matches_subject: "मुझसे मिलता है",
        clean_identity_signal: "साफ़ पहचान संकेत",
        measurement_verified: "मापन सत्यापित",
        segment_verified: "स्पीकर सेगमेंट सत्यापित",
      },
      rejected: {
        wrong_speaker: "गलत स्पीकर",
        third_party_present: "कोई और व्यक्ति मौजूद है",
        poor_quality: "क्वालिटी बहुत खराब है",
        corrupt_or_incomplete: "करप्ट या अधूरा",
        synthetic_or_replayed: "सिंथेटिक या रीप्ले किया गया",
        privacy_risk: "गोपनीयता जोखिम",
      },
      superseded: {
        better_variant_selected: "बेहतर वैरिएंट चुना गया",
        newer_measurement: "नया मापन",
        corrected_segmentation: "सेगमेंटेशन ठीक किया गया",
        source_replaced: "सोर्स बदला गया",
      },
    },
    recently: "हाल ही में",
    contentWithheld: "कंटेंट रोका गया है। सिर्फ़ यहां दिखे समय, विश्वास स्तर, और उद्गम की समीक्षा करें।",
    needsReview: "समीक्षा चाहिए",
    reviewAriaLabel: "{label} की समीक्षा करें",
    decisionSelectLabel: "फैसला",
    reasonSelectLabel: "वजह",
    optionAccept: "स्वीकार करें",
    optionReject: "अस्वीकार करें",
    optionSupersede: "बदलें",
    saving: "सेव हो रहा है",
    recordReview: "समीक्षा दर्ज करें",
    decisionWithheldNote: "यहां फैसला उपलब्ध नहीं है क्योंकि सबूत की सामग्री जानबूझकर रोकी गई है।",
    confidenceNotReported: "विश्वास स्तर नहीं बताया गया",
    confidencePct: "{n}% विश्वास",
    endpointSuffix: "{n} सेकंड एंडपॉइंट",
    unreportedFamily: "न बताया गया परिवार",
    unreportedAdapter: "न बताया गया एडाप्टर",
    eyebrow: "आपकी समीक्षा",
    title: "देखें हमने क्या निकाला, फिर मंज़ूर करें",
    refreshing: "रीफ़्रेश हो रहा है",
    refresh: "रीफ़्रेश करें",
    intro:
      "सिर्फ़ समीक्षा के लिए सुरक्षित माप दिखाए जाते हैं। कच्चे ट्रांसक्रिप्ट, वॉइस वेक्टर, स्टोरेज लोकेशन, " +
      "प्रोवाइडर रेफरेंस, और स्थायी डाउनलोड लिंक कभी इस पेज पर नहीं आते। एक निजी सुनने का लिंक तभी बनता है जब " +
      "आप सुनें दबाते हैं, और यह 60 सेकंड में खत्म हो जाता है।",
    loadingReceipts: "निजी प्रोसेसिंग रसीदें लोड हो रही हैं",
    emptyHeadline: "अभी कोई प्रोसेसिंग रसीद नहीं है",
    emptyNote: "ऊपर एक सोर्स जोड़ें। यह तभी दिखेगा जब निजी प्रोसेसिंग शुरू होगी।",
    sourceTitle: "{label} सोर्स",
    pipelineStepOne: "{n} पाइपलाइन स्टेप",
    pipelineStepMany: "{n} पाइपलाइन स्टेप",
    derivedVariantOne: "{n} निकाला गया वैरिएंट",
    derivedVariantMany: "{n} निकाले गए वैरिएंट",
    evidenceRecordOne: "{n} सबूत रिकॉर्ड",
    evidenceRecordMany: "{n} सबूत रिकॉर्ड",
    pipelineStepsAriaLabel: "पाइपलाइन स्टेप",
    noPipelineAttempt: "अभी कोई पाइपलाइन प्रयास दर्ज नहीं हुआ।",
    attemptLabel: "प्रयास {n}",
    selectedVoiceBadge: "चुनी गई आवाज़",
    opening: "खोला जा रहा है",
    listenPrivately: "निजी तौर पर सुनें",
    selecting: "चुना जा रहा है",
    selected: "चुना गया",
    useThisVoice: "यह आवाज़ इस्तेमाल करें",
    cannotPlayAudio: "आपका ब्राउज़र यह निजी ऑडियो नहीं चला सकता।",
    linkExpiresNote: "यह साइन किया लिंक एक मिनट से कम में खुद खत्म हो जाता है।",
    noReviewableEvidence: "इस सोर्स के लिए समीक्षा योग्य कोई सबूत नहीं भेजा गया।",
    draftOnlyEyebrow: "सिर्फ़ ड्राफ्ट",
    voiceBuildGateTitle: "वॉइस बिल्ड गेट",
    voiceBuildGateIntro:
      "क्यू में लगा बिल्ड इस्तेमाल के लिए तैयार नहीं होता। एक अलग मंज़ूरी और एक असली, अलग से रखा गया " +
      "मूल्यांकन अभी भी ज़रूरी है।",
    acousticFamilies: "ध्वनि परिवार",
    voiceMeasurements: "आवाज़ माप",
    qualityMeasurements: "क्वालिटी माप",
    speakerSegments: "स्पीकर सेगमेंट",
    queueingDraft: "ड्राफ्ट क्यू में डाला जा रहा है",
    queueDraftVoice: "ड्राफ्ट आवाज़ क्यू में डालें",
    buildLedger: "बिल्ड लेजर",
    immutableDraftLedger: "अपरिवर्तनीय ड्राफ्ट लेजर",
    voiceVersionStatus: "आवाज़ वर्शन {n}, {label}",
    voicePrintFamiliesDetail: "{n} स्वतंत्र वॉइस-प्रिंट परिवार",
    targetSegmentsDetail: "{n} टारगेट सेगमेंट",
    enrollmentArtifactsDetail: "{n} निजी एनरोलमेंट कलाकृतियां",
    draftsCannotSynthesize:
      "ड्राफ्ट ऑडियो नहीं बना सकते। मंज़ूरी के लिए अभी भी मालिक का कैलिब्रेशन और एक असली, अलग से रखा गया " +
      "पहचान मूल्यांकन ज़रूरी है।",
    errorProcessingUnavailable: "प्रोसेसिंग समीक्षा अभी उपलब्ध नहीं है",
    errorDecisionNotRecorded: "फैसला दर्ज नहीं हो सका",
    errorDraftNotQueued: "ड्राफ्ट बिल्ड क्यू में नहीं लगाया जा सका",
    errorAuditionNotOpened: "निजी सुनवाई नहीं खोली जा सकी",
    errorCandidateNotSelected: "आवाज़ उम्मीदवार चुना नहीं जा सका",
    noticeReviewRecorded: "समीक्षा का फैसला एक स्थायी रसीद के रूप में दर्ज हो गया।",
    noticeCandidateSelected: "आवाज़ उम्मीदवार चुना गया। मौजूदा ड्राफ्ट हटा दिए गए ताकि अगला वॉइस बिल्ड यही सटीक ऑडियो इस्तेमाल करे।",
    noticeDraftQueued: "ड्राफ्ट वॉइस बिल्ड क्यू में डाला गया। इस्तेमाल होने से पहले अभी भी आपकी मंज़ूरी चाहिए।",
  },

  personModelStudio: {
    blockers: {
      self_name_required: "वह नाम पुष्ट करें जो आपका AI खुद के लिए इस्तेमाल करता है",
      language_identity_required: "इसकी भाषा और कोड-स्विचिंग पहचान पुष्ट करें",
      behavior_evidence_required: "कम से कम एक व्यवहार या सुधार पैटर्न देखें",
      boundary_evidence_required: "कम से कम एक निजी सीमा पुष्ट करें",
      critical_identity_conflict: "टकराते हुए पहचान दावे सुलझाएं",
    },
    extractionBlockers: {
      transcription_consent_required: "ट्रांसक्रिप्शन की अनुमति दें",
      training_consent_required: "सहायता प्राप्त दावा निष्कर्षण के लिए AI-निर्माण अनुमति दें",
      reviewed_subject_transcript_required: "कम से कम एक सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें",
    },
    confidencePct: "{n}% विश्वास",
    citedSourceOne: "{n} उद्धृत सोर्स",
    citedSourceMany: "{n} उद्धृत सोर्स",
    keepOut: "बाहर रखें",
    notAccurate: "सही नहीं है",
    outdated: "पुराना",
    thisIsMe: "यह मैं हूं",
    reviewClaimAriaLabel: "इस दावे की समीक्षा करें",
    eyebrow: "हमने आपके बारे में क्या सीखा",
    title: "हमें जो लगता है हमने आपके बारे में सीखा, एक-एक दावे के रूप में",
    intro:
      "पहचान, भाषा, व्यवहार, मूल्य, सीमाएं, और आत्मकथा को अलग-अलग सबूत-आधारित दावों के रूप में पुष्ट करें। " +
      "टकराव छिपाए नहीं जाते, एक भरोसेमंद कल्पना में औसत नहीं किए जाते।",
    approvedVersionLabel: "मंज़ूर वर्शन",
    loadingClaims: "समीक्षा किए गए दावे लोड हो रहे हैं...",
    retry: "फिर कोशिश करें",
    proposedClaims: "प्रस्तावित दावे",
    accepted: "स्वीकृत",
    criticalConflicts: "गंभीर टकराव",
    citedExtractionEyebrow: "उद्धृत निष्कर्षण",
    citedExtractionTitle: "अपनी समीक्षा की गई रिकॉर्डिंग को अपने नियंत्रण वाले दावों में बदलें",
    citedExtractionIntro:
      "सिर्फ़ स्वीकृत, लक्षित-स्पीकर ट्रांसक्रिप्ट हिस्से ही योग्य हैं। कच्चे ट्रांसक्रिप्ट सिर्फ़ सर्वर पर रहते " +
      "हैं, सीधी पहचान निष्कर्षण कॉल से पहले छिपाई जाती है, और हर नतीजा तब तक सिर्फ़ एक प्रस्ताव रहता है जब तक " +
      "आप उसे नीचे न देख लें।",
    eligibleSpans: "योग्य हिस्से",
    lastProposed: "पिछली बार प्रस्तावित",
    noExtractionRunYet: "अभी कोई निष्कर्षण नहीं हुआ",
    extractingPrivately: "निजी तौर पर निकाला जा रहा है...",
    extractNewEvidence: "नया सबूत निकालें",
    extractCitedClaims: "उद्धृत दावे निकालें",
    noClaimsHeadline: "अभी कोई व्यवहार या याददाश्त दावे नहीं हैं।",
    noClaimsNote: "प्रोसेस किया गया सबूत यहां समीक्षा के लिए दिखेगा। कच्चे ट्रांसक्रिप्ट, वेक्टर, और स्टोरेज पाथ रोके रहते हैं।",
    buildIsDeterministicNote: "एक बिल्ड निश्चित और वर्शन वाला होता है। इसे मंज़ूर करना कभी इन्फ़रेंस या आवाज़ बनाने की अनुमति नहीं देता।",
    checkingEvidence: "सबूत जांचा जा रहा है...",
    approveProfileVersion: "प्रोफ़ाइल v{n} मंज़ूर करें",
    building: "बनाया जा रहा है...",
    buildReviewDraft: "समीक्षा ड्राफ्ट बनाएं",
    errorExtractionUnavailable: "उद्धृत निष्कर्षण की स्थिति लोड नहीं हो सकी",
    errorProfileUnavailable: "हमने आपके बारे में जो सीखा वह लोड नहीं हो सका",
    errorClaimNotSaved: "दावे की समीक्षा सेव नहीं हुई",
    errorBuildRefused: "हमने आपके बारे में जो सीखा उसे बनाना अस्वीकार हुआ",
    errorApproveChanged: "प्रोफ़ाइल बदल गई और मंज़ूर नहीं हो सकी",
    errorExtractionFailed: "उद्धृत दावे नहीं निकाले जा सके",
  },
  showcase: {
    title: "अपने पेज पर दिखाएं",
    intro: "पांच तक सवाल जवाब, जो कोई अजनबी जुड़ने से पहले आपके अपने पब्लिक पेज पर देखेगा। आपके अपने शब्द, आपके अपने क्रम में।",
    publishFirst: "पहले अपना रूम पब्लिश करें, फिर आप अपने पेज पर जवाब दिखा सकते हैं।",
    slotLabel: "स्लॉट {n}, कुल 5 में से",
    questionPlaceholder: "एक सवाल जो लोग सच में पूछते हैं",
    answerPlaceholder: "आपका जवाब, आपके अपने शब्दों में",
    save: "सेव करें",
    saving: "सेव हो रहा है...",
    remove: "हटाएं",
    removing: "हटाया जा रहा है...",
    removed: "आपके पेज से हटा दिया गया।",
    saved: "आपके पेज पर सेव हो गया।",
    copyViolation: "यह टेक्स्ट ऐसे नहीं चल सकता। डैश हटाएं या जिस शब्द पर निशान लगा है उसे बदलें, फिर दोबारा कोशिश करें।",
  },
  creatorExport: {
    eyebrow: "मालिक नियंत्रण",
    title: "सब कुछ डाउनलोड करें",
    body: "यह प्लेटफ़ॉर्म आपके और आपके AI के बारे में जो कुछ भी रखता है, वह सब: आपकी सामग्री, आपकी आवाज़, आपके रूम की अपनी सेटिंग्स, आपकी पेमेंट, आपके रिव्यू फ़ैसले। किसी फॉलोअर ने आपके AI से निजी तौर पर जो कहा, वह कभी नहीं, और किसी फॉलोअर का डेटा पांच से कम की गिनती में भी कभी नहीं, वह हमेशा उन्हीं का रहता है।",
    button: "सब कुछ डाउनलोड करें",
    downloading: "आपका डाउनलोड तैयार हो रहा है...",
    rateLimited: "आप यह दिन में एक बार मांग सकते हैं। कल फिर कोशिश करें।",
    error: "आपका डाउनलोड तैयार नहीं हो सका। कृपया फिर कोशिश करें।",
    done: "आपका डाउनलोड शुरू हो गया है।",
  },
  suiteSeatLock: {
    mandateNote:
      "अगर आप इस Suite के लिए UPI से भुगतान करते हैं, तो जब तक वह सदस्यता चलती है, उसकी सीट संख्या तय रहती है। बाद में बदलने के " +
      "लिए, इसे रद्द करें, यह अवधि खत्म होने तक काम करती रहेगी, फिर जितनी सीटें चाहिए उतनी संख्या पर एक नई सदस्यता शुरू करें। " +
      "कार्ड से भुगतान करने पर कभी भी अपडेट किया जा सकता है।",
    seatsLockedByMandate:
      "यह Suite UPI या बैंक ई-मैंडेट से भुगतान करता है, और Razorpay इस तरह की सदस्यता पर सीटें बदलने की अनुमति नहीं देता। नीचे " +
      "इसे रद्द करें, यह अवधि खत्म होने तक काम करती रहेगी, फिर जितनी सीटें चाहिए उतनी संख्या पर एक नई सदस्यता शुरू करें।",
  },
  creatorPush: {
    title: "इस हफ़्ते की खबर, आपके फ़ोन पर",
    intro: "हर सोमवार सुबह, आपके रूम के बारे में एक छोटा सा पुश: नए फॉलोअर और मैसेज। इसके लिए इस डिप्लॉयमेंट की अपनी पुश-की ज़रूरी है।",
    notConfigured: "इस डिप्लॉयमेंट पर पुश अलर्ट अभी सेट नहीं हैं।",
    turnOn: "इस डिवाइस पर साप्ताहिक पुश चालू करें",
    turnOff: "इस डिवाइस पर साप्ताहिक पुश बंद करें",
    error: "इस डिवाइस पर अलर्ट सेटिंग नहीं बदली जा सकी।",
  },
  showcasePicker: {
    pickButton: "अपनी समीक्षाओं में से चुनें",
    pickTitle: "वे कार्ड जिन्हें आपने पहले ही सही कहा है",
    pickEmpty: "अभी चुनने के लिए कुछ नहीं। पहले मिलें में कुछ कार्ड तय करें।",
    pickLoading: "देखा जा रहा है...",
    pickError: "आपके तय किए गए कार्ड पढ़े नहीं जा सके",
    pickUse: "इसे इस्तेमाल करें",
    pickCancel: "रद्द करें",
  },
  reviewQueueFlags: {
    flagsTitle: "फ़ॉलोअर्स द्वारा फ़्लैग किए गए",
    timesOne: "{n} बार फ़्लैग किया गया।",
    timesMany: "{n} बार फ़्लैग किया गया।",
    reasonsLabel: "कारण: {label}",
    reasonWrong: "गलत",
    reasonHarmful: "हानिकारक",
    reasonNotThem: "यह वे नहीं हैं",
    reasonOther: "अन्य",
    soundsRightAnyway: "फिर भी सही लगा",
    dismissing: "सेव हो रहा है...",
    dismissed: "आपकी फ़्लैग सूची से हटा दिया गया।",
    errorAction: "वह कार्रवाई सेव नहीं हो सकी",
  },
  poster: {
    download: "पोस्टर डाउनलोड करें (A4)",
  },

  activityPanel: {
    groupYourTurn: "आपकी बारी",
    groupWorkingNow: "अभी काम चल रहा है",
    groupStopped: "रुका हुआ",
    groupFinished: "पूरा हुआ",
    feedTitle: "हर अपलोड अभी कहां है",
    feedLede: "आपने जो कुछ भी दिया है, और उसका क्या हो रहा है। जिसकी आपको ज़रूरत है वह सबसे ऊपर है।",
    meetTitle: "क्या पूरा हुआ, और क्या नहीं",
    meetLede: "अगर आपका AI कोई ऐसी बात नहीं जानता जो आपने ज़रूर दी थी, तो वजह अक्सर यहीं मिलती है। अधूरा काम पहले।",
    justNow: "अभी-अभी",
    minutesAgo: "{n} मिनट पहले",
    hourAgoOne: "1 घंटा पहले",
    hoursAgoMany: "{n} घंटे पहले",
    dayAgoOne: "1 दिन पहले",
    daysAgoMany: "{n} दिन पहले",
    stepsDoneAriaLabel: "{n2} में से {n} स्टेप पूरे",
    notConnectedTitle: "{label}: अभी कनेक्ट नहीं है।",
    notConnectedBody: "जब तक यह सेटअप नहीं होता, इस लेन में कुछ नहीं चल सकता, इसलिए यहां खाली लिस्ट का मतलब यह नहीं कि कुछ हुआ ही नहीं।",
    notConnectedMissingLabel: "क्या गुम है:",
    loadingGroupName: "लोड हो रहा है",
    emptyState: "अभी तक कुछ शुरू नहीं हुआ। एक रिकॉर्डिंग, फ़ाइल या अपना चैनल जोड़ें, और वह यहां चलते हुए दिखेगा।",
    ofCount: "{n2} में से {n}",
    doneLabel: "पूरे",
    retryingLabel: "काम चल रहा है",
    errorCouldNotRead: "गतिविधि पढ़ी नहीं जा सकी",
    errorRetryFailed: "फिर कोशिश नहीं हो सकी",
    errorAlreadyMoved: "वह अपलोड पहले ही आगे बढ़ चुका था, इसलिए पूरा करने के लिए कुछ नहीं बचा।",
  },

  channelsStudio: {
    eyebrow: "चैनल",
    title: "आपका AI कहां तक पहुंचा जा सकता है",
    intro: "पब्लिश करने से आपका AI पहुंच में आता है। यहीं वह लोगों से मिलता है। नीचे हर चैनल आपका अपना है: आपकी साइट, आपका बॉट, आपका बिज़नेस नंबर। आप इनमें से किसी को भी बिना हमसे पूछे कभी भी रोक या रिटायर कर सकते हैं।",
    embedCardTitle: "एम्बेड कोड लें",
    embedCardBody: "इसे अपने नियंत्रण वाले किसी भी पेज पर पेस्ट करें। यह प्लेन HTML साइट, वर्डप्रेस थीम, स्क्वेयरस्पेस कोड ब्लॉक, जहां भी स्क्रिप्ट टैग चलता है वहां काम करता है। यह कोई कुकी सेट नहीं करता और आपके विज़िटर से कुछ नहीं मांगता।",
    embedSnippetAriaLabel: "एम्बेड स्निपेट",
    copyEmbedCode: "एम्बेड कोड कॉपी करें",
    copiedLabel: "कॉपी हो गया",
    disclosureNote: "हर विज़िटर अपने पहले मैसेज से पहले वही डिस्क्लोज़र कार्ड देखता है जिसे आपने मंज़ूर किया था। यह हमारी तरफ़ से जवाब के साथ भेजा जाता है, पेज से नहीं दिखाया जाता। जिस साइट ने इसे हटा दिया हो, वह बातचीत ही नहीं कर पाएगी।",
    loadingChannels: "चैनल लोड हो रहे हैं...",
    statusLabel: "स्टेटस",
    notSetUp: "सेटअप नहीं है",
    webWidgetTitle: "आपकी वेबसाइट",
    webWidgetRefLabel: "पब्लिक स्लग",
    webWidgetBlurb: "आपके नियंत्रण वाले किसी भी पेज पर एक चैट बबल। HTML की एक लाइन, कहीं और कोई अकाउंट नहीं।",
    webWidgetCost: "किसी के लिए आवेदन नहीं करना। लाइन पेस्ट करते ही लाइव।",
    telegramTitle: "टेलीग्राम",
    telegramRefLabel: "बॉट ID",
    telegramSecretLabel: "बॉट टोकन",
    telegramBlurb: "@BotFather में बनाया गया आपका अपना बॉट, आपके AI के तौर पर जवाब देता है।",
    telegramCost: "कोई रिव्यू प्रोसेस नहीं। आप बॉट बनाते हैं और हमारा दिया एक वेबहुक URL रजिस्टर करते हैं।",
    whatsappTitle: "व्हाट्सएप",
    whatsappRefLabel: "फ़ोन नंबर ID",
    whatsappSecretLabel: "एक्सेस टोकन",
    whatsappBlurb: "एक व्हाट्सएप बिज़नेस नंबर, जो आपके AI के तौर पर जवाब देता है।",
    whatsappCost: "एक मेटा बिज़नेस अकाउंट, एक वेरिफ़ाइड बिज़नेस, और क्लाउड API पर रजिस्टर्ड नंबर चाहिए। मेटा का रिव्यू दिनों से हफ़्तों में नापा जाता है, और यह उनका फ़ैसला है, हमारा नहीं।",
    statusDraft: "लाइव नहीं। नीचे डीटेल पूरी करें।",
    statusConnected: "लाइव",
    statusPaused: "रुका हुआ। यहां कुछ जवाब नहीं दिया जाता।",
    statusRevoked: "रद्द। यह पता हमेशा के लिए रिटायर हो गया है।",
    secretOnFile: "फ़ाइल में मौजूद है। बदलने के लिए नया पेस्ट करें।",
    secretVaultNote: "हमारे सीक्रेट वॉल्ट में रखा गया, कभी डेटाबेस में नहीं और दोबारा कभी नहीं दिखाया जाता, आपको भी नहीं। अगर यह कभी बदले, तो यहां बदलें।",
    saving: "सेव हो रहा है...",
    update: "अपडेट करें",
    connect: "कनेक्ट करें",
    pause: "रोकें",
    resume: "फिर शुरू करें",
    retire: "रिटायर करें",
    retiredNote: "हमेशा के लिए रिटायर। वह पता आपके AI से दोबारा नहीं जुड़ेगा। अगर यह चैनल वापस चाहिए तो नया सेटअप करें।",
    instagramTitle: "इंस्टाग्राम DM",
    instagramNotOffered: "अभी उपलब्ध नहीं है, और यह वह वजह है जो रोक रही है, कोई तारीख़ नहीं।",
    instagramWhatMetaRequiresLabel: "मेटा को क्या चाहिए",
    instagramRequirement: "इंस्टाग्राम मैसेजिंग की एडवांस्ड एक्सेस, जिसके लिए वेरिफ़ाइड बिज़नेस, लाइव मोड में ऐप, और इंटीग्रेशन के रिकॉर्ड किए गए डेमो के साथ पूरा ऐप रिव्यू चाहिए। मेटा यह हर ऐप को देता है, हर टीचर को नहीं, और इंतज़ार हफ़्तों से महीनों में नापा जाता है।",
    instagramNoFakeButton: "हम यहां ऐसा बटन नहीं लगाएंगे जो चुपचाप कुछ न करे।",
    liveNotice: "{name} लाइव है।",
    draftNotice: "{name} ड्राफ्ट के तौर पर सेव हुआ। जवाब देने से पहले इसे बाकी डीटेल चाहिए।",
    errorRequestFailed: "रिक्वेस्ट पूरी नहीं हुई",
  },

  teacherSheetStudio: {
    eyebrow: "शीट रिव्यू",
    title: "पुष्टि करें कि {name} कैसे पढ़ाते हैं",
    titleFallbackName: "यह टीचर",
    intro: "यहां सिर्फ़ वही एडिट किया जा सकता है जो आपको तय करना है। आपके अपलोड से जो ड्राफ्ट हुआ वह सिर्फ़ पढ़ने के लिए है, उसे आप क्लेम्स स्टेप में सुधारते हैं।",
    loadSavedDraft: "सेव किया ड्राफ्ट लोड करें",
    provenanceSeedNotice: "आपके AI के लिए अभी कुछ सेव नहीं हुआ। नीचे के फ़ील्ड खाली हैं या बीच के डिफ़ॉल्ट पर सेट हैं, और इनमें आपका नाम है क्योंकि हम आपको कभी किसी और का नहीं दिखाएंगे। तैयार होने पर सेव करें।",
    serviceUnavailableNotice: "शीट सर्विस ने जवाब नहीं दिया। आप जो भी टाइप करें वह इस ब्राउज़र में रहता है, आपके अकाउंट में सेव नहीं होता।",
    subjectCardTitle: "विषय और सिलेबस कवरेज",
    subjectLabel: "वह विषय जिसमें आपका AI जवाब देता है",
    subjectPhysics: "फ़िज़िक्स",
    subjectChemistry: "केमिस्ट्री",
    subjectMaths: "मैथ्स",
    scopeLabel: "दायरा, और यह क्या जवाब नहीं देता",
    chapterNote: "हर वह चैप्टर चुनें जो आपके AI को पढ़ाना चाहिए। ऑर्गेनिक केमिस्ट्री का जवाब देता फ़िज़िक्स टीचर का AI उनकी ग़लत नुमाइंदगी है।",
    chapterCoverageAriaLabel: "चैप्टर कवरेज",
    strictnessCardTitle: "सख़्ती और गर्मजोशी",
    strictnessWarmthNote: "इनकी पुष्टि आप करते हैं, हम कभी सिर्फ़ अनुमान से तय नहीं करते। यहां ज़्यादा पढ़ लेना 16 साल के बच्चे को असली नुकसान है।",
    strictnessLabel: "सख़्ती: ग़लत जवाब को कितना साफ़ बताया जाता है",
    strictness0: "कभी नाम नहीं लेते, हर चूक को लगभग सही की तरह दोबारा कहते हैं",
    strictness1: "नरम, ज़्यादातर सुधार नरम कर देते हैं",
    strictness2: "जवाब के बारे में सीधे, इंसान के बारे में आसान",
    strictness3: "ग़लत कदम को साफ़ नाम देते हैं, उसी सांस में जब सामने आए",
    strictness4: "कोई नरमी नहीं, ग़लती की सबसे तीखी पढ़त",
    warmthLabel: "गर्मजोशी: उत्साह की मात्रा, सख़्ती से अलग",
    warmth0: "पूरी तरह काम की बात, सुधार के अलावा कोई उत्साह नहीं",
    warmth1: "कभी-कभी, और सिर्फ़ किसी असली, ख़ास जीत के लिए",
    warmth2: "लगातार उत्साह, हमेशा किसी असली काम से जुड़ा",
    warmth3: "डिफ़ॉल्ट रूप से गर्मजोशी भरा, फिर भी ख़ास",
    warmth4: "इस शीट में सबसे ज़्यादा उत्साह की मात्रा",
    ladderCardTitle: "शक़ सुलझाने की सीढ़ी",
    ladderNote: "किसी भी पूरे हल से पहले दिए गए क्रम से हिंट के पायदान। यह अकादमिक ईमानदारी की रीढ़ है। पूरा हल कभी पहला जवाब नहीं होता।",
    removeRungAriaLabel: "पायदान {n} हटाएं",
    removeRung: "हटाएं",
    addRungPlaceholder: "अगला पायदान जोड़ें",
    addRung: "पायदान जोड़ें",
    boundariesCardTitle: "सीमाएं",
    boundariesNote: "identityLife आपका लिखा हुआ है और कभी इनजेस्ट नहीं होता। टीचर की निजी ज़िंदगी आपके AI के लिए मंज़ूर की गई सामग्री नहीं है, तब भी नहीं जब वह आपकी अपनी अपलोड की गई वीडियो में दिखे।",
    identityLifeLabel: "पढ़ाने की ज़िंदगी, एक सांस में",
    mentorBoundaryLabel: "मेंटर की सीमा - यहां एडिट नहीं होती",
    ingestedTitleDraft: "आपके अपलोड से ड्राफ्ट किया गया",
    ingestedTitleEmpty: "अभी तक कुछ ड्राफ्ट नहीं हुआ",
    ingestedNoteDraft: "यहां सिर्फ़ पढ़ने के लिए है। क्लेम्स स्टेप में हर एक की समीक्षा या सुधार करें।",
    ingestedNoteEmpty: "आपके अपलोड प्रोसेस होते ही ये भर जाएंगे। दोनों ही सूरत में यहां सिर्फ़ पढ़ने के लिए है, और क्लेम्स स्टेप में सुधारा जाता है।",
    ingestedStatusDraft: "आपके अपलोड से ड्राफ्ट किया गया",
    ingestedStatusEmpty: "अभी नहीं सीखा गया",
    languageVoiceRuleLabel: "भाषा / आवाज़ का अनुपात",
    sttSoundAlikesLabel: "STT मिलती-जुलती आवाज़ों के जोड़े",
    boardVerbalismsLabel: "बोर्ड की बोलचाल (कैचफ़्रेज़ फ़ील्ड)",
    notationConventionsLabel: "नोटेशन के रिवाज़",
    analogyBankLabel: "ख़ास मिसालें",
    commonMistakeBankLabel: "आम ग़लतियों की सूची",
    commonMistakeBankSummary: "{n} पंक्तियां, स्ट्रैंड-दायरे में",
    publishNote: "यहां सेव करना आपके AI को कभी पब्लिश नहीं करता। पब्लिश पूरी तैयारी और सहमति की जांच अलग से चलाता है।",
    saved: "शीट ड्राफ्ट सेव हुआ।",
    savedLocalOnly: "आपके अकाउंट में सेव नहीं हुआ। शीट सर्विस ने जवाब नहीं दिया, इसलिए यह ड्राफ्ट अभी सिर्फ़ इस ब्राउज़र में है।",
    saving: "सेव हो रहा है...",
    save: "शीट ड्राफ्ट सेव करें",
  },

  voicePreviewLab: {
    title: "ड्राफ्ट आवाज़ बनाएं और दो टेक की तुलना करें",
    intro: "यह निजी ड्राफ्ट सिर्फ़ आपके कानों और फ़ैसले के लिए है। यह कॉल में शामिल नहीं हो सकता या आपका AI चालू नहीं कर सकता।",
    checking: "जांचा जा रहा है",
    refreshDraft: "ड्राफ्ट रीफ़्रेश करें",
    draftVersionLabel: "ड्राफ्ट आवाज़ बिल्ड, वर्शन {n}",
    draftRequired: "ड्राफ्ट ज़रूरी है",
    identityModelsBound: "{n} पहचान प्रोफ़ाइल जुड़ी हुई हैं",
    reviewFirst: "पहले अपनी चुनी आवाज़ रिव्यू करें और बनाएं",
    languageLegend: "भाषा",
    languageEnglish: "अंग्रेज़ी",
    languageHindi: "हिन्दी और हिंग्लिश",
    whatShouldDraftSay: "ड्राफ्ट को क्या कहना चाहिए?",
    charactersLeft: "{n}/600 अक्षर बचे। सुनाई देने वाला AI डिस्क्लोज़र अपने आप जुड़ जाता है।",
    disclosureAddedNote: "सुनाई देने वाला AI डिस्क्लोज़र अपने आप जुड़ जाता है।",
    deliveryLegend: "अंदाज़",
    styleFaithfulLabel: "वफ़ादार",
    styleFaithfulCopy: "कसी हुई पहचान और स्थिर रफ़्तार",
    styleBalancedLabel: "संतुलित",
    styleBalancedCopy: "रोज़मर्रा की बोली जैसा सहज अंदाज़",
    styleExpressiveLabel: "भावुक",
    styleExpressiveCopy: "ज़्यादा भावनात्मक उतार-चढ़ाव और जोखिम",
    protectingPreview: "आपका प्रिव्यू सुरक्षित किया जा रहा है",
    generatePreview: "निजी प्रिव्यू बनाएं",
    coldStartNotice: "स्केल-टू-ज़ीरो वॉइस लैब अपने पहले रन में कुछ मिनट ले सकती है।",
    yourProtectedDraft: "आपका सुरक्षित ड्राफ्ट",
    listenOnceNote: "पहचान के लिए एक बार सुनें, अंदाज़ के लिए एक बार, फिर एक बार में एक कंट्रोल बदलें।",
    audioFallback: "आपका ब्राउज़र यह सुरक्षित WAV नहीं चला सकता।",
    disclosureRowLabel: "डिस्क्लोज़र",
    disclosureRowValue: "सुनाई देता है",
    watermarksRowLabel: "वॉटरमार्क",
    provenanceRowLabel: "प्रोवेनेंस",
    provenanceRowValue: "C2PA साइन किया हुआ",
    receiptLine: "रसीद {n}। बिल्ड {n2}।",
    roomReady: "कमरा तैयार है",
    noDraftYet: "अभी कोई ड्राफ्ट बोल नहीं सकता",
    chooseWordsNote: "शब्द और अंदाज़ चुनें। कोई भी ऑडियो बिना निशान के सुरक्षा सीमा से बाहर नहीं जाता।",
    needRecordingNote: "पहले आपको प्रोसेस की गई रिकॉर्डिंग चाहिए। फ़ीड स्टेप पर एक जोड़ें, हम उससे ड्राफ्ट आवाज़ बनाएंगे।",
    proofOwnerOnly: "सिर्फ़ मालिक",
    proofSelfOnly: "सिर्फ़ आपके लिए",
    proofNoRuntimeAccess: "कोई रनटाइम एक्सेस नहीं",
    preferenceLabTag: "ब्लाइंड पसंद लैब",
    preferenceLabHeading: "अपने कानों से अपने AI को सिखाएं।",
    preferenceLabIntro: "सर्वर एक बहुभाषी चुनौती डेक को संतुलित रखता है और अगला सबसे जानकारी-भरा छुपा हुआ अंतर चुनता है। दोनों तरफ़ तय शब्द, पहचान का सबूत, वॉइस इंजन, भाषा, और सैंपलिंग सीड एक जैसी रहती है।",
    renderingAB: "पहले A, फिर B बनाया जा रहा है",
    newBlindPair: "नई ब्लाइंड जोड़ी",
    startBlindAB: "ब्लाइंड A/B शुरू करें",
    adaptiveComparisonLabel: "अनुकूल तुलना {n}",
    conditionsCoveredLabel: "{n2} में से {n} अंदाज़ कवर हुए",
    promptFamiliesLabel: "{n2} में से {n} प्रॉम्प्ट समूह",
    boundaryConverged: "सीमा तय हो गई",
    stillLearning: "अभी भी सीख रहे हैं",
    challengeSuffix: "चुनौती",
    candidateLetterA: "A",
    candidateLetterB: "B",
    protectedCandidateLabel: "सुरक्षित उम्मीदवार",
    completedLabel: "पूरा हुआ",
    listenFullyNote: "फ़ैसला लेने से पहले पूरा सुनें",
    audioCandidateFallback: "सुरक्षित आवाज़ उम्मीदवार।",
    preferenceSecured: "पसंद दर्ज हो गई",
    choiceNeither: "कोई भी उम्मीदवार सही नहीं बैठा।",
    choiceTie: "दोनों उम्मीदवार बराबर थे।",
    choiceCloser: "{label} ज़्यादा क़रीब था।",
    conditionSummary: "A {label} था; B {label2} था।",
    evidenceLine: "सबूत {n} ठीक इसी जनरेशन से बंधा है।",
    whatSeparatedThem: "इन्हें अलग किस बात ने किया?",
    optionalLabel: "वैकल्पिक",
    chooseCloserAriaLabel: "ज़्यादा क़रीब सुरक्षित आवाज़ चुनें",
    aIsCloser: "A ज़्यादा क़रीब है",
    bIsCloser: "B ज़्यादा क़रीब है",
    both: "दोनों",
    neither: "कोई नहीं",
    finishBothToUnlock: "फ़ैसला अनलॉक करने के लिए दोनों उम्मीदवार पूरे सुनें।",
    buildingTwoTakes: "दो पूरी तरह सुरक्षित जनरेशन बनाई जा रही हैं। कोल्ड स्टार्ट कुछ मिनट ले सकते हैं।",
    noComparisonOpen: "कोई तुलना खुली नहीं है। लैब एक नई चुनौती वाला वाक्य देगी और उसे दोनों तरफ़ एक जैसा रखेगी।",
    voiceDeliveryTag: "वॉइस डिलीवरी",
    versionFrozen: "वर्शन {n} फ़्रीज़ हो गया है",
    buildDeliveryCandidate: "एक स्थायी डिलीवरी उम्मीदवार बनाएं",
    championBoundNote: "अंदाज़ {label} अब तक के {n} ठीक फ़ैसलों से बंधा है। यह अनदेखी जांच तक सिर्फ़ ड्राफ्ट रहता है।",
    candidateCreatedNote: "उम्मीदवार तभी बनता है जब बहुभाषी तुलना की सीमा गहरी और विविध हो जाए।",
    comparisonsLabel: "{n} तुलनाएं",
    conditionsFractionLabel: "{n2} में से {n} अंदाज़",
    promptsFractionLabel: "{n2} में से {n} प्रॉम्प्ट",
    freezingEvidence: "सबूत फ़्रीज़ किया जा रहा है",
    freezeUpdatedVersion: "अपडेट किया वर्शन फ़्रीज़ करें",
    freezeDeliveryCandidate: "डिलीवरी उम्मीदवार फ़्रीज़ करें",
    moreEvidenceRequired: "और ब्लाइंड सबूत चाहिए। एक जाने-पहचाने वाक्य को दोहराने से यह गेट नहीं खुलता।",
    freezingDoesNotActivate: "फ़्रीज़ करना आवाज़ को चालू नहीं करता। अगला एक अलग अनदेखी ABX जांच है।",
    unseenSpeechTag: "अनदेखी बोली की जांच",
    unseenSpeechHeading: "क्या फ़्रीज़ की गई डिलीवरी हर जगह चलती है?",
    unseenSpeechIntro: "कैलिब्रेशन से बाहर रखे छह प्रॉम्प्ट, हर एक दो तय सीड के साथ जांचा गया। उम्मीदवार अपने सबसे मज़बूत प्रतिद्वंद्वी के सामने छुपा रहता है।",
    heldOutJudgmentsLabel: "अनदेखे फ़ैसले",
    holdoutChallengeSuffix: "अनदेखी जांच",
    heldOutCandidateLabel: "अनदेखा उम्मीदवार",
    listenFully: "पूरा सुनें",
    heldOutJudgmentSecured: "अनदेखा फ़ैसला दर्ज हो गया",
    startNextCellNote: "जब तैयार हों तो अगला अनदेखा हिस्सा शुरू करें।",
    chooseCloserHeldOutAriaLabel: "ज़्यादा क़रीब अनदेखी आवाज़ चुनें",
    ownerHoldoutPassed: "मालिक की अनदेखी जांच पास हुई",
    ownerHoldoutFailed: "मालिक की अनदेखी जांच नहीं हो पाई",
    notProductionQualificationNote: "यह प्रोडक्शन के लिए योग्यता नहीं है। पहचान, स्पष्टता, ख़राबी, वॉटरमार्क, निजता और लेटेंसी की अपने-आप चलने वाली जांचें अभी लॉक हैं।",
    securingTrial: "तुलना दर्ज की जा रही है",
    nextUnseenPair: "अगली अनदेखी जोड़ी",
    startHeldOutAB: "अनदेखी A/B शुरू करें",
    finalizeOwnerGate: "मालिक की जांच पक्की करें",
    conditionIdentityAnchor: "पहचान का आधार",
    conditionFaithful: "वफ़ादार",
    conditionSteadyWarm: "स्थिर गर्मजोशी",
    conditionBalanced: "संतुलित",
    conditionWarmExpressive: "गर्म भाव",
    conditionExpressive: "भावुक",
    conditionAnimated: "जोशीला",
    fallbackConditionA: "अंदाज़ A",
    fallbackConditionB: "अंदाज़ B",
    fallbackLearnedDelivery: "सीखा हुआ अंदाज़",
    reasonIdentity: "आवाज़ की पहचान",
    reasonAccent: "लहजा",
    reasonRhythm: "रिदम",
    reasonEmotion: "भाव",
    reasonNaturalness: "सहजता",
    reasonPronunciation: "उच्चारण",
    reasonFewerArtifacts: "कम गड़बड़ियां",
    errorStatusUnavailable: "आवाज़ प्रिव्यू का स्टेटस उपलब्ध नहीं है",
    errorPreviewNotGenerated: "सुरक्षित प्रिव्यू नहीं बनाया जा सका",
    errorComparisonNotGenerated: "ब्लाइंड तुलना नहीं बनाई जा सकी",
    errorPreferenceNotSecured: "आवाज़ की पसंद दर्ज नहीं हो सकी",
    errorDeliveryNotFrozen: "आपकी आवाज़ की डिलीवरी फ़्रीज़ नहीं हो सकी",
    errorHeldOutNotGenerated: "अनदेखी तुलना नहीं बनाई जा सकी",
    errorHeldOutJudgmentNotSecured: "अनदेखा फ़ैसला दर्ज नहीं हो सका",
    errorHeldOutResultNotFinalized: "अनदेखा नतीजा पक्का नहीं हो सका",
  },

  voicePreviewPanel: {
    eyebrow: "आपकी आवाज़",
    title: "मेरी आवाज़ का प्रिव्यू",
    introTest: "एक लाइन टाइप करें और मौजूदा ड्राफ्ट को हिन्दी, हिंग्लिश या अंग्रेज़ी में सुनें।",
    introReal: "एक निजी ड्राफ्ट, आपकी अपनी मंज़ूर की गई रिकॉर्डिंग से बना। हर क्लिप बोले गए AI डिस्क्लोज़र से शुरू होता है और एक अनसुना वॉटरमार्क रखता है। प्रिव्यू करने से कुछ चालू नहीं होता और किसी और को यह सुनने नहीं दिया जाता।",
    languageLegend: "प्रिव्यू भाषा",
    languageHindiLabel: "हिन्दी",
    languageHindiHelp: "हिन्दी देवनागरी में लिखें। जाने-पहचाने अंग्रेज़ी शब्द अंग्रेज़ी में रह सकते हैं।",
    languageHinglishLabel: "हिंग्लिश",
    languageHinglishHelp: "रोमन में सहज हिन्दी और अंग्रेज़ी लिखें। हर हिस्सा बनने से पहले प्लान किया जाता है।",
    languageEnglishLabel: "अंग्रेज़ी",
    languageEnglishHelp: "वह ठीक अंग्रेज़ी लाइन लिखें जो आप ड्राफ्ट से कहलवाना चाहते हैं।",
    yourLine: "आपकी लाइन",
    charactersLeftTest: "{n} अक्षर बचे।",
    charactersLeftReal: "{n} अक्षर बचे। बोला गया AI डिस्क्लोज़र आपके लिए जुड़ जाता है।",
    disabledCheckingHeadline: "हम अभी जांच रहे हैं कि आपके पास ड्राफ्ट आवाज़ है या नहीं।",
    disabledCheckingNext: "इसमें बस एक पल लगता है। जांच पूरी होते ही बटन अपने आप चालू हो जाता है।",
    disabledBusyWarming: "वॉइस रनटाइम शुरू हो रहा है, जिसमें ख़ामोशी के बाद दो से पांच मिनट लगते हैं।",
    disabledBusyGenerating: "आपकी लाइन अभी बन रही है।",
    disabledBusyNext: "यह अपने आप फिर कोशिश करता है। आप इसे खुला छोड़ सकते हैं या इस स्टेप पर कुछ और कर सकते हैं।",
    disabledEmptyHeadline: "बॉक्स खाली है, इसलिए कहने के लिए कुछ नहीं है।",
    disabledEmptyNext: "अपने AI के बोलने के लिए एक लाइन टाइप करें।",
    disabledOverLimitHeadline: "यह प्रिव्यू के लिए तय {n} अक्षरों से लंबा है।",
    disabledOverLimitNext: "इसे छोटा करें, बटन चालू हो जाएगा।",
    buttonGenerating: "बन रहा है",
    buttonWaking: "वॉइस लैब जगाई जा रही है",
    buttonAnotherTake: "एक और टेक बनाएं",
    buttonPreview: "मेरी आवाज़ का प्रिव्यू",
    stateReady: "तैयार",
    listenToThisTake: "यह टेक सुनें",
    audioFallback: "आपका ब्राउज़र यह सुरक्षित WAV नहीं चला सकता।",
    pronunciationPlanSummary: "{n} जांचे गए हिन्दी उच्चारण बदलाव लगाए गए",
    spokenAsLabel: "ऐसे बोला गया:",
    originalTextUnchangedNote: "आपका असली टेक्स्ट नहीं बदला। प्लान {n} इस प्रिव्यू के साथ सेव है।",
    disclosureRowLabel: "डिस्क्लोज़र",
    disclosureRowValue: "हर क्लिप में बोला जाता है",
    watermarkRowLabel: "वॉटरमार्क",
    watermarkRowValue: "PerTh, रिलीज़ से पहले जांचा गया",
    notRightYet: "अभी सही नहीं लगा?",
    editLineNote: "लाइन बदलें या भाषा बदलें, फिर एक और टेक बनाएं।",
    editLine: "लाइन बदलें",
    receiptLine: "रसीद {n} · बिल्ड {n2}",
    stateWarming: "जगाया जा रहा है",
    runtimeStarting: "आपका वॉइस रनटाइम शुरू हो रहा है",
    nextCheckLabel: "अगली जांच",
    coldStartEstimateTitle: "कोल्ड स्टार्ट अनुमान",
    coldStartEstimateLabel: "{n} से {n2} मिनट",
    checkCompleteNote: "जांच {n} पूरी हुई। यह पेज अपने आप फिर कोशिश करता है।",
    keepWorkingNote: "यह शुरू होने के दौरान आप इस स्टेप पर काम जारी रख सकते हैं। अगर यह टैब फिर लोड हो, तो आपकी लाइन और इंतज़ार बना रहता है।",
    stateGenerating: "बन रहा है",
    makingYourTake: "आपकी टेक बनाई जा रही है",
    renderingTest: "मौजूदा ड्राफ्ट आवाज़ में आपके शब्द बनाए जा रहे हैं।",
    renderingReal: "आपके शब्द बनाए जा रहे हैं, डिस्क्लोज़र और वॉटरमार्क जोड़े जा रहे हैं।",
    stateFailed: "नहीं हो सका",
    previewStopped: "प्रिव्यू रुक गया",
    tryAgain: "फिर कोशिश करें",
    stateIdle: "अभी तक कुछ नहीं बना",
    takeAppearsHere: "आपकी टेक यहां दिखेगी",
    chooseLanguageNote: "भाषा चुनें, एक सहज लाइन लिखें, और मौजूदा ड्राफ्ट बनाएं।",
    firstWaitNote: "ख़ामोशी के बाद पहला रन शुरू होने में 2 से 5 मिनट लग सकते हैं। उसके बाद, जब तक रनटाइम गर्म रहता है, यह आमतौर पर बहुत तेज़ होता है।",
    runtimeNotWokenHeadline: "वॉइस रनटाइम पूरी तरह जग नहीं पाया",
    ownerReportTooManyTimes: "इसे {n} बार, क़रीब {n2} सेकंड में मांगा जा चुका है और अभी भी शुरू हो रहा है। कुछ मिनट में फिर कोशिश करें, या सपोर्ट को बताएं कि रनटाइम नहीं आ रहा।",
  },

  voiceExperimentPanel: {
    kindPack: "पैक",
    kindRatings: "रेटिंग",
    kindResult: "नतीजा",
    errorCleanupFailed: "नया पैक लोड नहीं हुआ क्योंकि ब्राउज़र स्टोरेज पुराने निजी एक्सपेरिमेंट को पूरी तरह हटा नहीं सका। मौजूदा एक्सपेरिमेंट अभी भी खुला है।",
    errorMappingLeak: "यह फ़ाइल फ़ैसले लॉक होने से पहले ही एक उम्मीदवार बता देती है, इसलिए इसे मना कर दिया गया।",
    errorBindingMismatch: "यह {kind} फ़ाइल किसी और सील किए एक्सपेरिमेंट की है।",
    errorSizeLimit: "यह {kind} फ़ाइल तय सुरक्षित साइज़ सीमा से बाहर है।",
    errorIntegrityCheck: "एक ऑडियो फ़ाइल की इंटीग्रिटी जांच नहीं हो सकी। सील पैक फिर से एक्सपोर्ट करें।",
    errorNoSignature: "इस रिपोर्ट में कोई मान्य निजी-पैक सिग्नेचर नहीं है, इसलिए उम्मीदवारों की पहचान छुपी रहती है।",
    errorNotValidExport: "यह {kind} फ़ाइल Vyakti के आवाज़ एक्सपेरिमेंट का मान्य एक्सपोर्ट नहीं है।",
    errorAudioCouldNotStart: "ऑडियो शुरू नहीं हो सका। इस ब्राउज़र की साउंड परमिशन जांचें, फिर फिर कोशिश करें।",
    errorStorageFailedRemoving: "यह निजी एक्सपेरिमेंट हटाते समय ब्राउज़र स्टोरेज में गड़बड़ी हुई। मौजूदा एक्सपेरिमेंट अभी भी खुला है। इस डिवाइस से जाने से पहले फिर कोशिश करें।",
    removeConfirm: "इस ब्राउज़र से यह निजी एक्सपेरिमेंट हटाएं? आपके कंप्यूटर पर एक्सपोर्ट की गई फ़ाइलें नहीं हटतीं।",
    summaryTitle: "ब्लाइंड आवाज़ एक्सपेरिमेंट",
    summarySubtitle: "यह देखने से पहले कि किस उम्मीदवार ने कौन-सा आउटपुट बनाया, असली आउटपुट की तुलना करें।",
    statusIdentitiesUnlocked: "पहचान अनलॉक हुई",
    statusRatingsLocked: "रेटिंग लॉक हुई",
    statusReadyToLock: "लॉक करने के लिए तैयार",
    statusRatedCount: "{n2} में से {n} रेट हुए",
    statusNoExperiment: "कोई एक्सपेरिमेंट लोड नहीं है",
    dismiss: "हटाएं",
    openSealedPackTitle: "एक सील किया सुनने का पैक खोलें",
    openSealedPackBody: "एक-फ़ाइल स्टूडियो बंडल इम्पोर्ट करें। इसमें छुपे हुए क्लिप और स्कोर कंट्रोल हैं, कभी उम्मीदवारों के नाम या निजी उत्तर-कुंजी नहीं।",
    checkingPack: "पैक जांचा जा रहा है...",
    chooseSealedPack: "सील किया पैक चुनें",
    identitiesUnlockedTitle: "एक्सपेरिमेंट की पहचान अनलॉक हुई",
    acceptedListenerNote: "{n} मंज़ूर सुनने वाली शीट। ये बताने वाले औसत हैं, अपने-आप कोई जीत तय करने वाले नहीं।",
    signatureVerified: "सिग्नेचर जांचा गया",
    languageHindi: "हिन्दी",
    languageEnglish: "अंग्रेज़ी",
    meanLabel: "औसत",
    noMean: "कोई औसत नहीं",
    noneLabel: "कोई नहीं",
    noPromotionNote: "यहां किसी उम्मीदवार को आगे नहीं बढ़ाया जाता। इन रेटिंग को उच्चारण जांच, आवाज़ की समानता, लेटेंसी और लागत के साथ एक सबूत की तरह इस्तेमाल करें।",
    learnOwnerVoiceTitle: "पहले, मालिक की असली आवाज़ सीखें",
    headphonesNote: "हेडफ़ोन इस्तेमाल करें और एक ही वॉल्यूम रखें। उम्मीदवारों की पहचान इस ब्राउज़र पैक से बाहर रहती है।",
    playOwnerAgain: "मालिक को फिर सुनें",
    playRealOwner: "असली मालिक सुनें",
    startBlindRating: "ब्लाइंड रेटिंग शुरू करें",
    ratingsLockedTitle: "इस ब्राउज़र पर रेटिंग लॉक हैं",
    ratingsLockedBody: "उम्मीदवार की मैपिंग अभी भी सील है। यह शीट एक्सपोर्ट करें, निजी सुनने वाले गेट से भेजें, फिर अनसील की गई रिपोर्ट इम्पोर्ट करें।",
    savedLocally: "इसी जगह सेव है",
    exportBeforeLeaving: "जाने से पहले एक्सपोर्ट करें",
    exportLockedRatings: "लॉक रेटिंग एक्सपोर्ट करें",
    importUnsealedReport: "अनसील की गई रिपोर्ट इम्पोर्ट करें",
    privateGateCommandsSummary: "निजी गेट के कमांड",
    privateGateCommandsNote: "फिर ऊपर reports/unsealed-report.json इम्पोर्ट करें। सुनने की नाकाम जांच पहचान अनलॉक नहीं करती।",
    progressBarAriaLabel: "ब्लाइंड एक्सपेरिमेंट की प्रगति",
    progressAriaValueText: "{n2} में से {n} रेटिंग पूरी",
    listeningCheck: "सुनने की जांच",
    positionLabel: "{n2} में से {n}",
    playHiddenClipAgain: "छुपा क्लिप फिर सुनें",
    playHiddenClip: "छुपा क्लिप सुनें",
    clipHeard: "क्लिप सुन लिया",
    playBeforeRating: "रेटिंग से पहले सुनें",
    axisScaleLabel: "1 {n} · 5 {n2}",
    axisButtonAriaLabel: "{label}: 5 में से {n}",
    disclosureLegend: "क्या बोला गया AI डिस्क्लोज़र साफ़ और पूरा था?",
    noteQuestion: "अगर कुछ ग़लत लगा, तो क्या?",
    playCheckAgain: "जांच फिर सुनें",
    playCheck: "जांच सुनें",
    attentionPrompt: "छोटी जांच सुनें, फिर बताएं आपने क्या सुना।",
    back: "पीछे",
    savingPack: "पैक सेव हो रहा है...",
    progressSavedLocally: "प्रगति इसी जगह सेव है",
    exportProgressBeforeLeaving: "जाने से पहले प्रगति एक्सपोर्ट करें",
    lockRatings: "रेटिंग लॉक करें",
    saveAndContinue: "सेव करें और आगे बढ़ें",
    lockIrreversibleNote: "स्टूडियो में लॉक करना वापस नहीं हो सकता। एक्सपोर्ट बाद में भी उपलब्ध रहता है।",
    exportProgress: "प्रगति एक्सपोर्ट करें",
    importProgress: "प्रगति इम्पोर्ट करें",
    replaceClearsNote: "बदलने से यह पैक, इसकी लोकल रेटिंग, और इस ब्राउज़र से इम्पोर्ट किया कोई भी नतीजा मिट जाता है।",
    working: "काम चल रहा है...",
    replacePack: "पैक बदलें",
    removePrivateExperiment: "निजी एक्सपेरिमेंट हटाएं",
  },

  shareKit: {
    title: "शेयर किट",
    intro: "आप जहां पहले से पोस्ट करते हैं, वहां के लिए सही टेक्स्ट और तस्वीर। एक कॉपी करें, या WhatsApp खोलें, संदेश तैयार मिलेगा।",
    loading: "आपकी शेयर किट लोड हो रही है...",
    whatsappLabel: "WhatsApp",
    instagramLabel: "Instagram बायो",
    youtubeLabel: "YouTube विवरण",
    telegramLabel: "Telegram चैनल पोस्ट",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया",
    openWhatsapp: "WhatsApp खोलें",
    viewPicture: "तस्वीर",
    notPublishedYet: "अपनी शेयर किट पाने के लिए अपना Room प्रकाशित करें।",
    whatsappTemplate:
      "मैंने {name} AI शुरू किया है, जिससे आप {name} से जुड़े कभी भी सवाल पूछ सकते हैं। यह साफ बताता है कि यह एक AI है, {name} नहीं, और आपकी बात किसी और को नहीं बताई जाती। यहां बात करें: {url}",
    instagramTemplate: "{name} AI, कभी भी बात करें: {url}",
    youtubeTemplate:
      "{name} AI अब यहां है।\n\nमैंने अपनी एक AI बनाई है ताकि आप कभी भी सवाल पूछ सकें, भले ही मैं उपलब्ध न होऊं। यह साफ बताता है कि यह एक AI है, {name} नहीं, और आपकी बात किसी और को नहीं बताई जाती।\n\nयहां बात करें: {url}",
    telegramTemplate:
      "{name} AI अब लाइव है। यहां कभी भी कुछ भी पूछें: {url}\n\nयह {name} की अपनी सामग्री से बनी एक AI है, खुद {name} नहीं, और यह आपकी बात किसी और को नहीं बताती।",
  },
};
