// src/studio/hiCopy.ts — WS-R159. The personal studio's Hindi table, its own
// chunk (loaded only by `copy.ts#loadStudioCopy("hi")`), the same shape
// `src/creatorStudio/hiCopy.ts` and `src/studio/hiPersonalAuthCopy.ts`
// already establish. `personModelStudio` below reuses
// `src/creatorStudio/hiCopy.ts#personModelStudio` (WS-R61)'s own
// already-reviewed wording wherever this file's English matches it, adapting
// only where this screen's own English differs (the nearline nearline-busy
// states this file's English adds, and one extra extraction blocker key).
import type { CloneExperienceShellCopy, CloneVerificationJourneyCopy, ContextLockerPanelCopy, ExpertConversationCopy, ExpertSharePanelCopy, FirstFiveMinutesCopy, MeetMemoryCopy, MirrorCallStudioCopy, PersonModelStudioCopy, QuickVoiceCaptureCopy, SourcesStudioCopy, StudioCopy, VoicePreviewPanelCopy } from "./copy";

const HI_EXPERT_SHARE_PANEL: ExpertSharePanelCopy = {
  title: "अपने AI को एक ठिकाना दें।",
  voiceOtherChannelsSummary: "आवाज़ और अन्य चैनल",
  voiceOtherChannelsNote: "शेयर करने से पहले इनकी अपनी अलग पुष्टि ज़रूरी है।",
  reviewReadiness: "तैयारी की समीक्षा करें",
};

const HI_QUICK_VOICE_CAPTURE: QuickVoiceCaptureCopy = {
  recommendedEyebrow: "सुझाया गया",
  heading: "एक साफ़ आवाज़ का नमूना रिकॉर्ड करें",
  instructionsOne: "किसी भी विषय पर सहज होकर बोलें। 12 सेकंड के बाद, एक टैप रिकॉर्डिंग खत्म करता है और आपका AI शुरू करता है।",
  instructionsTwo: "करीब 30 सेकंड में साफ़ बोली के ज़्यादा हिस्से चुनने का मौका मिलता है। हम इसे निजी रखते हैं।",
  localUntilUpload: "अपलोड करने तक सिर्फ़ आपके डिवाइस पर",
  languageGroupAriaLabel: "रिकॉर्डिंग की भाषा",
  promptSummary: "कोई विचार चाहिए? एक वैकल्पिक सुझाव देखें",
  promptHint: "यह पढ़ना ज़रूरी नहीं है। आपके अपने सहज शब्द बेहतर हैं।",
  startRecording: "रिकॉर्डिंग शुरू करें",
  micPermissionNote: "आपका ब्राउज़र माइक्रोफ़ोन की अनुमति इसी क्लिक के बाद मांगेगा।",
  openingMic: "आपका माइक्रोफ़ोन खोला जा रहा है",
  checkPermissionPrompt: "ब्राउज़र की अनुमति वाला संदेश देखें।",
  recordingVisuallyHidden: "रिकॉर्डिंग शुरू हो गई है। 12 सेकंड बाद खत्म करना और बनाना उपलब्ध होगा।",
  recordingLabel: "रिकॉर्डिंग हो रही है",
  ofMaxTemplate: "{time}, अधिकतम 1:00 में से",
  speakMoreTemplate: "{n} सेकंड और बोलें",
  finishAndBuild: "खत्म करें और बनाएं",
  meterAriaLabel: "माइक्रोफ़ोन का लाइव इनपुट स्तर",
  keepSpeakingTemplate: "{n} सेकंड और बोलते रहें",
  goodKeepGoing: "अच्छा है। बेहतर विकल्प के लिए जारी रखें।",
  targetReached: "लक्ष्य पूरा हुआ। जब यह वाक्य पूरा लगे, तब रुक जाएं।",
  progressAriaLabel: "सुझाई गई रिकॉर्डिंग लंबाई",
  improveSampleHeading: "चलिए इस नमूने को बेहतर बनाते हैं",
  durationFormatTemplate: "{duration} · 24 kHz निजी WAV",
  retakeNeeded: "फिर से रिकॉर्ड करना ज़रूरी",
  levelTooHigh: "आवाज़ का स्तर ज़्यादा हो सकता है। माइक्रोफ़ोन से थोड़ा दूर होकर फिर से रिकॉर्ड करें।",
  quietRecording: "इस रिकॉर्डिंग का ज़्यादातर हिस्सा धीमा है। माइक्रोफ़ोन के पास होकर फिर से रिकॉर्ड करें।",
  usableLevel: "स्थानीय इनपुट स्तर काम लायक लगता है। अंतिम चुनाव निजी प्रोसेसिंग करती है।",
  notEnoughYet: "कम से कम 12 सेकंड बोलें। करीब 30 सेकंड में प्रोसेसिंग को साफ़ बोली के ज़्यादा हिस्से चुनने का मौका मिलता है।",
  recordAgain: "फिर से रिकॉर्ड करें",
  errorTooShort: "यह नमूना बहुत छोटा है। कम से कम 12 सेकंड बोलें।",
  errorClipped: "माइक्रोफ़ोन का स्तर सीमा पार कर गया। थोड़ा दूर होकर एक बार फिर रिकॉर्ड करें।",
  errorTooQuiet: "इस नमूने का ज़्यादातर हिस्सा धीमा है। पास आकर एक बार फिर रिकॉर्ड करें।",
  errorFinishFailed: "रिकॉर्डिंग खत्म नहीं हो सकी।",
  errorStartFailed: "ब्राउज़र रिकॉर्डिंग शुरू नहीं कर सका।",
  errorCloseMicFailed: "माइक्रोफ़ोन बंद नहीं हो सका।",
};

const HI_EXPERT_CONVERSATION: ExpertConversationCopy = {
  ariaLabel: "निजी विशेषज्ञ बातचीत",
  statusActive: "निजी बातचीत",
  statusInactive: "निजी वर्कस्पेस",
  aiReviewedByYou: "AI, आपके द्वारा समीक्षित",
  continuityAudioNote: "पुरानी बातचीत वाले जवाबों में ऑडियो उपलब्ध नहीं है।",
  readinessTitle: {
    stopped: "यह AI रुका हुआ है",
    reconciling: "जवाब सेव हो गया",
    checking: "आपका AI जांचा जा रहा है",
    privateUnavailable: "आपका निजी वर्शन उपलब्ध नहीं है",
    unavailable: "तैयारी की जानकारी उपलब्ध नहीं है",
    setup: "अपनी पहली बातचीत शुरू करें",
  },
  readinessBody: {
    stopped: "इस AI के लिए निजी जवाब उपलब्ध नहीं हैं।",
    reconciling: "अगला जवाब शुरू होने से पहले हम इस्तेमाल की जांच कर रहे हैं।",
    checking: "मौजूदा सर्वर स्थिति जांची जा रही है।",
    privateUnavailable: "हम चुना गया निजी वर्शन लोड नहीं कर सके। इसे ठीक करते समय फिर से जांचें।",
    unavailable: "हम बातचीत की तैयारी जांच नहीं सके। फिर कोशिश करें।",
    setup: "निजी जवाब शुरू होने से पहले जो ज़रूरी है, वह जांचें।",
  },
  openConversationSetup: "बातचीत की सेटअप खोलें",
  checkAgain: "फिर जांचें",
  newConversation: "नई बातचीत",
  retryOpeningConversation: "बातचीत खोलने की फिर कोशिश करें",
  openingConversation: "बातचीत खुल रही है",
  checkConversation: "बातचीत जांचें",
  recentCompletedReplies: "हाल के पूरे हुए जवाब",
  runtimeChangedNotice: "आपका निजी वर्शन बदल गया है। पिछला जवाब जांचने के बाद नई बातचीत शुरू करें।",
  historyPendingNotice: "हम पिछले जवाब और उसके इस्तेमाल की जांच कर रहे हैं। फिर भेजने से पहले बातचीत जांचें।",
  historyUnconfirmedNotice: "पिछले जवाब की पुष्टि नहीं हो सकी। इस बातचीत को जांचें, या साफ़ तौर पर एक नई बातचीत शुरू करें। हमने आपका संदेश दोबारा नहीं भेजा है।",
  emptyHeading: "एक असली सवाल आज़माएं।",
  emptyBody: "वह पूछें जो कोई क्लाइंट आपसे पूछता। सुनें, फिर अपने AI को दिखाएं कि आप क्या बदलेंगे।",
  emptyStarterButton: "किसी की शुरुआत में मदद करें",
  emptyStarterQuestion: "मेरे काम में नए किसी व्यक्ति को आप सबसे पहला कदम क्या सुझाएंगे?",
  youLabel: "आप",
  yourAiLabel: "आपका AI",
  stopAudio: "ऑडियो रोकें",
  listen: "सुनें",
  teachCorrection: "सुधार सिखाएं",
  workingStatus: "आपका AI जवाब तैयार कर रहा है",
  recallPreviousLabel: "पहले की निजी बातचीत इस्तेमाल करें",
  askYourAi: "अपने AI से पूछें",
  questionPlaceholder: "अपने काम से जुड़ा एक सवाल लाएं",
  privateToThisRelationship: "इस रिश्ते तक सीमित निजी",
  answering: "जवाब दिया जा रहा है",
  send: "भेजें",
  errorRecovered: "आपका सेव किया गया जवाब वापस मिल गया है।",
  errorConversationUnavailable: "पिछली बातचीत उपलब्ध नहीं है। आप साफ़ तौर पर एक नई बातचीत शुरू कर सकते हैं।",
  errorRestoreFailed: "हम इस बातचीत को वापस नहीं ला सके। अगला संदेश भेजने से पहले फिर जांचें।",
  errorOpenFailed: "बातचीत खोलने की पुष्टि नहीं हो सकी। वही बातचीत जांचने के लिए फिर कोशिश करें।",
  errorReplyFailed: "आपका AI यह जवाब पूरा नहीं कर सका। आपका संदेश अभी भी यहां है। हमने इसे अपने आप फिर से नहीं भेजा है।",
  errorReplySavedNeedsReconcile: "आपका जवाब सेव हो गया है। अगले जवाब से पहले हमें इसका इस्तेमाल तय करना होगा।",
  errorAudioPlaybackFailed: "यह ऑडियो नहीं चल सका। फिर सुनने की कोशिश करें।",
  errorVoiceUnavailable: "आवाज़ में सुनना उपलब्ध नहीं है। लिखा हुआ जवाब अभी भी यहां है।",
  // WS-R161 (wave twenty-two).
  apprenticeVoiceNotice: "अब आप बात कर सकते हैं। आवाज़ अभी बन रही है।",
};

const HI_PERSON_MODEL_STUDIO: PersonModelStudioCopy = {
  blockers: {
    self_name_required: "वह नाम पुष्ट करें जो आपका AI खुद के लिए इस्तेमाल करता है",
    language_identity_required: "इसकी भाषा और कोड-स्विचिंग पहचान पुष्ट करें",
    behavior_evidence_required: "कम से कम एक व्यवहार या सुधार पैटर्न देखें",
    boundary_evidence_required: "कम से कम एक निजी सीमा पुष्ट करें",
    critical_identity_conflict: "टकराते हुए पहचान दावे सुलझाएं",
  },
  extractionBlockers: {
    transcription_consent_required: "ट्रांसक्रिप्शन की अनुमति दें",
    training_consent_required: "सहायता प्राप्त दावा निष्कर्षण के लिए AI-निर्माण अनुमति दें",
    reviewed_subject_transcript_required: "कम से कम एक सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें",
    reviewed_confident_subject_transcript_required: "कम से कम एक भरोसेमंद, सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें",
    reviewed_confident_subject_evidence_required: "एक भरोसेमंद सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें, या अपलोड किए गए दस्तावेज़ को अपना लिखा हुआ बताएं",
  },
  confidencePctTemplate: "{n}% विश्वास",
  fromYourSource: "आपके सोर्स से:",
  citedSourceOne: "{n} उद्धृत सोर्स",
  citedSourceMany: "{n} उद्धृत सोर्स",
  keepOut: "बाहर रखें",
  notAccurate: "सही नहीं है",
  outdated: "पुराना",
  thisIsMe: "यह मैं हूं",
  reviewClaimAriaLabel: "इस दावे की समीक्षा करें",
  eyebrow: "हमने आपके बारे में क्या सीखा",
  title: "हमें जो लगता है हमने आपके बारे में सीखा, एक-एक दावे के रूप में",
  intro: "पहचान, भाषा, व्यवहार, मूल्य, सीमाएं, और आत्मकथा को अलग-अलग सबूत-आधारित दावों के रूप में पुष्ट करें। टकराव छिपाए नहीं जाते, एक भरोसेमंद कल्पना में औसत नहीं किए जाते।",
  noApprovedVersion: "अभी मंज़ूर नहीं",
  approvedVersionLabel: "मंज़ूर वर्शन",
  loadingClaims: "समीक्षा किए गए दावे लोड हो रहे हैं…",
  retry: "फिर कोशिश करें",
  proposedClaims: "प्रस्तावित दावे",
  accepted: "स्वीकृत",
  criticalConflicts: "गंभीर टकराव",
  citedExtractionEyebrow: "उद्धृत निष्कर्षण",
  citedExtractionTitle: "अपनी समीक्षा की गई रिकॉर्डिंग को अपने नियंत्रण वाले दावों में बदलें",
  citedExtractionIntro: "सिर्फ़ स्वीकृत लक्षित-स्पीकर ट्रांसक्रिप्ट हिस्से ही योग्य हैं। कच्चे ट्रांसक्रिप्ट सिर्फ़ सर्वर पर रहते हैं, सीधी पहचान निष्कर्षण कॉल से पहले छिपाई जाती है, और हर नतीजा तब तक सिर्फ़ एक प्रस्ताव रहता है जब तक आप उसे नीचे न देख लें।",
  eligibleSpans: "योग्य हिस्से",
  lastProposed: "पिछली बार प्रस्तावित",
  noExtractionRunYet: "अभी कोई निष्कर्षण नहीं हुआ",
  observedRangeLabel: "देखी गई सीमा",
  nextCheckLabel: "अगली जांच",
  leaveOrReturnLabel: "छोड़ें या लौटें",
  checkStatusNow: "अभी स्थिति जांचें",
  submittingExtraction: "निष्कर्षण भेजा जा रहा है...",
  extractionRunning: "निष्कर्षण चल रहा है",
  waitingToRetry: "फिर कोशिश का इंतज़ार",
  extractionQueued: "निष्कर्षण कतार में है",
  extractNewEvidence: "नया सबूत निकालें",
  extractCitedClaims: "उद्धृत दावे निकालें",
  noClaimsHeadline: "अभी कोई व्यवहार या याददाश्त वाला दावा नहीं है।",
  noClaimsNote: "प्रोसेस किया गया सबूत यहां समीक्षा के लिए दिखेगा। कच्चे ट्रांसक्रिप्ट, वेक्टर, और स्टोरेज पाथ रोके रहते हैं।",
  buildIsDeterministicNote: "एक बिल्ड निश्चित और वर्शन वाला होता है। इसे मंज़ूर करना कभी इन्फ़रेंस या आवाज़ बनाने की अनुमति नहीं देता।",
  checkingEvidence: "सबूत जांचा जा रहा है…",
  approveProfileVersionTemplate: "प्रोफ़ाइल v{n} मंज़ूर करें",
  building: "बनाया जा रहा है…",
  buildReviewDraft: "समीक्षा ड्राफ्ट बनाएं",
  errorLoadFailed: "हमने आपके बारे में जो सीखा वह लोड नहीं हो सका",
  errorExtractionUnavailable: "उद्धृत निष्कर्षण की स्थिति लोड नहीं हो सकी",
  errorProfileUnavailable: "हमने आपके बारे में जो सीखा उसकी पुष्टि नहीं हो सकी। फिर कोशिश करें।",
  errorClaimNotSaved: "दावे की समीक्षा सेव नहीं हुई",
  errorBuildRefused: "हमने आपके बारे में जो सीखा उसे बनाना अस्वीकार हुआ",
  errorApproveChanged: "प्रोफ़ाइल बदल गई और मंज़ूर नहीं हो सकी",
  errorExtractionFailed: "उद्धृत दावे नहीं निकाले जा सके",
  errorExtractionScopeChanged: "निष्कर्षण का दायरा बदल गया",
  errorExtractionCheckFailed: "निष्कर्षण की स्थिति की पुष्टि नहीं हो सकी। फिर कोशिश करें।",
  errorExtractionCheckFailedRetryable: "नवीनतम स्थायी निष्कर्षण स्थिति जांची नहीं जा सकी। सर्वर पर काम अभी भी जारी हो सकता है; यह पेज दोबारा जुड़ने या रीलोड होने के बाद फिर कोशिश करेगा।",
};

// WS-R167 (own closed block, appended). "It remembers" — see
// src/studio/copy.ts's MeetMemoryCopy for the full rationale.
const HI_MEET_MEMORY: MeetMemoryCopy = {
  heading: "यह याद रखता है",
  onDescription: "आपका AI यहां जो कहते हैं उसे याद रखता है, ताकि जांचना हर बार नए सिरे से शुरू करने के बजाय एक चलती हुई बातचीत जैसा लगे।",
  offDescription: "याददाश्त बंद है। हर बातचीत नए सिरे से शुरू होती है, और यहां जो कहा जाता है वह बाद में नहीं रखा जाता।",
  toggleOn: "याददाश्त चालू करें",
  toggleOff: "याददाश्त बंद करें",
  factsHeading: "यह क्या याद रखता है",
  factsEmpty: "अभी कुछ याद नहीं है।",
  correctAction: "इसे सुधारें",
  forgetAction: "इसे भुलाएं",
  correctPromptLabel: "इसे बदले में क्या याद रखना चाहिए?",
  correctPlaceholder: "इसे ठीक वैसे कहें जैसे आप चाहते हैं कि यह याद रहे",
  correctSave: "सुधार सेव करें",
  correctCancel: "रद्द करें",
  classificationUnconfirmed: "अभी वर्गीकृत नहीं",
  howWeAreHeading: "हम कैसे हैं",
  startFreshAction: "नए सिरे से शुरू करें",
  startFreshConfirm: "यह आपके और आपके AI के बीच अभी जो भी खुला है उसे बंद करता है, जो हुआ उसे मिटाए बिना।",
  startFreshNothingOpen: "अभी कुछ भी खुला नहीं है।",
  startFreshDone: "नए सिरे से शुरू हो गया।",
  errorStatusUnavailable: "हम जांच नहीं सके कि याददाश्त चालू है या नहीं।",
  errorToggleFailed: "यह सेव नहीं हो सका। फिर कोशिश करें।",
  errorFactsUnavailable: "यह क्या याद रखता है, लोड नहीं हो सका।",
  errorCorrectFailed: "वह सुधार सेव नहीं हुआ।",
  errorForgetFailed: "अभी वह भुलाया नहीं जा सका।",
};

// WS-R166. `cloneVerificationJourney` translates CloneVerificationJourney.tsx
// (`copy.ts`'s own header on this section explains the EN/HI split: English
// values are pre-existing, verbatim-frozen strings several sibling suites
// assert on; this Hindi table is new translation). Law 5 of this brief
// ("never a clone... in a string") is honored here: every occurrence renders
// as AI, never क्लोन.
const HI_CLONE_VERIFICATION_JOURNEY: CloneVerificationJourneyCopy = {
  verificationStepTemplate: "सत्यापन चरण {n}, कुल 5 में से",
  verificationPaused: "सत्यापन रुका हुआ है",
  leaveVerification: "सत्यापन छोड़ें",
  makeYoursTemplate: "{name} को अपना बनाएं",
  privateVerification: "निजी सत्यापन",
  legacyReset: {
    erasureFailedError: "मिटाना शुरू नहीं हो सका। यह टेस्ट AI अभी भी रुका हुआ है। फिर कोशिश करें।",
    title: "यह टेस्ट AI आगे नहीं बढ़ सकता।",
    body: "इस ड्राफ्ट को बनाने के लिए एक पुरानी आंतरिक टेस्ट अनुमति इस्तेमाल हुई थी। यह असली सत्यापन से आगे नहीं बढ़ सकता। इस टेस्ट AI को मिटाएं और साफ़ रिकॉर्ड के साथ फिर से शुरू करें।",
    startClean: "साफ़ शुरुआत करें",
    confirmAriaLabel: "टेस्ट AI मिटाने की पुष्टि करें",
    confirmBody: "यह अभी AI को रोक देता है और इसकी रिकॉर्डिंग तथा उससे बने डेटा का सत्यापित मिटाना शुरू करता है। नया AI इस ड्राफ्ट या इसकी अनुमतियां नहीं अपनाएगा।",
    startingErasure: "मिटाना शुरू हो रहा है",
    eraseAndStartAgain: "मिटाएं और फिर से शुरू करें",
    cancel: "रद्द करें",
  },
  identity: {
    fileEmpty: "यह फ़ाइल खाली है।",
    fileTooLarge: "यह दस्तावेज़ 50 MB से बड़ा है।",
    chooseFileType: "JPEG, PNG, या PDF चुनें।",
    uploadAuthMissing: "निजी अपलोड की अनुमति मौजूद नहीं है।",
    uploadStopped: "सत्यापन से पहले निजी अपलोड रुक गया।",
    removeFailed: "अधूरा अपलोड हटाया नहीं जा सका।",
    securingTitle: "आपका दस्तावेज़ सुरक्षित किया जा रहा है।",
    uploadNotFinished: "निजी अपलोड अभी पूरा नहीं हुआ है।",
    checkingStoredFile: "Vyakti सेव की गई फ़ाइल जांच रहा है। इस पेज को एक और कॉपी की ज़रूरत नहीं है।",
    checkAgain: "फिर जांचें",
    removing: "हटाया जा रहा है",
    removeUnfinished: "अधूरा अपलोड हटाएं",
    addTitle: "एक निजी पहचान पत्र जोड़ें।",
    addBody: "एक JPEG, PNG, या PDF आपकी उम्र और पहचान की पुष्टि करता है। एक अलग लाइव जांच आपको रिकॉर्डिंग से जोड़ती है। इस फ़ाइल का इस्तेमाल कभी AI को सिखाने के लिए नहीं किया जाता।",
    rejected: "पिछला दस्तावेज़ स्वीकार नहीं हुआ। एक नई फ़ाइल चुनें।",
    deleting: "पुराना दस्तावेज़ मिटाया जा रहा है। एक और जोड़ने से पहले फिर जांचें।",
    typeSelectedTemplate: "{type} चुना गया",
    pdfLabel: "PDF",
    imageLabel: "तस्वीर",
    chooseId: "अपनी पहचान चुनें",
    sizeOnDeviceTemplate: "{size} इस डिवाइस पर",
    fileTypesHint: "JPEG, PNG, या PDF, 50 MB तक",
    declaration: "इस मौजूदा सरकारी पहचान पत्र में सिर्फ़ मैं हूं।",
    statusChecking: "फ़ाइल जांची जा रही है",
    statusAuthorizing: "निजी स्टोरेज खोली जा रही है",
    statusUploading: "निजी तौर पर अपलोड हो रहा है",
    statusVerifying: "सेव की गई कॉपी की पुष्टि हो रही है",
    keepPageOpen: "कृपया यह पेज खुला रखें",
    uploadProgressAriaLabel: "निजी दस्तावेज़ अपलोड प्रगति",
    documentSecured: "दस्तावेज़ सुरक्षित हो गया। पहचान जांच खुल रही है।",
    securingDocument: "दस्तावेज़ सुरक्षित किया जा रहा है",
    retryUpload: "निजी अपलोड फिर आज़माएं",
    uploadPrivately: "निजी तौर पर अपलोड करें",
    retryWithoutChoosing: "फ़ाइल दोबारा चुने बिना फिर आज़माएं",
    privacyNote: "अपलोड दबाने के बाद फ़ाइल सीधे निजी स्टोरेज में जाती है।",
  },
  deferred: {
    identityProof: "निजी पहचान जांच खुल रही है",
    liveness: "लाइव पहचान जांच खुल रही है",
    modelConsent: "AI अनुमति खुल रही है",
    review: "सबूत की समीक्षा खुल रही है",
    stepsSaved: "यह स्क्रीन खुलने तक आपके पूरे किए गए चरण सेव रहते हैं।",
  },
  main: {
    ariaLabel: "AI सत्यापन",
    stopped: { title: "यह AI अब सक्रिय नहीं है।", body: "सत्यापित मिटाना पूरा होने तक बनाना रुका हुआ है।" },
    sourcePermission: { title: "अनुमति पर ध्यान देना ज़रूरी है।", body: "आपकी रिकॉर्डिंग निजी रहती है। कैप्चर, ट्रांसक्रिप्शन और स्टोरेज अनुमति सक्रिय होने तक बनाना रुका हुआ है।", label: "अनुमति देखें" },
    primarySource: { title: "पहले अपनी आवाज़ पूरी करें।", body: "पहचान सत्यापन शुरू होने से पहले एक तैयार मुख्य रिकॉर्डिंग ज़रूरी है।", label: "आवाज़ पर लौटें" },
    sourceProcessing: {
      title: "आपकी रिकॉर्डिंग तैयार हो रही है।",
      body: "निजी वर्कर आपके चुने गए सोर्स की जांच कर रहा है। हाल की रिकॉर्डिंग को वर्कर शुरू होने के बाद करीब 5 से 15 मिनट लगे; लंबी फ़ाइलों में ज़्यादा समय लग सकता है।",
      autoCheckLabel: "अपने आप जांच",
      autoCheckValue: "जब तक यह पेज खुला है, हर 10 सेकंड में",
      returnLabel: "आप लौट सकते हैं",
      returnValue: "यह सर्वर पर जारी रहता है",
      checkNow: "अभी जांचें",
    },
    comparisonSummary: "एक तैयार तुलना रिकॉर्डिंग देखें",
    openingComparisonReview: "निजी तुलना समीक्षा खुल रही है",
    review: {
      failedStrong: "हम आपकी आवाज़ बनाना पूरा नहीं कर सके।",
      failedSpan: "नीचे नतीजे देखें। अगर यह ही अस्वीकार हुआ हो तभी नई रिकॉर्डिंग चाहिए।",
      loading: "आपकी रिकॉर्डिंग की जांच लोड हो रही है।",
    },
    building: {
      title: "आपकी निजी आवाज़ बनाई जा रही है।",
      body: "आपकी आवाज़ आपकी समीक्षा की गई रिकॉर्डिंग से बन रही है। यह पेज खुला रहते हुए हर 10 सेकंड में प्रगति जांचता है। आप जा सकते हैं और लौट सकते हैं।",
      currentStateLabel: "मौजूदा स्थिति",
      stateRetry: "अपने आप फिर कोशिश का इंतज़ार",
      stateLeased: "बनाने की तैयारी हो रही है",
      stateBuilding: "ड्राफ्ट बनाया जा रहा है",
      stateQueued: "कतार में",
      completionLabel: "पूरा होना",
      completionValue: "अभी अनुमान उपलब्ध नहीं है",
      checkNow: "अभी जांचें",
    },
    complete: { title: "आपकी ड्राफ्ट आवाज़ तैयार है।", body: "यह ड्राफ्ट आपकी समीक्षा की गई रिकॉर्डिंग का इस्तेमाल करता है। मंज़ूर करने या शेयर करने से पहले सुनें।", label: "अपने AI से मिलें" },
  },
};

const HI_CONTEXT_LOCKER_PANEL: ContextLockerPanelCopy = {
  reasons: {
    pdf_no_text_layer: "यह PDF एक स्कैन है। इसमें पढ़ने लायक कोई टेक्स्ट नहीं है, सिर्फ़ टेक्स्ट की तस्वीरें हैं। हमारे पास OCR नहीं है, इसलिए हम इसे खाली सेव करने के बजाय यही बता देना बेहतर समझते हैं।",
    pdf_text_layer_unreadable: "हमें इस PDF में टेक्स्ट मिला पर यह भाषा जैसा नहीं पढ़ता। फ़ॉन्ट एक ऐसी एन्कोडिंग इस्तेमाल करते हैं जिसे हम मैप नहीं कर सकते। इसके बजाय इसे टेक्स्ट या DOCX के रूप में एक्सपोर्ट करें।",
    pdf_encrypted: "यह PDF पासवर्ड-सुरक्षित है। पासवर्ड हटाकर फिर कोशिश करें।",
    pdf_unsupported_filter: "यह PDF अपने टेक्स्ट को एक ऐसे तरीके से कंप्रेस करता है जिसे हम नहीं पढ़ते।",
    pdf_malformed: "यह फ़ाइल पढ़ने लायक PDF नहीं है।",
    docx_malformed: "यह फ़ाइल पढ़ने लायक Word दस्तावेज़ नहीं है।",
    docx_encrypted: "यह Word दस्तावेज़ पासवर्ड-सुरक्षित है।",
    docx_no_text: "इस Word दस्तावेज़ के मुख्य भाग में कोई टेक्स्ट नहीं है।",
    doc_legacy_binary_unsupported: "पुराना .doc फ़ॉर्मैट नहीं पढ़ा जाता। इसे .docx के रूप में सेव करें और फिर कोशिश करें।",
    rtf_unsupported: "RTF नहीं पढ़ा जाता। इसे .docx या सादे टेक्स्ट के रूप में सेव करें।",
    odt_unsupported: "OpenDocument नहीं पढ़ा जाता। .docx या टेक्स्ट के रूप में एक्सपोर्ट करें।",
    pages_unsupported: "Pages फ़ाइलें नहीं पढ़ी जातीं। .docx या असली टेक्स्ट वाली PDF के रूप में एक्सपोर्ट करें।",
    epub_unsupported: "EPUB नहीं पढ़ा जाता।",
    archive_unsupported: "हम आर्काइव नहीं खोलते। इसके अंदर की फ़ाइलें अपलोड करें।",
    csv_unsupported: "स्प्रेडशीट गद्य नहीं है। इसे माइन करने से कॉलम हेडिंग आपकी भाषा शैली में आ जाएंगी।",
    spreadsheet_unsupported: "स्प्रेडशीट गद्य नहीं है।",
    slides_unsupported: "स्लाइड शीर्षक और टुकड़े हैं, यह नहीं कि आप कैसे बोलते हैं। अगर यही मकसद था तो स्पीकर नोट्स एक्सपोर्ट करें।",
    structured_data_unsupported: "स्ट्रक्चर्ड डेटा गद्य नहीं है।",
    html_upload_unsupported: "इसके बजाय पेज का लिंक पेस्ट करें। अपलोड की गई HTML फ़ाइल में बताने के लिए कोई सोर्स नहीं है।",
    text_not_utf8: "यह फ़ाइल UTF-8 टेक्स्ट नहीं है। इसे UTF-8 के रूप में फिर से सेव करें।",
    text_unreadable: "यह फ़ाइल भाषा जैसी नहीं पढ़ती।",
    format_unsupported: "हम इस फ़ाइल प्रकार को नहीं पढ़ते।",
    image_format_unsupported: "PNG, JPEG, या WebP तस्वीर इस्तेमाल करें। अन्य इमेज कंटेनर अभी नहीं पढ़े जाते।",
    image_dimensions_unreadable: "हम इस तस्वीर के पिक्सेल आकार की पुष्टि नहीं कर सके, इसलिए कोई इमेज सबूत नहीं रखा गया।",
    image_dimensions_invalid: "यह तस्वीर अमान्य पिक्सेल आकार बताती है।",
    image_malformed: "यह पढ़ने लायक तस्वीर नहीं है।",
    extracted_text_too_large: "यह दस्तावेज़ एक आइटम की सीमा से लंबा है। इसे बांटकर हिस्से अपलोड करें। हम कुछ भी चुपचाप नहीं काटते।",
    file_too_large: "यह फ़ाइल एक अपलोड की सीमा से बड़ी है।",
    chat_export_third_party_consent_required: "यह एक चैट एक्सपोर्ट है, इसलिए इसमें किसी और के निजी संदेश हैं। ऊपर वाला बॉक्स चुनें और इसे फिर से जोड़ें। हम सिर्फ़ आपके अपने संदेश माइन करते हैं, और उनके संदेश सिर्फ़ दोनों को अलग बताने के लिए पढ़े जाते हैं।",
    chat_export_too_many_speakers: "यह एक बड़ा ग्रुप चैट है, ज़्यादातर दूसरों के शब्द। इसके बजाय एक-से-एक चैट एक्सपोर्ट करें।",
    whatsapp_export_unparseable: "यह चैट एक्सपोर्ट जैसा दिखता है पर इसकी कोई लाइन संदेश से मेल नहीं खाई। चैट को फिर से 'बिना मीडिया के' एक्सपोर्ट करें और .txt फ़ाइल बिना बदले अपलोड करें।",
    link_unparseable: "यह कोई लिंक नहीं है।",
    link_scheme_unsupported: "सिर्फ़ https लिंक पढ़े जाते हैं।",
    link_host_not_public: "हम सिर्फ़ सार्वजनिक वेबसाइट के लिंक पढ़ते हैं।",
    article_fetch_not_configured: "यह डिप्लॉयमेंट अभी लिंक नहीं पढ़ सकता। इसके बजाय टेक्स्ट अपलोड करें।",
    article_fetch_failed: "हम वह पेज लोड नहीं कर सके।",
    article_no_text: "उस पेज में पढ़ने लायक कोई टेक्स्ट नहीं था।",
    article_unreadable: "वह पेज भाषा जैसा नहीं पढ़ा।",
    channel_lane: "यह YouTube है। यह चैनल लेन से जुड़ा है, जो एक भी वीडियो पढ़ने से पहले चैनल आपका होने की पुष्टि मांगती है।",
    voice_evidence_lane: "यह ऑडियो है। यह वॉइस लेन से जुड़ा है, जो आपकी आवाज़ के लिए ज़रूरी अनुमति रखती है।",
    not_owner_authored_no_style_evidence: "पढ़ा गया, पर आपके बोलने के तरीके के लिए इस्तेमाल नहीं हुआ, क्योंकि यह आपकी अपनी लिखावट नहीं है। अगर यह आपकी है तो इसे अपना बताएं।",
    speaker_unattributed_no_style_evidence: "पढ़ा गया। हमें बताएं कि इनमें से कौन आप हैं और हम सिर्फ़ आपके संदेश माइन करेंगे।",
    declared_speaker_not_in_export: "इस एक्सपोर्ट में उस नाम से कोई संदेश नहीं भेजता।",
    no_candidates_cleared_held_out: "पढ़ा गया, पर इसमें कुछ भी सुझाव देने लायक बार-बार नहीं आया। छोटे दस्तावेज़ के लिए यह सामान्य है।",
    citation_integrity_failed: "पढ़ा गया, पर सुझावों को उस टेक्स्ट तक वापस नहीं जोड़ा जा सका जहां से वे आए, इसलिए कोई नहीं रखा गया।",
    proposal_already_exists: "सुझाव पहले से निजी तौर पर सेव हैं।",
    image_ocr_not_configured: "एक सटीक इमेज हैश और पिक्सेल क्षेत्र के साथ निजी तौर पर सेव किया गया। OCR और विज़ुअल व्याख्या जुड़ी नहीं है, इसलिए इससे कोई दावा नहीं बनाया गया।",
    context_source_permissions_required: "यह फ़ाइल जोड़ने से पहले सोर्स कैप्चर और निजी स्टोरेज की अनुमति दर्ज करें।",
    context_private_storage_failed: "निजी स्टोरेज इस फ़ाइल को नहीं रख सकी। इससे कुछ भी नहीं लिया गया। फिर कोशिश करें।",
    context_locker_response_invalid: "निजी कॉन्टेक्स्ट से एक अपठनीय जवाब आया। कुछ भी नहीं जोड़ा गया। फिर कोशिश करें।",
    context_item_quota_exhausted: "आपका लॉकर भर गया है। और जोड़ने के लिए कुछ हटाएं।",
    context_byte_quota_exhausted: "आपके लॉकर में जगह नहीं है। और जोड़ने के लिए कुछ हटाएं।",
    replica_not_found: "यह AI आपका नहीं है।",
  },
  errorFallback: "अनुरोध विफल रहा",
  teachYourAi: "अपने AI को सिखाएं",
  testThisSource: "यह सोर्स टेस्ट करें",
  viewPhrases: "वाक्यांश देखें",
  writingAttributionAriaLabel: "लेखन का श्रेय",
  myWriting: "मेरी लिखावट",
  referenceOnly: "सिर्फ़ संदर्भ",
  heading: "अपना कॉन्टेक्स्ट लाएं",
  intro: "वह सब कुछ जो आप पहले ही अपने बारे में लिख चुके हैं, या जो पहले से आपके बारे में है। फ़ाइलें डालें, लिंक पेस्ट करें। हर एक बताता है कि वह क्या बना, और जो कुछ हम ईमानदारी से नहीं पढ़ सकते, उसे चुपचाप रखने के बजाय हम यह बता देते हैं।",
  dropzoneTitle: "अपनी फ़ाइलें यहां डालें",
  dropzoneBodyTemplate: "टेक्स्ट, Markdown, Word दस्तावेज़, असली टेक्स्ट वाली PDF, WhatsApp चैट एक्सपोर्ट, और PNG, JPEG, या WebP तस्वीरें। हर एक {size} तक। ऑडियो वॉइस लेन में जाता है और YouTube चैनल लेन में। उन्हें पेस्ट करें और हम आपको दोबारा करने के बजाय वहां भेज देंगे।",
  fewMb: "कुछ MB",
  reading: "पढ़ा जा रहा है…",
  chooseFiles: "फ़ाइलें चुनें",
  chatConsentNote: "अगर मैं कोई चैट एक्सपोर्ट अपलोड करता/करती हूं, तो मैं समझता/समझती हूं कि इसमें किसी और के निजी संदेश हैं, कि सिर्फ़ मेरे संदेश ही कभी इस्तेमाल होंगे, और उनके संदेश सिर्फ़ दोनों को अलग बताने के लिए पढ़े जाते हैं।",
  pasteLinksLabel: "या लिंक पेस्ट करें, एक लाइन में एक",
  linksPlaceholder: "https://example.com/an-interview-with-me\nhttps://example.com/my-essay",
  addLinks: "लिंक जोड़ें",
  iAmSpeakerTemplate: "मैं {name} हूं ({count})",
  openingPhrases: "वाक्यांश खुल रहे हैं",
  inYourLocker: "आपके लॉकर में",
  loadingEllipsis: "लोड हो रहा है…",
  nothingYet: "अभी कुछ नहीं है।",
  charactersTemplate: "{n} अक्षर",
  yourMessagesAsTemplate: "{name} के रूप में आपके संदेश",
  remove: "हटाएं",
  quotaTemplate: "{maxItems} में से {items} आइटम · {maxBytes} में से {bytes}।",
  states: {
    notAdded: "नहीं जोड़ा गया",
    suggestionSingularTemplate: "{n} सुझाव",
    suggestionPluralTemplate: "{n} सुझाव",
    suggestionsSaved: "सुझाव सेव हो गए",
    notRead: "नहीं पढ़ा गया",
    belongsElsewhere: "कहीं और से जुड़ा है",
    read: "पढ़ा गया",
    working: "काम हो रहा है…",
  },
  phraseSuggestionsSavedPrivately: "वाक्यांश सुझाव निजी तौर पर सेव हैं।",
};

const HI_VOICE_PREVIEW_PANEL: VoicePreviewPanelCopy = {
  languageOptions: {
    hi: { label: "हिन्दी", help: "देवनागरी में हिंदी लिखें। जाने-पहचाने अंग्रेज़ी शब्द अंग्रेज़ी में ही रह सकते हैं।" },
    hiLatn: { label: "हिंग्लिश", help: "रोमन में सहज हिंदी और अंग्रेज़ी लिखें। पूरी लाइन एक साथ प्लान होती है ताकि भाषा बदलने पर भी एक ही लय बनी रहे।" },
    en: { label: "अंग्रेज़ी", help: "वह सटीक अंग्रेज़ी लाइन लिखें जो आप ड्राफ्ट से कहलवाना चाहते हैं।" },
  },
  likeness: {
    ariaLabel: "आपकी जैसी आवाज़",
    heading: "आपकी जैसी आवाज़",
    scoreTemplate: "100 में से {n}",
    measuredOnTemplate: ", {date} को मापा गया।",
    stale: " इसे मापे जाने के बाद आपकी आवाज़ बदल गई है, इसलिए एक नया स्कोर बाकी है।",
    notMeasuredYet: "अभी मापा नहीं गया।",
    tieTemplate: "{date} को आपके आखिरी लिसनिंग टेस्ट में, आपने दोनों सैंपल को बराबर रेट किया।",
    preferredTemplate: "{date} को आपके आखिरी लिसनिंग टेस्ट में, आपने एक सैंपल को दूसरे से बेहतर बताया।",
    noListeningTestYet: "आपने अभी तक कोई लिसनिंग टेस्ट नहीं किया है।",
    methodMeasuredTemplate: "यह आपके {n} खुद के ब्लाइंड लिसनिंग टेस्ट पर आधारित है, जिसमें दो सेव किए गए सैंपल को आपकी अपनी रेफरेंस रिकॉर्डिंग के साथ परखा गया: कितना आपकी आवाज़ जैसा लगता है, कितना नैचुरल लगता है, एक्सेंट कितना सही है, और शब्द कितने साफ हैं।",
    methodNotMeasured: "यह स्कोर अभी तक सिर्फ एक ऑटोमैटिक माप है। इसे अपने असली सुनने के अनुभव से मिलाने के लिए एक ब्लाइंड लिसनिंग टेस्ट करें।",
  },
  stage: {
    protecting: "आपका प्रीव्यू सुरक्षित किया जा रहा है",
    generating: "आपका प्रीव्यू बनाया जा रहा है",
    waitingForRuntime: "वॉइस रनटाइम का इंतज़ार",
    wakingRuntime: "वॉइस रनटाइम जगाया जा रहा है",
  },
  eyebrow: "आपकी आवाज़",
  heading: "मेरी आवाज़ का प्रीव्यू",
  introTest: "एक लाइन लिखें और मौजूदा ड्राफ्ट को हिंदी, हिंग्लिश, या अंग्रेज़ी में सुनें।",
  introLive: "आपकी अपनी सहमति से हुई रिकॉर्डिंग से बना एक निजी ड्राफ्ट। हर क्लिप बोले गए AI डिस्क्लोज़र के साथ शुरू होती है और इसमें एक अश्रव्य वॉटरमार्क होता है। प्रीव्यू करने से कुछ भी सक्रिय नहीं होता और किसी और को इसे सुनने नहीं दिया जाता।",
  lineage: {
    ariaLabel: "आवाज़ ड्राफ्ट के सोर्स",
    versionTemplate: "आवाज़ ड्राफ्ट v{version}",
    primaryVoiceLabel: "मुख्य आवाज़: आपकी मुख्य रिकॉर्डिंग",
    chooseRecordingLabel: "चुनें कि कौन सी रिकॉर्डिंग आवाज़ चलाए",
    sourceDetailsLoading: "सोर्स की जानकारी अभी लोड हो रही है",
    rolePrimary: "मुख्य आवाज़",
    roleVideo: "सहायक वीडियो",
    roleAudio: "सहायक ऑडियो",
    roleSource: "सहायक सोर्स",
    kindPrimary: "आपकी मुख्य रिकॉर्डिंग",
    kindVideo: "अपलोड किया गया वीडियो",
    kindAudio: "अपलोड किया गया ऑडियो",
    kindContext: "सहायक कॉन्टेक्स्ट",
    referenceSecondsTemplate: "{n} सेकंड की आवाज़ रेफरेंस",
    referenceSelected: "आवाज़ रेफरेंस चुना गया",
    addedOnTemplate: " · {date} को जोड़ा गया",
    technicalReference: "तकनीकी रेफरेंस",
    privateSourceTemplate: "निजी सोर्स {code}",
    manageSources: "सोर्स प्रबंधित करें",
  },
  languageLegend: "प्रीव्यू भाषा",
  yourLine: "आपकी लाइन",
  charactersLeftTemplate: "{n} अक्षर बाकी",
  disclosureAddedSuffix: " बोला गया AI डिस्क्लोज़र आपके लिए अपने आप जोड़ा जाता है।",
  remoteIntentNote: "जब आप यहां लिख रहे थे तब एक और टैब में प्रीव्यू शुरू हुआ।",
  joinThatPreview: "उस प्रीव्यू में शामिल हों",
  reasons: {
    checkingDraftHeadline: "हम अभी जांच रहे हैं कि आपके पास ड्राफ्ट आवाज़ है या नहीं।",
    checkingDraftDetail: "इसमें थोड़ा समय लगता है। जांच पूरी होते ही बटन अपने आप चालू हो जाएगा।",
    busyPendingTemplate: "{stage}। यह एक ही टिकाऊ अनुरोध है, भले ही कई टैब इसे देख रहे हों।",
    busyConnecting: "हम आपके मौजूदा प्रीव्यू अनुरोध से जुड़ रहे हैं।",
    busyOnlineDetail: "जब तक यह पेज खुला है यह जांचता रहता है। अगर आप चले जाएं, तो अनुरोध सेव रहता है और लौटने पर जांच फिर शुरू होती है।",
    busyOfflineDetail: "आपका डिवाइस ऑफ़लाइन है। अनुरोध सेव रहता है और यह पेज अपने आप फिर जुड़ जाता है।",
    offlineHeadline: "यह डिवाइस ऑफ़लाइन है, इसलिए यह प्रीव्यू शुरू नहीं कर सकता।",
    offlineDetail: "इंटरनेट से फिर जुड़ें। आपकी लाइन यहीं रहेगी।",
    emptyHeadline: "बॉक्स खाली है, इसलिए कहने के लिए कुछ नहीं है।",
    emptyDetail: "अपने AI के बोलने के लिए एक लाइन लिखें।",
    overLimitTemplate: "यह प्रीव्यू की {max} अक्षरों की सीमा से लंबा है।",
    overLimitDetail: "इसे छोटा करें और बटन चालू हो जाएगा।",
  },
  button: {
    connecting: "जुड़ रहा है",
    previewUpdatedLine: "अपडेट की गई लाइन का प्रीव्यू",
    regeneratePreview: "प्रीव्यू फिर से बनाएं",
    previewMyVoice: "मेरी आवाज़ का प्रीव्यू",
  },
  announcement: {
    connectionLost: "कनेक्शन टूट गया। आपका प्रीव्यू अनुरोध सेव रहता है और यह पेज अपने आप फिर जुड़ जाएगा।",
    pendingTemplate: "{stage}। {note}",
    joinedNote: "यह पेज मौजूदा प्रीव्यू अनुरोध में शामिल हुआ।",
    savedCheckingNote: "आपका अनुरोध सेव है और यह पेज इसकी सर्वर स्थिति जांच रहा है।",
    connectingExisting: "आपके मौजूदा प्रीव्यू अनुरोध से जुड़ रहे हैं।",
    ready: "आपका सुरक्षित आवाज़ प्रीव्यू चलाने के लिए तैयार है।",
    stopped: "यह प्रीव्यू अनुरोध रुक गया। नया अनुरोध शुरू करने के लिए फिर से बनाएं दबाएं।",
    errorTemplate: "प्रीव्यू रुक गया। {headline}",
  },
  ready: {
    readyLabel: "तैयार",
    listenHeading: "यह टेक सुनें",
    audioFallback: "आपका ब्राउज़र यह सुरक्षित WAV नहीं चला सकता।",
    pronunciationSummaryTemplate: "{n} हिंदी उच्चारण वर्तनी लगाई गईं",
    spokenAsPrefix: "इस तरह बोला गया: ",
    planNoteTemplate: "आपका मूल टेक्स्ट नहीं बदला है। प्लान {plan} इस प्रीव्यू के साथ सेव है।",
    disclosureLabel: "डिस्क्लोज़र",
    disclosureValue: "हर क्लिप में बोला गया",
    watermarkLabel: "वॉटरमार्क",
    watermarkValue: "PerTh, रिलीज़ से पहले पुष्ट",
    notRightYet: "अभी सही नहीं लगा?",
    correctionNote: "नए इरादे के लिए लाइन बदलें, या इन्हीं शब्दों का एक और टेक पाने के लिए प्रीव्यू फिर से बनाएं इस्तेमाल करें।",
    editTheLine: "लाइन बदलें",
    receiptTemplate: "रसीद {generationId}, अनुरोध {intentId}, मॉडल {modelCommitment}",
    reusedNote: "। यह इस अनुरोध के लिए पहले से सील किया गया सुरक्षित नतीजा है।",
  },
  pending: {
    runtimeStarting: "रनटाइम शुरू हो रहा है",
    audioProcessing: "ऑडियो प्रोसेसिंग",
    offlineNote: "यह फ़ोन ऑफ़लाइन है। अनुरोध और नवीनतम सर्वर स्थिति सेव है। फिर जुड़ने पर यह पेज फिर से जांचता है।",
    joinedFromAnotherTab: "यह पेज किसी और टैब या पहले की विज़िट में शुरू हुए प्रीव्यू में शामिल हुआ।",
    waitMetricsAriaLabel: "वॉइस रनटाइम प्रतीक्षा",
    elapsedLabel: "बीता समय",
    observedRangeLabel: "देखी गई सीमा",
    observedRangeTemplate: "{low} से {high} मिनट",
    returnAroundLabel: "इसके आसपास लौटेगा",
    beyondWindowNote: "यह देखी गई कोल्ड-स्टार्ट सीमा से आगे है। यही अनुरोध अभी भी जांचा जा रहा है; फिर से शुरू करने से यह तेज़ नहीं होगा।",
    reusedRequestNote: "सर्वर को यही अनुरोध मिला और उसने इस पेज को उससे जोड़ दिया। कोई दूसरा जनरेशन नहीं बना।",
    savedRequestOnlineTemplate: "सर्वर ने यह अनुरोध सेव किया। अगली जांच करीब {n} सेकंड में।",
    savedRequestOfflineNote: "सर्वर ने यह अनुरोध सेव किया। फिर जुड़ने पर जांच फिर शुरू होगी।",
    leaveNote: "अनुरोध नंबर दिखने के बाद आप इस पेज को छोड़ सकते हैं। लौटने पर वही सेव किया गया अनुरोध फिर शुरू होता है।",
    requestDetails: "अनुरोध की जानकारी",
    savedRequestReceiptTemplate: "सेव किया गया अनुरोध {id}, {started} को शुरू, सर्वर कोशिश {attempt}",
    requestSnapshotTemplate: "अनुरोध स्नैपशॉट सेव · {started} को शुरू",
    closingPausesNote: "इस पेज को बंद करने से ब्राउज़र की जांच रुक जाती है। अनुरोध और नवीनतम सर्वर स्थिति सेव रहती है, और लौटने पर वही अनुरोध फिर शुरू होता है। जांच के दौरान लाइन और भाषा लॉक रहती हैं।",
    keepOpenNote: "जब तक सर्वर एक सेव किया गया अनुरोध नंबर न दे, यह पेज खुला रखें। आपकी सटीक लाइन इस ब्राउज़र में सुरक्षित है, और यह पेज अपने आप फिर जांचता है।",
    lastCheckUnfinished: "पिछली सर्वर जांच पूरी नहीं हुई। आपका सेव किया गया प्रीव्यू अनुरोध बदला नहीं गया है।",
    noReceiptYet: "सर्वर ने अभी अनुरोध रसीद नहीं दी। आपकी सटीक लाइन इस ब्राउज़र में सेव है।",
  },
  submitting: {
    stateLabel: "जुड़ रहा है",
    heading: "यह प्रीव्यू अनुरोध खोजा जा रहा है",
    messageTest: "सर्वर इन्हीं सटीक शब्दों के लिए एक अनुरोध खोज रहा है या बना रहा है।",
    messageLive: "सर्वर इन्हीं सटीक शब्दों, आवाज़ ड्राफ्ट और भाषा के लिए एक अनुरोध खोज रहा है या बना रहा है।",
    note: "अगर किसी और टैब ने इसे पहले ही शुरू किया है, तो यह पेज उसी अनुरोध में शामिल होता है। यह दूसरा ऑडियो जनरेशन नहीं बनाता।",
  },
  failed: {
    stateLabel: "अनुरोध बंद हुआ",
    heading: "यह प्रीव्यू रुक गया",
    body: "एक सुरक्षित क्लिप सील होने से पहले सर्वर ने यह अनुरोध खत्म कर दिया। यह हमारी तरफ़ से है, आपने कुछ नहीं किया।",
    note: "अलग अनुरोध के लिए लाइन बदलें, या इन्हीं सटीक शब्दों का नया टेक पाने के लिए एक बार प्रीव्यू फिर से बनाएं इस्तेमाल करें।",
    receiptTemplate: "अनुरोध {intentId} / रुका {updatedAt} / कोशिश {attempt} / कोड {errorCode}",
  },
  error: {
    stateLabel: "काम नहीं हुआ",
    heading: "प्रीव्यू रुक गया",
    voiceNotReadyHeadline: "वॉइस प्रीव्यू अभी तैयार नहीं है",
    connectionDetail: "हम वॉइस कनेक्शन पूरा कर रहे हैं। कोई प्रीव्यू शुरू नहीं हुआ है।",
    attemptCheckDetail: "फिर कोशिश करने से पहले हमें यह वॉइस प्रयास जांचना होगा।",
    checkVoiceSources: "वॉइस सोर्स जांचें",
  },
  idle: {
    stateLabel: "अभी कुछ नहीं बना",
    heading: "आपका टेक यहां दिखेगा",
    body: "भाषा चुनें, एक सहज लाइन लिखें, और मौजूदा ड्राफ्ट बनाएं।",
    firstWaitNote: "GPU सिर्फ़ प्रीव्यू दबाने के बाद शुरू होता है। शांत समय के बाद पहली बार चलाने में देखी गई 2 से 8 मिनट की कोल्ड-स्टार्ट सीमा होती है। इसके बाद, रनटाइम गर्म रहते हुए यह आमतौर पर बहुत तेज़ होता है।",
  },
  vibe: {
    toggle: "वाइब सुनें",
    helpOn: "यह प्रीव्यू आपकी मौजूदा EmotionOS वाइब इस्तेमाल करता है: रफ़्तार, ठहराव और ऊर्जा।",
    helpOff: "बंद: यह प्रीव्यू सादी आवाज़ इस्तेमाल करता है, बिना वाइब की शैली के।",
    confirmed: "आपकी मौजूदा वाइब के अनुसार ढाला गया।",
  },
};

const HI_MIRROR_CALL_STUDIO: MirrorCallStudioCopy = {
  kindLabel: { phraseHabit: "बोलने की आदत", register: "अंदाज़", boundary: "सीमा", fact: "तथ्य", delivery: "अदायगी" },
  caption: { you: "आप", yourClone: "आपका AI", missed: "छूट गया", call: "कॉल" },
  recovery: {
    recoveredEndReceipt: "सेव की गई एंड रसीद वापस मिल गई। इस ब्राउज़र में कोई रिकॉर्डिंग सेव नहीं हुई।",
    recovering: "सेव की गई एंड रसीद वापस लाई जा रही है। कोई माइक्रोफ़ोन या ऑडियो वापस नहीं लाया जा रहा।",
    recoverFailed: "सेव की गई एंड रसीद अभी वापस नहीं लाई जा सकी। सेशन आईडी इस टैब में रखी गई है ताकि आप फिर कोशिश कर सकें।",
    speakerCheckSaved: "स्पीकर जांच सेव हो गई। इस टैब को अब कॉल रिकवरी रिकॉर्ड की ज़रूरत नहीं है।",
  },
  mic: {
    permissionTimeout: "माइक्रोफ़ोन अनुमति 30 सेकंड में पूरी नहीं हुई।",
    micCouldNotOpen: "माइक्रोफ़ोन नहीं खुल सका",
  },
  changeApplied: "लागू",
  changeDismissed: "खारिज",
  callNoLongerOpen: "यह कॉल अब खुली नहीं है",
  contexts: {
    backendUnreachable: "मिरर कॉल बैकएंड तक नहीं पहुंचा जा सका",
    couldNotStart: "मिरर कॉल शुरू नहीं हो सकी",
    couldNotEndCleanly: "कॉल साफ़ तरीके से खत्म नहीं हो सकी",
    couldNotRecoverEndReceipt: "कॉल की एंड रसीद वापस नहीं लाई जा सकी",
    speakerCheckCouldNotBeSaved: "स्पीकर जांच सेव नहीं हो सकी",
    windowCouldNotBeSent: "वह विंडो नहीं भेजी जा सकी",
    proposedChangesCouldNotBeRefreshed: "प्रस्तावित बदलाव ताज़ा नहीं हो सके",
    changeCouldNotBeTemplate: "यह बदलाव {action} नहीं हो सका",
    ratingCouldNotBeSaved: "वह रेटिंग सेव नहीं हो सकी",
    micCouldNotOpenForRerecord: "फिर-रिकॉर्ड के लिए माइक्रोफ़ोन नहीं खुल सका",
    reRecordCouldNotBeSaved: "वह फिर-रिकॉर्ड सेव नहीं हो सका",
  },
  header: {
    eyebrow: "मिरर कॉल",
    heading: "अपने AI से बात करें और सुनते समय उसे सुधारें।",
    body: "आपका हिस्सा 30 सेकंड तक की विंडो में जाता है। तैनात लर्नर उद्धृत वाक्यांश या स्लैंग पैटर्न सुझा सकता है, और फिलर, हंसी, खिंची हुई बोली, और कोड-स्विचिंग के बारे में सलाह जैसे अवलोकन दिखा सकता है। सिर्फ़ वह उद्धृत सुझाव जिस पर आप स्वीकार करें दबाते हैं आपकी शीट तक पहुंच सकता है; बाकी सब बाद में समीक्षा में रहता है।",
  },
  stateBadge: {
    checking: "जांच हो रही है", notDeployed: "तैनात नहीं", waitingOnUs: "हमारी तरफ़ से इंतज़ार", ready: "तैयार",
    connecting: "जुड़ रहा है", gpuWarming: "GPU गर्म हो रहा है", live: "लाइव", ending: "खत्म हो रहा है", ended: "खत्म हुआ", stopped: "रुका",
  },
  tabs: { ariaLabel: "मिरर कॉल", call: "कॉल", reviewLater: "बाद में समीक्षा करें", countSuffixTemplate: " · {n}" },
  availabilityLabels: { observedRange: "देखी गई सीमा", nextCheck: "अगली जांच", leaveOrReturn: "छोड़ें या लौटें" },
  availability: {
    checking: {
      title: "कॉल उपलब्धता जांची जा रही है",
      phase: "कॉल शुरू करें दिखाने से पहले तैनात कॉल रूट की पुष्टि हो रही है।",
      range: "जब तक सर्वर जवाब न दे, पूरा होने का कोई अनुमान नहीं दिखता।",
      next: "यह जांच अभी चल रही है।",
      leave: "उपलब्धता जांच के लिए यह पेज खुला रखें।",
    },
    replyUnavailable: {
      title: "कॉल हमारी तरफ़ से रुकी हैं",
      phase: "निजी कॉल रूट ऑनलाइन है, पर इसकी बातचीत वाली जवाब सेवा सेट नहीं है।",
      range: "अभी शुरुआत का कोई अनुमान नहीं है।",
      next: "कॉल शुरू होने से पहले Vyakti को जवाब सेवा बहाल करनी होगी।",
      leave: "आप यह पेज छोड़ सकते हैं। रिकॉर्डिंग बंद है, और कोई नया कॉल सेशन नहीं बनेगा।",
    },
    recovering: {
      title: "पिछली कॉल वापस लाई जा रही है",
      phase: "इस टैब को एक सेव किया गया सेशन आईडी मिला और यह वही आइडमपोटेंट एंड अनुरोध दोहरा रहा है।",
      range: "इस ब्राउज़र में कोई ऑडियो, ट्रांसक्रिप्ट, कैप्शन, सुझाव, या स्पीकर फ़ैसला सेव नहीं हुआ।",
      next: "सेव की गई एंड रसीद अभी मांगी जा रही है।",
      leave: "जब तक वापस मिली रसीद या नामित फिर कोशिश न दिखे, यह टैब खुला रखें।",
    },
    idle: {
      title: "शुरू करने के लिए तैयार",
      phase: "कॉल रूट मौजूद हैं। कॉल शुरू करें दबाने के बाद ही GPU मांगा जाता है।",
      range: "ठंडे वॉइस GPU की देखी गई शुरुआत सीमा 2 से 8 मिनट है। गर्म GPU तेज़ जुड़ता है।",
      next: "अभी इस कॉल के लिए कोई GPU नहीं चल रहा।",
      leave: "तभी शुरू करें जब आपके पास कनेक्शन चरण तक यह टैब खुला रखने का समय हो।",
    },
    connecting: {
      title: "निजी कॉल खोली जा रही है",
      phase: "सर्वर सेशन बनाया जा रहा है और इसकी साइन की गई वॉइस-रनटाइम तैयारी जांची जा रही है।",
      range: "सर्वर ने अभी GPU अनुमान नहीं दिया है।",
      next: "अगली स्थिति सेशन के जवाब से आती है।",
      leave: "यह टैब खुला रखें। जब तक आप बात करें न दबाएं, ब्राउज़र माइक्रोफ़ोन एक्सेस नहीं मांगता।",
    },
    warming: {
      titleNormal: "वॉइस GPU शुरू हो रहा है",
      titleBeyondRange: "GPU शुरुआत देखी गई सीमा से आगे है",
      phase: "कॉल सेशन मौजूद है और सर्वर अपने निजी वॉइस रनटाइम का इंतज़ार कर रहा है।",
      rangeNoEstimate: "देखी गई कोल्ड-स्टार्ट सीमा: 2 से 8 मिनट।",
      rangeWithEstimateTemplate: "देखी गई कोल्ड-स्टार्ट सीमा: 2 से 8 मिनट। सर्वर का मौजूदा अनुमान करीब {n} {unit} है, पर इससे देखी गई सीमा छोटी नहीं होती।",
      minuteSingular: "मिनट",
      minutePlural: "मिनट",
      next: "अगली सर्वर तैयारी जांच 6 सेकंड में। सर्वर अनुमान उस जवाब से ताज़ा होता है।",
      leaveNoObservedHigh: "आप टैब या ऐप बदल सकते हैं, पर यह टैब खुला रखें ताकि कॉल तैयार हो सके।",
      leaveBeyondWindow: "देखी गई आठ-मिनट की सीमा बीत चुकी है; हम अभी भी जांच रहे हैं।",
      leaveWithinWindowTemplate: "लौटने का एक उपयोगी समय करीब {time} है, देखी गई सीमा का ऊपरी छोर।",
      leaveSuffix: " आप टैब या ऐप बदल सकते हैं, पर यह टैब खुला रखें। रीलोड करने से यह कॉल सेटअप खत्म हो जाता है।",
    },
    live: {
      title: "कॉल अभी तैयार है",
      phaseCapturing: "स्थानीय रूप से रिकॉर्ड हो रहा है। जब तक आप यह विंडो भेजें न दबाएं, कुछ नहीं भेजा जाता।",
      phaseUploading: "आपकी मंज़ूर की गई विंडो भेजी और ट्रांसक्राइब की जा रही है।",
      phaseThinking: "आपका AI अपना जवाब तैयार कर रहा है।",
      phaseSpeaking: "सुरक्षित AI जवाब चलाया जा रहा है।",
      phaseIdle: "आपकी अगली वॉइस विंडो के लिए तैयार। जब तक आप बात करें न दबाएं, माइक्रोफ़ोन बंद है।",
      range: "इस डिप्लॉयमेंट पर टर्न पूरा होने की कोई मापी गई सीमा नहीं है, इसलिए कोई काउंटडाउन नहीं दिखता।",
      nextIdle: "आपका इंतज़ार है।",
      nextTurn: "इसका मौजूदा सर्वर चरण पूरा होने पर यह टर्न अपडेट होता है।",
      leaveIdle: "लाइव कॉल के लिए यह टैब खुला रखें।",
      leaveTurn: "मौजूदा टर्न पूरा होने तक यह टैब खुला रखें।",
    },
    ending: {
      title: "कॉल खत्म हो रही है",
      phase: "एंड रसीद सेव की जा रही है और बिना छुए सुझाव बाद में समीक्षा में भेजे जा रहे हैं।",
      range: "इस चरण के लिए कोई मापी गई पूर्णता सीमा उपलब्ध नहीं है।",
      next: "सर्वर का जवाब सेशन बंद करता है।",
      leave: "जब तक एंड रसीद न दिखे, यह टैब खुला रखें।",
    },
    ended: {
      title: "कॉल खत्म हुई",
      phase: "एंड रसीद सेव है। बिना स्वीकार किए सुझाव बाद में समीक्षा में लागू नहीं हुए रहते हैं।",
      range: "लाइव कॉल पूरी हो गई है।",
      nextQueued: "सर्वर ने एक कॉल-लर्निंग अनुरोध दर्ज किया। इसके पूरा होने की उम्मीद से पहले जांच लें कि Activity में इसका रनर जुड़ा हुआ दिखता है या नहीं।",
      nextNotQueued: "कोई कॉल-लर्निंग अनुरोध दर्ज नहीं हुआ।",
      leaveChoosePending: "दूसरी कॉल शुरू करने से पहले चुनें कि कौन बोला। इस टैब को रीलोड करने से यह सवाल सर्वर से वापस आ जाता है।",
      leaveMayLeave: "अब आप जा सकते हैं। लौटने पर समीक्षा आइटम उपलब्ध रहते हैं।",
    },
    recoveryPaused: {
      title: "कॉल रिकवरी रुकी हुई है",
      range: "हो सकता है सर्वर ने कॉल पहले ही खत्म कर दी हो। नई कॉल शुरू करने से यह अस्पष्टता नहीं सुलझेगी।",
      next: "इसी सेशन के अंत को सुरक्षित तरीके से दोहराने के लिए एंड रसीद वापस लाएं दबाएं।",
      leave: "बिना कॉन्टेंट वाली सेशन आईडी इस टैब में रहती है। यहां कोई ऑडियो सेव नहीं है।",
    },
    stopped: {
      title: "कॉल रुक गई",
      range: "रुकी हुई कॉल का कोई पूर्णता अनुमान नहीं है।",
      next: "जब आप तैयार हों तो दूसरी कॉल शुरू करें।",
      leave: "इस कॉल में कुछ भी चुपचाप रिकॉर्ड या आगे नहीं बढ़ रहा है।",
    },
  },
  recoveryPausedPhaseFallback: "एंड रसीद इस टैब तक नहीं पहुंची।",
  stoppedPhaseFallback: "कॉल आगे नहीं बढ़ी।",
  speaker: {
    savedHeading: "स्पीकर जांच सेव हो गई",
    savedBodyTemplate: "{n} माइक्रोफ़ोन विंडो अब उद्धृत मेमोरी सुझावों के लिए जांची जा सकती हैं। हर सुझाव अभी भी आपकी समीक्षा का इंतज़ार करता है। आपकी AI आवाज़ नहीं बदली।",
    excludedHeading: "ये रिकॉर्डिंग मेमोरी लर्निंग से बाहर रहेंगी",
    excludedBody: "आपकी AI आवाज़ नहीं बदली है। जब आपके पास एक साफ़ रिकॉर्डिंग हो तो आप दूसरी कॉल शुरू कर सकते हैं।",
    consentRequiredHeading: "यह कॉल मेमोरी लर्निंग में शामिल नहीं हो सकती",
    consentRequiredBody: "कैप्चर, स्टोरेज, ट्रांसक्रिप्शन, या लर्निंग के लिए इस्तेमाल होने वाली एक या ज़्यादा अनुमतियां अब सक्रिय नहीं हैं। रिकॉर्डिंग दावा सुझावों से बाहर रहती है और आपकी AI आवाज़ नहीं बदलती।",
    questionLegend: "क्या आपके माइक्रोफ़ोन में सिर्फ़ आप ही बोल रहे थे?",
    questionBody: "हां तभी चुनें जब हर रिकॉर्ड की गई विंडो आप ही थे। यह चुनाव इस कॉल के लिए अंतिम है। AI की बनाई गई प्लेबैक शामिल नहीं है और कभी आपकी बोली नहीं गिनी जाती। इससे सिर्फ़ उद्धृत मेमोरी सुझाव तैयार करने की अनुमति मिलती है। हर सुझाव अभी भी आपकी समीक्षा का इंतज़ार करता है, और इससे AI की आवाज़ नहीं बदलती।",
    saving: "सेव हो रहा है...",
    yesOnlyMe: "हां, सिर्फ़ मैं",
    noOrNotSure: "नहीं या पक्का नहीं",
  },
  backendAbsent: {
    heading: "इस माहौल में मिरर कॉल बैकएंड तैनात नहीं है।",
    bodyBefore: "यह टैब ",
    bodyAfterTemplate: " से बात करता है, जिसने यहां कुछ जवाब नहीं दिया ({detail})। जानबूझकर मिरर कॉल का कोई ऑफ़लाइन डेमो नहीं है: एक नकली कॉल बिल्कुल असली कॉल जैसी दिखेगी।",
    missingTemplate: "क्या गायब है: {list}।",
  },
  replyUnavailable: {
    heading: "वॉइस कॉल अभी उपलब्ध नहीं हैं।",
    body: "आपका माइक्रोफ़ोन और AI समस्या नहीं हैं। इस माहौल में Vyakti की बातचीत वाली जवाब सेवा तैयार नहीं है, इसलिए यह स्क्रीन कॉल शुरू या रिकॉर्ड नहीं करेगी।",
    note: "जब तक यह सेवा उपलब्ध नहीं है, कोई कॉल सेशन या GPU शुरुआत नहीं मांगी जाती।",
  },
  controls: {
    checkingNote: "जांचा जा रहा है कि इस माहौल में कॉल बैकएंड है या नहीं।",
    endingCallSetup: "खत्म हो रहा है...",
    endCallSetup: "कॉल सेटअप खत्म करें",
    recoveringReceipt: "रसीद वापस लाई जा रही है...",
    recoverEndReceipt: "एंड रसीद वापस लाएं",
    finishSpeakerCheck: "ऊपर स्पीकर जांच पूरी करें",
    startAnotherCall: "दूसरी कॉल शुरू करें",
    startTheCall: "कॉल शुरू करें",
    ending: "खत्म हो रहा है...",
    finishReplyBeforeEnding: "खत्म करने से पहले यह जवाब पूरा करें",
    endCall: "कॉल खत्म करें",
  },
  mic2: {
    sendThisWindow: "यह विंडो भेजें",
    discard: "छोड़ें",
    openingMicrophone: "माइक्रोफ़ोन खोला जा रहा है...",
    transcribing: "ट्रांसक्राइब हो रहा है...",
    cloneAnswering: "आपका AI जवाब दे रहा है...",
    cloneSpeaking: "आपका AI बोल रहा है...",
    talk: "बात करें",
    capturingNote: "रिकॉर्ड हो रहा है। विंडो की सीमा 30 सेकंड है। यह तब भेजी जाती है जब आप कहें, या सीमा पर कट जाती है।",
    turnTakingNote: "एक बार में एक विंडो: पहले आपकी बारी, फिर इसकी। यह कैस्केड लेन है, डुप्लेक्स कॉल नहीं।",
    autoCutNote: "30-सेकंड की सीमा ने इस विंडो को काट दिया। इसे भेजें और बाकी अगली विंडो में कहें। कुछ भी चुपचाप नहीं छोड़ा गया।",
    micErrorSuffix: " फिर कोशिश के लिए बात करें दबाएं।",
    voiceUnavailableNote: "इस माहौल में सिर्फ़ कैप्शन हैं। AI का वॉइस रूट तैनात नहीं है।",
  },
  thread: {
    soundedLikeMe: "यह मेरे जैसा लगा",
    didNotSoundLikeMe: "यह मेरे जैसा नहीं लगा",
    stopAndSend: "रोकें और भेजें",
    idSayItLikeThis: "मैं इसे ऐसे कहूंगा/कहूंगी",
    emptyHeading: "अभी तक कुछ नहीं कहा गया है।",
    emptyBody: "आपका AI वही जवाब देता है जो आप कहते हैं और कभी खुद कॉल शुरू नहीं करता।",
  },
  dismiss: "खारिज करें",
  fidelity: {
    heading: "आवाज़ की निष्ठा",
    noPrintedCeiling: "कोई प्रिंट की गई सीमा नहीं",
    ceilingTemplate: "सीमा {n}",
    ofCeilingTemplate: "सीमा का {pct}",
    windowSingularTemplate: "{n} विंडो",
    windowPluralTemplate: "{n} विंडो",
    secondsPooledTemplate: "{n} सेकंड इकट्ठा",
    confidenceTemplate: "{pct} भरोसा",
    noWindowYet: "अभी कोई विंडो नहीं",
    windowSecondsTemplate: "{n} सेकंड की विंडो",
    reselectionSingularTemplate: "{n} फिर-चुनाव",
    reselectionPluralTemplate: "{n} फिर-चुनाव",
    referenceSetSingularTemplate: "रेफरेंस सेट: {n} सहमति वाली विंडो, {sec} सेकंड।",
    referenceSetPluralTemplate: "रेफरेंस सेट: {n} सहमति वाली विंडो, {sec} सेकंड।",
    droppedSingularTemplate: "{n} विंडो ट्रांसक्रिप्शन से नहीं गुज़र सकी।",
    droppedPluralTemplate: "{n} विंडो ट्रांसक्रिप्शन से नहीं गुज़र सकीं।",
  },
  rail: {
    heading: "प्रस्तावित बदलाव",
    waitingTemplate: "{n} इंतज़ार में",
    rollIntoReviewTemplate: " · अभी खत्म करने पर {n} बाद में समीक्षा में चले जाएंगे",
    heldBackTemplate: " · {cap}-प्रति-मिनट सीमा ने {n} रोक लिए",
    refresh: "ताज़ा करें",
    heardTemplate: "{n} बार सुना",
    becauseYouSaidTemplate: "क्योंकि आपने कहा “{quote}”",
    applying: "लागू हो रहा है...",
    accept: "स्वीकार करें",
    dismissing: "खारिज हो रहा है...",
    reject: "अस्वीकार करें",
    emptyLive: "इस कॉल से अभी तक कुछ नहीं निकला। जैसे-जैसे आप बोलते हैं, चिप्स दिखेंगी, हर एक उसका हवाला देते हुए जिससे वह बनी।",
    emptyIdle: "कॉल के दौरान चिप्स दिखती हैं।",
    actionedThisCall: "इस कॉल में तय किया गया",
    applied: "लागू",
    acceptedNotOnSheet: "स्वीकृत, अभी शीट पर नहीं",
    rejected: "अस्वीकृत",
  },
  review: {
    intro: "यहां कुछ भी लागू नहीं हुआ। ये वे चिप्स हैं जिन पर आपने कॉल खत्म होने से पहले फ़ैसला नहीं लिया, साथ ही वे जिन्हें {cap}-प्रति-मिनट रेल सीमा ने रोक लिया ताकि कॉल सवालों की झड़ी न बन जाए। ये सामान्य समीक्षा कतार में गए, बिल्कुल वैसे ही जैसे अपलोड से निकला कोई बदलाव।",
    neverShown: "कभी नहीं दिखा, रेल सीमा ने रोका, लागू नहीं हुआ",
    notAppliedReviewLater: "लागू नहीं हुआ · बाद में समीक्षा करें",
    emptyWaiting: "समीक्षा के लिए कुछ भी इंतज़ार में नहीं है।",
    summaryTemplate: "{accepted} स्वीकृत, {rejected} अस्वीकृत, {deferred} टाले गए",
    finetuneQueued: "सर्वर ने एक वॉइस-लर्निंग अनुरोध दर्ज किया। यह पूरा होने का दावा नहीं है; इसके चलने से पहले Activity में इसका रनर जुड़ा हुआ दिखना चाहिए।",
    finetuneNotQueuedTemplate: "कोई फ़ाइन-ट्यून कतार में नहीं था{reason}।",
  },
};

const HI_CLONE_EXPERIENCE_SHELL: CloneExperienceShellCopy = {
  capture: {
    stayLocalHint: "जारी रखें चुनने तक यह फ़ाइल स्थानीय रहती है।",
    addKnowledgeFirst: "पहले जानकारी जोड़ें",
    readyHeading: "अपनी रिकॉर्डिंग सुनें।",
    sayHeading: "अपनी आवाज़ से शुरू करें।",
    readyBody: "भाषा चुनें, फिर जारी रखें।",
    sayBody: "अपने शब्दों में कोई विचार बताएँ।",
    minMinimum: "कम से कम 12 सेकंड",
    idealLength: "आदर्श रूप से 30 सेकंड",
    localFirst: "पहले स्थानीय",
    finishRecordingAriaTemplate: "रिकॉर्डिंग खत्म करें। {duration} रिकॉर्ड हुआ",
    startRecordingAria: "आवाज़ रिकॉर्डिंग शुरू करें",
    opening: "खुल रहा है",
    finish: "खत्म करें",
    begin: "शुरू करें",
    audioReady: "ऑडियो तैयार है",
    sealedWav: "सिर्फ़ इस डिवाइस पर",
    fileLabelTemplate: "{size} {kind} फ़ाइल",
    videoFallback: "आपका ब्राउज़र यह वीडियो प्रीव्यू नहीं कर सकता।",
    audioFallback: "आपका ब्राउज़र यह ऑडियो प्रीव्यू नहीं कर सकता।",
    onlyMyVoice: "इस फ़ाइल में सिर्फ़ मेरी आवाज़ है, या मैंने बाकी सभी वक्ताओं को हटा दिया है।",
    howDidYouSpeak: "भाषा",
    tryAgain: "फिर कोशिश करें",
    continueLabel: "जारी रखें",
    secondsToGoTemplate: "{n} सेकंड बाकी",
    enoughToFinish: "खत्म करने लायक",
    strongSampleLength: "मज़बूत नमूना लंबाई",
    aboutThirtySeconds: "करीब 30 सेकंड साफ़ आवाज़ में बोलें।",
    finishAtEnd: "इस विचार के अंत में खत्म करें।",
    useFileInstead: "इसके बजाय ऑडियो या वीडियो फ़ाइल इस्तेमाल करें",
    chooseRecordingAria: "अपनी आवाज़ रिकॉर्डिंग चुनें",
    signalCouldNotReadDuration: "यह ब्राउज़र अवधि नहीं पढ़ सका। एक अलग ऑडियो या वीडियो फ़ाइल चुनें।",
    signalChooseTwelveSeconds: "कम से कम 12 सेकंड की साफ़, एक-वक्ता वाली ऑडियो चुनें।",
    signalVerifiedDuringProcessing: "बोली और सिग्नल की गुणवत्ता निजी प्रोसेसिंग के दौरान जांची जाएगी।",
    signalClipped: "माइक्रोफ़ोन की सीमा पार हो गई। थोड़ा दूर होकर फिर कोशिश करें।",
    signalTooQuiet: "नमूने का ज़्यादातर हिस्सा धीमा है। पास आकर फिर कोशिश करें।",
    signalUsable: "रिकॉर्डिंग की आवाज़ ठीक लग रही है।",
    initialHint: "शुरू करें दबाएँ। बोलने के बाद खत्म करें दबाएँ।",
    keepSpeakingTemplate: "{n} और सेकंड बोलते रहें।",
    reviewHint: "जारी रखने पर ही रिकॉर्डिंग अपलोड होगी।",
    recordingFailed: "रिकॉर्डिंग खत्म नहीं हो सकी।",
    recordingHint: "किसी भी विषय पर सहज होकर बोलें। स्क्रिप्ट से एक पूरा विचार बेहतर है।",
    micOpenFailed: "ब्राउज़र आपका माइक्रोफ़ोन नहीं खोल सका।",
  },
  agreement: {
    labelOwnSources: "ये मेरे सोर्स हैं, और मैं सिर्फ़ अपना निजी AI बना रहा/रही हूं।",
    labelAgeAndDisclosure: "मैं 18 या उससे ज़्यादा उम्र का/की हूं और समझता/समझती हूं कि हर बना हुआ क्लिप डिस्क्लोज़ और सुरक्षित है।",
    labelPrivacyTerms: "मैं निजी कैप्चर, स्टोरेज, और ट्रांसक्रिप्शन के लिए गोपनीयता नीति और शर्तें स्वीकार करता/करती हूं।",
    heading: "इसे अपना बनाएं।",
    body: "चुनें कि आपका AI क्या इस्तेमाल कर सकता है। आप इसे बाद में बदल या मिटा सकते हैं।",
    everythingSelected: "सब कुछ चुना गया",
    selectAll: "सभी चुनें",
    legalPrefix: "यह पढ़ें ",
    legalLinkText: "गोपनीयता नीति और शर्तें",
    legalSuffix: "। AI अनुमति अलग है, पहचान से जुड़ी है, और वॉइस AI बनने से पहले दिखाई जाती है। आप बाद में एक सोर्स या पूरा AI मिटा सकते हैं।",
    openingPrivateSpace: "आपकी निजी जगह खुल रही है",
    agreeAndContinue: "सहमत हों और जारी रखें",
    couldNotRecordAgreement: "हम समझौता दर्ज नहीं कर सके। कुछ भी अपलोड नहीं हुआ।",
  },
  roomNav: {
    ariaLabel: "AI कमरे",
    meet: "मिलें",
    knowledge: "जानकारी",
    review: "समीक्षा",
    call: "कॉल",
    share: "शेयर करें",
  },
  describeMe: {
    savedNote: "निजी कॉन्टेक्स्ट के रूप में सेव हुआ। कोई भी टिकाऊ बदलाव आपकी समीक्षा का इंतज़ार करेगा।",
    notStoredError: "नोट सेव नहीं हुआ।",
    notSavedError: "नोट सेव नहीं हो सका।",
    heading: "खुद को सहज तरीके से बताएं।",
    body: "एक वाक्य या एक पेज ठीक है। Vyakti इसे उद्धृत सुझावों में बदलता है, कभी चुपचाप व्यक्तित्व नहीं बदलता।",
    placeholder: "मैं करीबी दोस्तों के साथ गर्मजोशी से पेश आता/आती हूं, काम पर सीधा, और उत्साहित होने पर हिंदी में बदल जाता/जाती हूं...",
    savingPrivately: "निजी तौर पर सेव हो रहा है",
    addToContext: "अपने कॉन्टेक्स्ट में जोड़ें",
    charactersTemplate: "{n} अक्षर",
  },
  drawer: {
    closeDrawerAria: "AI ड्रॉअर बंद करें",
    dialogAria: "आपके AI और वर्शन",
    heading: "आपके Vyakti",
    closeAria: "बंद करें",
    voiceVersionTemplate: "आवाज़ v{n}",
    createAnother: "एक और AI बनाएं",
    replacePrimary: "मुख्य रिकॉर्डिंग बदलें",
    deleteClone: "यह AI मिटाएं",
    deleteConfirmBody: "यह अभी AI को रोकता है और सत्यापित मिटाना शुरू करता है।",
    deleting: "मिटाया जा रहा है",
    deletePermanently: "हमेशा के लिए मिटाएं",
    cancel: "रद्द करें",
  },
  header: {
    openClonesAria: "अपने AI खोलें",
    homeAria: "Vyakti होम",
    openAccountMenuAria: "खाता मेनू खोलें",
    signOut: "साइन आउट",
  },
  readStates: {
    workspaceError: "हम आपका वर्कस्पेस लोड नहीं कर सके।",
    workspaceLoading: "आपका वर्कस्पेस खुल रहा है।",
    tryAgain: "फिर कोशिश करें",
    checkingSavedClones: "आपके सेव किए गए AI जांचे जा रहे हैं।",
    openingPrivateDraftTest: "निजी ड्राफ्ट टेस्ट खुल रहा है",
    consentError: "हम आपकी अनुमतियों की पुष्टि नहीं कर सके।",
    consentLoading: "आपकी अनुमतियां जांची जा रही हैं।",
    checkAgain: "फिर जांचें",
    loadingAgreement: "आपका सेव किया गया समझौता लोड हो रहा है।",
  },
  upload: {
    hashMessage: "इस डिवाइस पर रिकॉर्डिंग जांची जा रही है",
    authorizeMessage: "एक निजी अपलोड खोला जा रहा है",
    uploadAuthMissing: "निजी अपलोड की अनुमति मौजूद नहीं है।",
    uploadMessage: "रिकॉर्डिंग निजी स्टोरेज में भेजी जा रही है",
    sourceReceiptMissing: "निजी सोर्स रसीद मौजूद नहीं है।",
    renewMessage: "निजी अपलोड फिर से शुरू किया जा रहा है",
    resumeMessage: "निजी अपलोड फिर से शुरू हो रहा है",
    verifyMessage: "सेव की गई रिकॉर्डिंग की पुष्टि हो रही है",
    selectMessage: "इस सटीक रिकॉर्डिंग के लिए निजी सत्यापन खुल रहा है",
    stoppedBeforeBuild: "बनना शुरू होने से पहले अपलोड रुक गया।",
    pausedHeading: "अपलोड रुका हुआ है।",
    securingHeading: "आपकी रिकॉर्डिंग सुरक्षित की जा रही है।",
    checkingRecording: "रिकॉर्डिंग जांची जा रही है",
    uploadingPercentTemplate: "{n}% अपलोड हो रहा है",
    paused: "रुका हुआ",
    openingPrivateUpload: "निजी अपलोड खोला जा रहा है",
    verifyingReceipt: "रसीद की पुष्टि हो रही है",
    selectingVoice: "आवाज़ चुनी जा रही है",
    recordingStillHere: "रिकॉर्डिंग अभी भी इस टैब में है। फिर कोशिश के लिए इसे खुला रखें।",
    retrySafely: "सुरक्षित तरीके से फिर कोशिश करें",
    recordAgain: "फिर रिकॉर्ड करें",
    keepPageOpen: "जब तक निजी स्टोरेज अपलोड की पुष्टि न कर दे, यह पेज खुला रखें।",
  },
  sagaRecovery: {
    heading: "अपनी रिकॉर्डिंग फिर से जोड़ें।",
    body: "यह ब्राउज़र सटीक निजी अपलोड अनुरोध याद रखता है। इसकी सर्वर रसीद के लिए एक बार जांचें, या अगर पिछला टैब अपलोड से पहले बंद हो गया था तो एक नई रिकॉर्डिंग शुरू करें।",
    checkReceipt: "निजी रसीद जांचें",
    startAgain: "फिर से शुरू करें",
    cannotReadSaved: "यह ब्राउज़र सेव किया गया अनुरोध नहीं पढ़ सका। कोई बिल्ड नहीं भेजा गया। स्थानीय स्टोरेज की अनुमति दें और फिर कोशिश करें।",
    cannotSaveNew: "यह ब्राउज़र नया अनुरोध सेव नहीं कर सका। कोई बिल्ड नहीं भेजा गया। स्थानीय स्टोरेज की अनुमति दें और फिर कोशिश करें।",
    changedInAnotherTab: "यह रिकॉर्डिंग अनुरोध किसी और टैब में बदल गया। फिर चुनने से पहले रीलोड करें।",
    couldNotCheckRecording: "यह रिकॉर्डिंग जांची नहीं जा सकी। आपका सेव किया गया अनुरोध रखा गया है।",
    notEligibleForNewRequest: "यह सेव की गई रिकॉर्डिंग नए अनुरोध के लिए उपलब्ध नहीं है। फिर कोशिश करने से पहले इसकी स्थिति ताज़ा करें।",
  },
  verification: {
    chooseWhetherToUse: "चुनें कि इस सेव की गई रिकॉर्डिंग का इस्तेमाल करना है या नहीं।",
    couldNotBuild: "यह सटीक रिकॉर्डिंग नहीं बन सकी।",
    needsNewConfirmation: "इस पुराने अनुरोध को नई पुष्टि चाहिए। आपकी सेव की गई रिकॉर्डिंग अभी भी उपलब्ध है।",
    confirmToReplace: "आपकी चुनी गई रिकॉर्डिंग बदल गई है। तभी पुष्टि करें जब आप चाहें कि यह सेव की गई रिकॉर्डिंग उस चुनाव की जगह ले।",
    buildStoppedOurSide: "निजी बिल्ड हमारी तरफ़ से रुक गई।",
    checkingUnavailable: "इस सेव की गई रिकॉर्डिंग की जांच यहां उपलब्ध नहीं है। आपका पिछला अनुरोध रखा गया है।",
    checkingRecording: "रिकॉर्डिंग जांची जा रही है",
    useThisRecording: "यह रिकॉर्डिंग इस्तेमाल करें",
    recordAgain: "फिर रिकॉर्ड करें",
    actionNeeded: "एक कार्रवाई ज़रूरी है",
    stepStopped: "यह चरण रुक गया",
    checking: "जांचा जा रहा है",
    backToKnowledge: "जानकारी पर लौटें",
    platformPendingHeading: "आवाज़ की पुष्टि अभी उपलब्ध नहीं है।",
    platformPendingBody: "आपकी रिकॉर्डिंग सुरक्षित है। आवाज़ की पुष्टि हमारी ओर से रुकी है। निजी टेक्स्ट ड्राफ्ट तैयार करने के लिए जानकारी पर लौटें।",
    platformPendingReadyBody: "आपकी रिकॉर्डिंग सुरक्षित है। आवाज़ की पुष्टि हमारी ओर से रुकी है। अभी निजी टेक्स्ट ड्राफ्ट आज़माएँ।",
    testPrivateDraft: "निजी ड्राफ्ट आज़माएँ",
  },
  rooms: {
    voice: {
      headingTemplate: "{name} से मिलें।",
      body: "एक सवाल पूछें या आवाज़ का नमूना सुनें।",
      meetExperienceAria: "मिलने का अनुभव",
      conversation: "बातचीत",
      voiceSample: "आवाज़",
      privateDraftTest: "ड्राफ्ट",
      listeningTest: "सुनें",
      openingListeningTest: "लिसनिंग टेस्ट खुल रहा है",
      lookingForSamples: "तुलना के लिए दो सेव की गई आवाज़ के नमूने खोजे जा रहे हैं।",
      needTwoSamples: "लिसनिंग टेस्ट चलाने से पहले आपको दो सेव की गई आवाज़ के नमूने चाहिए।",
      couldNotOpen: "हम लिसनिंग टेस्ट नहीं खोल सके। कुछ भी रिकॉर्ड नहीं हुआ।",
      close: "बंद करें",
      openingConversation: "बातचीत खुल रही है",
    },
    share: { backToKnowledge: "जानकारी पर लौटें", openingSharing: "शेयरिंग खुल रही है" },
    enrich: {
      backToVoice: "आवाज़ पर लौटें",
      heading: "अपने बारे में और जोड़ें।",
      body: "एक चीज़ चुनें। हर टिकाऊ बदलाव तब तक सुझाव रहता है जब तक आप उसे स्वीकार न करें।",
      shareKnowledgeTitle: "अपनी जानकारी शेयर करें",
      shareKnowledgeNote: "सिर्फ़-टेक्स्ट लिंक के लिए सामग्री की समीक्षा करें",
      testDraftTitle: "एक निजी ड्राफ्ट टेस्ट करें",
      testDraftNote: "आपके सेव किए गए सोर्स से एक टेक्स्ट जवाब",
      describeMeTitle: "मुझे बताएं",
      describeMeNote: "सहज तरीके से लिखें",
      whoYouAreTitle: "आप कौन हैं",
      whoYouAreNote: "पहचान, मूल्य, और आप कैसे बोलते हैं",
      sourcesTitle: "आपके सोर्स",
      sourcesNote: "देखें कि आपने क्या जोड़ा है और उसे सुरक्षित रूप से हटाएं",
      filesTitle: "फ़ाइलें, तस्वीरें, लिंक",
      filesNote: "निजी कॉन्टेक्स्ट जोड़ें",
      videoTitle: "YouTube या वीडियो",
      videoNote: "अपनी खुद की सामग्री लाएं",
      improveVoiceTitle: "मेरी आवाज़ बेहतर करें",
      improveVoiceNote: "एक मज़बूत रिकॉर्डिंग जोड़ें",
      vibeTitle: "आपका अंदाज़",
      vibeNote: "गर्मजोशी, ऊर्जा, हास्य, सीधापन, औपचारिकता",
      backToChoices: "चुनावों पर लौटें",
      recordInstead: "इसके बजाय मेरी आवाज़ रिकॉर्ड करें",
      reviewTextSharing: "टेक्स्ट शेयरिंग की समीक्षा करें",
      openingWhoYouAre: "आप कौन हैं खुल रहा है",
      openingSources: "आपके सोर्स खुल रहे हैं",
    },
    evolve: { heading: "चुनें कि आप क्या बनते हैं।", body: "जब तक आप उद्धृत सुझाव स्वीकार न करें, AI नहीं बदलता।", openingHistory: "आपका विकास इतिहास खुल रहा है" },
    emotionos: { openingVibe: "आपका अंदाज़ खुल रहा है" },
    call: { headingTemplate: "{name} से बात करें।", body: "कॉल यादें और भाषा की आदतें सुझा सकती हैं। आप तय करते हैं कि क्या रहेगा।", openingCallRoom: "निजी कॉल रूम खुल रहा है" },
  },
};

// WS-R164 (wave twenty-two). `copy.ts#FirstFiveMinutesCopy`'s own closed
// block, restated here as its own block per the same rule.
const HI_FIRST_FIVE_MINUTES: FirstFiveMinutesCopy = {
  railLabel: "आपका AI शुरू हो रहा है",
  signInTitle: "साइन इन करें",
  firstSourceTitle: "सिखाएँ",
  firstSourceHint: "रिकॉर्डिंग, फ़ाइल या कुछ शब्द जोड़ें।",
  meetTitle: "इससे मिलें",
  meetHint: "आपका AI तैयार हो रहा है। तब तक और सामग्री जोड़ सकते हैं।",
  stepDoneLabel: "हो गया",
};

const HI_SOURCES_STUDIO: SourcesStudioCopy = {
  title: "आपके सोर्स",
  intro: "आपने अपने AI को जो कुछ दिया है, उसकी मौजूदा स्थिति और उससे मिला योगदान यहां देखें।",
  countOne: "1 सोर्स",
  countManyTemplate: "{count} सोर्स",
  loading: "आपके सोर्स लोड हो रहे हैं",
  emptyTitle: "अभी कोई सोर्स नहीं है",
  emptyBody: "अपनी आवाज़ रिकॉर्ड करें, फ़ाइल जोड़ें, या लिंक शेयर करें। वह यहां दिखाई देगा।",
  loadError: "हम आपके सोर्स लोड नहीं कर सके। कुछ भी बदला नहीं गया।",
  retry: "फिर कोशिश करें",
  addedOnTemplate: "{date} को जोड़ा गया",
  kind: { recording: "रिकॉर्डिंग", file: "फ़ाइल", link: "लिंक", call: "कॉल का हिस्सा" },
  unnamed: { recording: "आवाज़ की रिकॉर्डिंग", file: "निजी फ़ाइल", link: "निजी लिंक", call: "कॉल का हिस्सा" },
  states: {
    pending_upload: "अपलोड का इंतज़ार", uploaded: "अपलोड हो गया", quarantined: "जांच हो रही है",
    processing: "सीख रहा है", ready: "तैयार", rejected: "इस्तेमाल नहीं हो सका", received: "मिल गया",
    extracted: "टेक्स्ट निकाला गया", mined: "समीक्षा हो गई", refused: "इस्तेमाल नहीं हो सका", routed: "समीक्षा के लिए भेजा गया",
  },
  statusUnavailable: "स्थिति उपलब्ध नहीं है",
  detailCodeTemplate: "सर्वर ने यह कोड दिया: {code}",
  thirdPartyDeclaration: "आपने बताया था कि इसमें दूसरे लोग शामिल हैं।",
  acceptedDetails: "स्वीकार किए गए विवरण",
  draftDetails: "ड्राफ्ट विवरण",
  voiceTime: "आवाज़ का समय",
  noYield: "अभी कोई सेव किया गया योगदान नहीं",
  secondsTemplate: "{count} सेकंड",
  minutesTemplate: "{minutes} मिनट {seconds} सेकंड",
  remove: "हटाएं",
  dialogTitle: "यह सोर्स हटाएं?",
  dialogBody: "हम यह सोर्स और इसका हवाला देने वाला हर सक्रिय विवरण हटा देंगे। इसे वापस नहीं लाया जा सकता।",
  impactLoading: "जांच रहे हैं कि क्या हटेगा",
  impactError: "हम असर की पुष्टि नहीं कर सके। हटाने का विकल्प बंद रहेगा।",
  impactAcceptedTemplate: "{count} स्वीकार किए गए विवरण",
  impactDraftTemplate: "{count} ड्राफ्ट विवरण",
  impactVoiceTemplate: "{time} की आवाज़",
  primaryVoiceWarning: "यह आपकी चुनी हुई आवाज़ का सोर्स है। दूसरी रिकॉर्डिंग चुनने तक आवाज़ का प्लेबैक रुक सकता है।",
  confirmInstructionTemplate: "पुष्टि के लिए {word} लिखें।",
  confirmWord: "हटाएं",
  confirmLabel: "पुष्टि का टेक्स्ट",
  cancel: "सोर्स रखें",
  removeForever: "हमेशा के लिए हटाएं",
  removing: "हटाया जा रहा है",
  removalError: "हटाना शुरू नहीं हुआ। आपका सोर्स अभी भी सूची में है।",
  removedComplete: "सोर्स हटा दिया गया।",
  removedPending: "हटाना शुरू हो गया। निजी स्टोरेज की सफ़ाई अभी चल रही है।",
  rebuildRequired: "इस सोर्स के बिना आपके AI को फिर से बनाना होगा।",
};

// `personalAuth` is deliberately absent here: `copy.ts#loadStudioCopy`
// installs it separately from `personalAuthCopyRegistry.ts`'s own already-lazy
// Hindi loader, so this file owns only the sections named above.
export const HI_STUDIO_COPY: Omit<StudioCopy, "personalAuth"> = {
  expertSharePanel: HI_EXPERT_SHARE_PANEL,
  quickVoiceCapture: HI_QUICK_VOICE_CAPTURE,
  expertConversation: HI_EXPERT_CONVERSATION,
  personModelStudio: HI_PERSON_MODEL_STUDIO,
  meetMemory: HI_MEET_MEMORY,
  cloneVerificationJourney: HI_CLONE_VERIFICATION_JOURNEY,
  contextLockerPanel: HI_CONTEXT_LOCKER_PANEL,
  voicePreviewPanel: HI_VOICE_PREVIEW_PANEL,
  mirrorCallStudio: HI_MIRROR_CALL_STUDIO,
  cloneExperienceShell: HI_CLONE_EXPERIENCE_SHELL,
  firstFiveMinutes: HI_FIRST_FIVE_MINUTES,
  sourcesStudio: HI_SOURCES_STUDIO,
};
