// src/studio/hiCopy.ts — WS-R159. The personal studio's Hindi table, its own
// chunk (loaded only by `copy.ts#loadStudioCopy("hi")`), the same shape
// `src/creatorStudio/hiCopy.ts` and `src/studio/hiPersonalAuthCopy.ts`
// already establish. `personModelStudio` below reuses
// `src/creatorStudio/hiCopy.ts#personModelStudio` (WS-R61)'s own
// already-reviewed wording wherever this file's English matches it, adapting
// only where this screen's own English differs (the nearline nearline-busy
// states this file's English adds, and one extra extraction blocker key).
import type { ExpertConversationCopy, ExpertSharePanelCopy, MeetMemoryCopy, PersonModelStudioCopy, QuickVoiceCaptureCopy, StudioCopy } from "./copy";

const HI_EXPERT_SHARE_PANEL: ExpertSharePanelCopy = {
  title: "अपने AI को एक ठिकाना दें।",
  voiceOtherChannelsSummary: "आवाज़ और अन्य चैनल",
  voiceOtherChannelsNote: "शेयर करने से पहले इनकी अपनी अलग पुष्टि ज़रूरी है।",
  reviewReadiness: "तैयारी की समीक्षा करें",
};

const HI_QUICK_VOICE_CAPTURE: QuickVoiceCaptureCopy = {
  recommendedEyebrow: "सुझाया गया",
  heading: "एक साफ़ आवाज़ का नमूना रिकॉर्ड करें",
  instructionsOne: "किसी भी विषय पर सहज होकर बोलें। 12 सेकंड के बाद, एक टैप रिकॉर्डिंग खत्म करता है और आपका AI शुरू करता है।",
  instructionsTwo: "करीब 30 सेकंड में साफ़ बोली के ज़्यादा हिस्से चुनने का मौका मिलता है। हम इसे निजी रखते हैं।",
  localUntilUpload: "अपलोड करने तक सिर्फ़ आपके डिवाइस पर",
  languageGroupAriaLabel: "रिकॉर्डिंग की भाषा",
  promptSummary: "कोई विचार चाहिए? एक वैकल्पिक सुझाव देखें",
  promptHint: "यह पढ़ना ज़रूरी नहीं है। आपके अपने सहज शब्द बेहतर हैं।",
  startRecording: "रिकॉर्डिंग शुरू करें",
  micPermissionNote: "आपका ब्राउज़र माइक्रोफ़ोन की अनुमति इसी क्लिक के बाद मांगेगा।",
  openingMic: "आपका माइक्रोफ़ोन खोला जा रहा है",
  checkPermissionPrompt: "ब्राउज़र की अनुमति वाला संदेश देखें।",
  recordingVisuallyHidden: "रिकॉर्डिंग शुरू हो गई है। 12 सेकंड बाद खत्म करना और बनाना उपलब्ध होगा।",
  recordingLabel: "रिकॉर्डिंग हो रही है",
  ofMaxTemplate: "{time}, अधिकतम 1:00 में से",
  speakMoreTemplate: "{n} सेकंड और बोलें",
  finishAndBuild: "खत्म करें और बनाएं",
  meterAriaLabel: "माइक्रोफ़ोन का लाइव इनपुट स्तर",
  keepSpeakingTemplate: "{n} सेकंड और बोलते रहें",
  goodKeepGoing: "अच्छा है। बेहतर विकल्प के लिए जारी रखें।",
  targetReached: "लक्ष्य पूरा हुआ। जब यह वाक्य पूरा लगे, तब रुक जाएं।",
  progressAriaLabel: "सुझाई गई रिकॉर्डिंग लंबाई",
  improveSampleHeading: "चलिए इस नमूने को बेहतर बनाते हैं",
  durationFormatTemplate: "{duration} · 24 kHz निजी WAV",
  retakeNeeded: "फिर से रिकॉर्ड करना ज़रूरी",
  levelTooHigh: "आवाज़ का स्तर ज़्यादा हो सकता है। माइक्रोफ़ोन से थोड़ा दूर होकर फिर से रिकॉर्ड करें।",
  quietRecording: "इस रिकॉर्डिंग का ज़्यादातर हिस्सा धीमा है। माइक्रोफ़ोन के पास होकर फिर से रिकॉर्ड करें।",
  usableLevel: "स्थानीय इनपुट स्तर काम लायक लगता है। अंतिम चुनाव निजी प्रोसेसिंग करती है।",
  notEnoughYet: "कम से कम 12 सेकंड बोलें। करीब 30 सेकंड में प्रोसेसिंग को साफ़ बोली के ज़्यादा हिस्से चुनने का मौका मिलता है।",
  recordAgain: "फिर से रिकॉर्ड करें",
  errorTooShort: "यह नमूना बहुत छोटा है। कम से कम 12 सेकंड बोलें।",
  errorClipped: "माइक्रोफ़ोन का स्तर सीमा पार कर गया। थोड़ा दूर होकर एक बार फिर रिकॉर्ड करें।",
  errorTooQuiet: "इस नमूने का ज़्यादातर हिस्सा धीमा है। पास आकर एक बार फिर रिकॉर्ड करें।",
  errorFinishFailed: "रिकॉर्डिंग खत्म नहीं हो सकी।",
  errorStartFailed: "ब्राउज़र रिकॉर्डिंग शुरू नहीं कर सका।",
  errorCloseMicFailed: "माइक्रोफ़ोन बंद नहीं हो सका।",
};

const HI_EXPERT_CONVERSATION: ExpertConversationCopy = {
  ariaLabel: "निजी विशेषज्ञ बातचीत",
  statusActive: "निजी बातचीत",
  statusInactive: "निजी वर्कस्पेस",
  aiReviewedByYou: "AI, आपके द्वारा समीक्षित",
  continuityAudioNote: "पुरानी बातचीत वाले जवाबों में ऑडियो उपलब्ध नहीं है।",
  readinessTitle: {
    stopped: "यह AI रुका हुआ है",
    reconciling: "जवाब सेव हो गया",
    checking: "आपका AI जांचा जा रहा है",
    privateUnavailable: "आपका निजी वर्शन उपलब्ध नहीं है",
    unavailable: "तैयारी की जानकारी उपलब्ध नहीं है",
    setup: "अपनी पहली बातचीत शुरू करें",
  },
  readinessBody: {
    stopped: "इस AI के लिए निजी जवाब उपलब्ध नहीं हैं।",
    reconciling: "अगला जवाब शुरू होने से पहले हम इस्तेमाल की जांच कर रहे हैं।",
    checking: "मौजूदा सर्वर स्थिति जांची जा रही है।",
    privateUnavailable: "हम चुना गया निजी वर्शन लोड नहीं कर सके। इसे ठीक करते समय फिर से जांचें।",
    unavailable: "हम बातचीत की तैयारी जांच नहीं सके। फिर कोशिश करें।",
    setup: "निजी जवाब शुरू होने से पहले जो ज़रूरी है, वह जांचें।",
  },
  openConversationSetup: "बातचीत की सेटअप खोलें",
  checkAgain: "फिर जांचें",
  newConversation: "नई बातचीत",
  retryOpeningConversation: "बातचीत खोलने की फिर कोशिश करें",
  openingConversation: "बातचीत खुल रही है",
  checkConversation: "बातचीत जांचें",
  recentCompletedReplies: "हाल के पूरे हुए जवाब",
  runtimeChangedNotice: "आपका निजी वर्शन बदल गया है। पिछला जवाब जांचने के बाद नई बातचीत शुरू करें।",
  historyPendingNotice: "हम पिछले जवाब और उसके इस्तेमाल की जांच कर रहे हैं। फिर भेजने से पहले बातचीत जांचें।",
  historyUnconfirmedNotice: "पिछले जवाब की पुष्टि नहीं हो सकी। इस बातचीत को जांचें, या साफ़ तौर पर एक नई बातचीत शुरू करें। हमने आपका संदेश दोबारा नहीं भेजा है।",
  emptyHeading: "एक असली सवाल आज़माएं।",
  emptyBody: "वह पूछें जो कोई क्लाइंट आपसे पूछता। सुनें, फिर अपने AI को दिखाएं कि आप क्या बदलेंगे।",
  emptyStarterButton: "किसी की शुरुआत में मदद करें",
  emptyStarterQuestion: "मेरे काम में नए किसी व्यक्ति को आप सबसे पहला कदम क्या सुझाएंगे?",
  youLabel: "आप",
  yourAiLabel: "आपका AI",
  stopAudio: "ऑडियो रोकें",
  listen: "सुनें",
  teachCorrection: "सुधार सिखाएं",
  workingStatus: "आपका AI जवाब तैयार कर रहा है",
  recallPreviousLabel: "पहले की निजी बातचीत इस्तेमाल करें",
  askYourAi: "अपने AI से पूछें",
  questionPlaceholder: "अपने काम से जुड़ा एक सवाल लाएं",
  privateToThisRelationship: "इस रिश्ते तक सीमित निजी",
  answering: "जवाब दिया जा रहा है",
  send: "भेजें",
  errorRecovered: "आपका सेव किया गया जवाब वापस मिल गया है।",
  errorConversationUnavailable: "पिछली बातचीत उपलब्ध नहीं है। आप साफ़ तौर पर एक नई बातचीत शुरू कर सकते हैं।",
  errorRestoreFailed: "हम इस बातचीत को वापस नहीं ला सके। अगला संदेश भेजने से पहले फिर जांचें।",
  errorOpenFailed: "बातचीत खोलने की पुष्टि नहीं हो सकी। वही बातचीत जांचने के लिए फिर कोशिश करें।",
  errorReplyFailed: "आपका AI यह जवाब पूरा नहीं कर सका। आपका संदेश अभी भी यहां है। हमने इसे अपने आप फिर से नहीं भेजा है।",
  errorReplySavedNeedsReconcile: "आपका जवाब सेव हो गया है। अगले जवाब से पहले हमें इसका इस्तेमाल तय करना होगा।",
  errorAudioPlaybackFailed: "यह ऑडियो नहीं चल सका। फिर सुनने की कोशिश करें।",
  errorVoiceUnavailable: "आवाज़ में सुनना उपलब्ध नहीं है। लिखा हुआ जवाब अभी भी यहां है।",
};

const HI_PERSON_MODEL_STUDIO: PersonModelStudioCopy = {
  blockers: {
    self_name_required: "वह नाम पुष्ट करें जो आपका AI खुद के लिए इस्तेमाल करता है",
    language_identity_required: "इसकी भाषा और कोड-स्विचिंग पहचान पुष्ट करें",
    behavior_evidence_required: "कम से कम एक व्यवहार या सुधार पैटर्न देखें",
    boundary_evidence_required: "कम से कम एक निजी सीमा पुष्ट करें",
    critical_identity_conflict: "टकराते हुए पहचान दावे सुलझाएं",
  },
  extractionBlockers: {
    transcription_consent_required: "ट्रांसक्रिप्शन की अनुमति दें",
    training_consent_required: "सहायता प्राप्त दावा निष्कर्षण के लिए AI-निर्माण अनुमति दें",
    reviewed_subject_transcript_required: "कम से कम एक सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें",
    reviewed_confident_subject_transcript_required: "कम से कम एक भरोसेमंद, सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें",
    reviewed_confident_subject_evidence_required: "एक भरोसेमंद सत्यापित स्पीकर ट्रांसक्रिप्ट स्वीकार करें, या अपलोड किए गए दस्तावेज़ को अपना लिखा हुआ बताएं",
  },
  confidencePctTemplate: "{n}% विश्वास",
  fromYourSource: "आपके सोर्स से:",
  citedSourceOne: "{n} उद्धृत सोर्स",
  citedSourceMany: "{n} उद्धृत सोर्स",
  keepOut: "बाहर रखें",
  notAccurate: "सही नहीं है",
  outdated: "पुराना",
  thisIsMe: "यह मैं हूं",
  reviewClaimAriaLabel: "इस दावे की समीक्षा करें",
  eyebrow: "हमने आपके बारे में क्या सीखा",
  title: "हमें जो लगता है हमने आपके बारे में सीखा, एक-एक दावे के रूप में",
  intro: "पहचान, भाषा, व्यवहार, मूल्य, सीमाएं, और आत्मकथा को अलग-अलग सबूत-आधारित दावों के रूप में पुष्ट करें। टकराव छिपाए नहीं जाते, एक भरोसेमंद कल्पना में औसत नहीं किए जाते।",
  noApprovedVersion: "अभी मंज़ूर नहीं",
  approvedVersionLabel: "मंज़ूर वर्शन",
  loadingClaims: "समीक्षा किए गए दावे लोड हो रहे हैं…",
  retry: "फिर कोशिश करें",
  proposedClaims: "प्रस्तावित दावे",
  accepted: "स्वीकृत",
  criticalConflicts: "गंभीर टकराव",
  citedExtractionEyebrow: "उद्धृत निष्कर्षण",
  citedExtractionTitle: "अपनी समीक्षा की गई रिकॉर्डिंग को अपने नियंत्रण वाले दावों में बदलें",
  citedExtractionIntro: "सिर्फ़ स्वीकृत लक्षित-स्पीकर ट्रांसक्रिप्ट हिस्से ही योग्य हैं। कच्चे ट्रांसक्रिप्ट सिर्फ़ सर्वर पर रहते हैं, सीधी पहचान निष्कर्षण कॉल से पहले छिपाई जाती है, और हर नतीजा तब तक सिर्फ़ एक प्रस्ताव रहता है जब तक आप उसे नीचे न देख लें।",
  eligibleSpans: "योग्य हिस्से",
  lastProposed: "पिछली बार प्रस्तावित",
  noExtractionRunYet: "अभी कोई निष्कर्षण नहीं हुआ",
  observedRangeLabel: "देखी गई सीमा",
  nextCheckLabel: "अगली जांच",
  leaveOrReturnLabel: "छोड़ें या लौटें",
  checkStatusNow: "अभी स्थिति जांचें",
  submittingExtraction: "निष्कर्षण भेजा जा रहा है...",
  extractionRunning: "निष्कर्षण चल रहा है",
  waitingToRetry: "फिर कोशिश का इंतज़ार",
  extractionQueued: "निष्कर्षण कतार में है",
  extractNewEvidence: "नया सबूत निकालें",
  extractCitedClaims: "उद्धृत दावे निकालें",
  noClaimsHeadline: "अभी कोई व्यवहार या याददाश्त वाला दावा नहीं है।",
  noClaimsNote: "प्रोसेस किया गया सबूत यहां समीक्षा के लिए दिखेगा। कच्चे ट्रांसक्रिप्ट, वेक्टर, और स्टोरेज पाथ रोके रहते हैं।",
  buildIsDeterministicNote: "एक बिल्ड निश्चित और वर्शन वाला होता है। इसे मंज़ूर करना कभी इन्फ़रेंस या आवाज़ बनाने की अनुमति नहीं देता।",
  checkingEvidence: "सबूत जांचा जा रहा है…",
  approveProfileVersionTemplate: "प्रोफ़ाइल v{n} मंज़ूर करें",
  building: "बनाया जा रहा है…",
  buildReviewDraft: "समीक्षा ड्राफ्ट बनाएं",
  errorLoadFailed: "हमने आपके बारे में जो सीखा वह लोड नहीं हो सका",
  errorExtractionUnavailable: "उद्धृत निष्कर्षण की स्थिति लोड नहीं हो सकी",
  errorProfileUnavailable: "हमने आपके बारे में जो सीखा उसकी पुष्टि नहीं हो सकी। फिर कोशिश करें।",
  errorClaimNotSaved: "दावे की समीक्षा सेव नहीं हुई",
  errorBuildRefused: "हमने आपके बारे में जो सीखा उसे बनाना अस्वीकार हुआ",
  errorApproveChanged: "प्रोफ़ाइल बदल गई और मंज़ूर नहीं हो सकी",
  errorExtractionFailed: "उद्धृत दावे नहीं निकाले जा सके",
  errorExtractionScopeChanged: "निष्कर्षण का दायरा बदल गया",
  errorExtractionCheckFailed: "निष्कर्षण की स्थिति की पुष्टि नहीं हो सकी। फिर कोशिश करें।",
  errorExtractionCheckFailedRetryable: "नवीनतम स्थायी निष्कर्षण स्थिति जांची नहीं जा सकी। सर्वर पर काम अभी भी जारी हो सकता है; यह पेज दोबारा जुड़ने या रीलोड होने के बाद फिर कोशिश करेगा।",
};

// WS-R167 (own closed block, appended). "It remembers" — see
// src/studio/copy.ts's MeetMemoryCopy for the full rationale.
const HI_MEET_MEMORY: MeetMemoryCopy = {
  heading: "यह याद रखता है",
  onDescription: "आपका AI यहां जो कहते हैं उसे याद रखता है, ताकि जांचना हर बार नए सिरे से शुरू करने के बजाय एक चलती हुई बातचीत जैसा लगे।",
  offDescription: "याददाश्त बंद है। हर बातचीत नए सिरे से शुरू होती है, और यहां जो कहा जाता है वह बाद में नहीं रखा जाता।",
  toggleOn: "याददाश्त चालू करें",
  toggleOff: "याददाश्त बंद करें",
  factsHeading: "यह क्या याद रखता है",
  factsEmpty: "अभी कुछ याद नहीं है।",
  correctAction: "इसे सुधारें",
  forgetAction: "इसे भुलाएं",
  correctPromptLabel: "इसे बदले में क्या याद रखना चाहिए?",
  correctPlaceholder: "इसे ठीक वैसे कहें जैसे आप चाहते हैं कि यह याद रहे",
  correctSave: "सुधार सेव करें",
  correctCancel: "रद्द करें",
  classificationUnconfirmed: "अभी वर्गीकृत नहीं",
  howWeAreHeading: "हम कैसे हैं",
  startFreshAction: "नए सिरे से शुरू करें",
  startFreshConfirm: "यह आपके और आपके AI के बीच अभी जो भी खुला है उसे बंद करता है, जो हुआ उसे मिटाए बिना।",
  startFreshNothingOpen: "अभी कुछ भी खुला नहीं है।",
  startFreshDone: "नए सिरे से शुरू हो गया।",
  errorStatusUnavailable: "हम जांच नहीं सके कि याददाश्त चालू है या नहीं।",
  errorToggleFailed: "यह सेव नहीं हो सका। फिर कोशिश करें।",
  errorFactsUnavailable: "यह क्या याद रखता है, लोड नहीं हो सका।",
  errorCorrectFailed: "वह सुधार सेव नहीं हुआ।",
  errorForgetFailed: "अभी वह भुलाया नहीं जा सका।",
};

// `personalAuth` is deliberately absent here: `copy.ts#loadStudioCopy`
// installs it separately from `personalAuthCopyRegistry.ts`'s own already-lazy
// Hindi loader, so this file owns only the sections named above.
export const HI_STUDIO_COPY: Omit<StudioCopy, "personalAuth"> = {
  expertSharePanel: HI_EXPERT_SHARE_PANEL,
  quickVoiceCapture: HI_QUICK_VOICE_CAPTURE,
  expertConversation: HI_EXPERT_CONVERSATION,
  personModelStudio: HI_PERSON_MODEL_STUDIO,
  meetMemory: HI_MEET_MEMORY,
};
