import type { PersonalAuthCopy } from "./personalAuthCopy";

export const HI_PERSONAL_AUTH_COPY: PersonalAuthCopy = {
  homeAriaLabel: "Vyakti होम",
  safeguardsAriaLabel: "स्टूडियो के सुरक्षा उपाय",
  privateByDefault: "शुरू से निजी",
  everyClipDisclosed: "हर क्लिप में AI की पहचान",
  deleteAnytime: "कभी भी मिटाएं",
  welcomeBackTitle: "फिर स्वागत है",
  emailTitle: "अपने ईमेल से साइन इन करें",
  inboxTitle: "अपना ईमेल देखें",
  resumeTitle: "वहीं से आगे बढ़ने के लिए फिर साइन इन करें।",
  resumeBodyTemplate: "हम आपको {name} के {step} चरण पर वापस ले जाएंगे। निजी अपलोड और सर्वर पर काम जारी हैं। सुरक्षा के लिए, बिना भेजी रिकॉर्डिंग या फ़ॉर्म में भरी जानकारी सेव नहीं होती।",
  sameClone: "आपके उसी AI",
  stepTitle: { feed: "सामग्री जोड़ें", meet: "अपना AI जांचें", deploy: "उपलब्ध कराएं" },
  emailBody: "अपने ईमेल के लिए सुरक्षित साइन-इन लिंक का अनुरोध करें।",
  inboxBodyTemplate: "{email} पर साइन-इन ईमेल देखें। अगर ईमेल पहुंचे, तो स्टूडियो खोलने के लिए उसका लिंक खोलें।",
  emailLabel: "ईमेल पता",
  emailPlaceholder: "you@example.com",
  sendingAriaLabel: "साइन-इन ईमेल भेजा जा रहा है",
  sending: "ईमेल भेजा जा रहा है",
  sendLink: "साइन-इन लिंक का अनुरोध करें",
  or: "या",
  google: "Google से जारी रखें",
  inboxHelp: "लिंक आपको स्टूडियो में वापस लाता है। दूसरे टैब में लिंक खोलने के बाद यहां लौटें।",
  checkingLink: "साइन-इन की जांच हो रही है",
  openedLink: "लिंक खोलने के बाद जारी रखें",
  optionalCodeDivider: "मेरे ईमेल में 6 अंकों का कोड है",
  codeLabel: "6 अंकों का कोड",
  codePlaceholder: "000000",
  verifyingAriaLabel: "कोड जांचा जा रहा है",
  verifying: "जांच हो रही है",
  verify: "जांचें और अंदर जाएं",
  differentEmail: "दूसरा ईमेल इस्तेमाल करें",
  linkNotReadyError: "इस टैब में अभी साइन-इन पूरा नहीं हुआ है। ईमेल का लिंक खोलकर यहां लौटें। अगर ईमेल में कोड है, तो उसे नीचे दर्ज करें।",
  sendError: "साइन-इन ईमेल का अनुरोध पूरा नहीं हुआ। थोड़ी देर बाद फिर कोशिश करें।",
  emailUnavailableError: "इस ईमेल पते के लिए साइन-इन उपलब्ध नहीं है क्योंकि अभी सभी लोगों के लिए ईमेल भेजने की व्यवस्था नहीं है। Google से जारी रखें।",
  networkError: "कनेक्शन नहीं हो पाया। अपना इंटरनेट कनेक्शन जांचें और फिर कोशिश करें।",
  rateLimitError: "साइन इन करने की बहुत कोशिशें हुई हैं। थोड़ा रुककर फिर कोशिश करें।",
  serviceUnavailableError: "अभी साइन-इन सेवा उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें।",
  invalidEmailError: "सही ईमेल पता दर्ज करें।",
  codeMismatchError: "यह कोड मेल नहीं खाया। जांचें और फिर कोशिश करें।",
  googleError: "Google साइन-इन उपलब्ध नहीं है। इसकी जगह अपना ईमेल इस्तेमाल करें।",
  workspaceLoadError: "आपका स्टूडियो खुल नहीं सका। आपका साइन-इन अभी भी सुरक्षित है। फिर खोलने के लिए दोबारा कोशिश करें।",
  retryWorkspace: "फिर कोशिश करें",
  legalNotice: "साइन इन के बाद आप चुनेंगे कि आपका AI क्या इस्तेमाल कर सकता है।",
  visualAlt: "मोती जैसे हल्के रंग की मेज पर खुली नोटबुक, ग्रेफाइट पेन और चांदी का माइक्रोफ़ोन",
  visualCaptions: { knowledge: "आपका ज्ञान।", voice: "आपकी आवाज़।", people: "आपके लोग।" },
  variant: {
    generic: { brandTag: "आपका निजी AI", introEyebrow: "", introTitle: "आपकी विशेषज्ञता। आपका अपना अंदाज़।", introBody: "अपने ज्ञान और आवाज़ वाला AI बनाएं, जो हर व्यक्ति से हुई बातों को याद रखे।" },
    teacher: { brandTag: "आपका निजी AI", introEyebrow: "", introTitle: "आपकी विशेषज्ञता। आपका अपना अंदाज़।", introBody: "अपने ज्ञान और आवाज़ वाला AI बनाएं, जो हर व्यक्ति से हुई बातों को याद रखे।" },
    test: { brandTag: "आंतरिक टेस्ट स्टूडियो", introEyebrow: "", introTitle: "अपनी सामग्री जोड़ें। फिर अपना AI जांचें।", introBody: "अपनी आवाज़, लेखन, वीडियो और संदर्भ के काम के उदाहरण अपलोड करें। फिर शुरुआती रूप सुनें, उससे बात करें और उसे ठीक करें।" },
  },
};
