import type { PersonalAuthCopy } from "./personalAuthCopy";

export const HI_PERSONAL_AUTH_COPY: PersonalAuthCopy = {
  homeAriaLabel: "Vyakti होम",
  safeguardsAriaLabel: "स्टूडियो के सुरक्षा उपाय",
  privateByDefault: "शुरू से निजी",
  everyClipDisclosed: "हर क्लिप में AI की पहचान",
  deleteAnytime: "कभी भी मिटाएं",
  welcomeBackTitle: "फिर स्वागत है",
  emailTitle: "अपने ईमेल से शुरू करें",
  inboxTitle: "अपना इनबॉक्स देखें",
  resumeTitle: "वहीं से आगे बढ़ने के लिए फिर साइन इन करें।",
  resumeBodyTemplate: "हम आपको {name} के {step} चरण पर वापस ले जाएंगे। निजी अपलोड और सर्वर पर काम जारी हैं। सुरक्षा के लिए, बिना भेजी रिकॉर्डिंग या फ़ॉर्म में भरी जानकारी सेव नहीं होती।",
  sameClone: "आपके उसी AI",
  stepTitle: { feed: "सामग्री जोड़ें", meet: "अपना AI जांचें", deploy: "उपलब्ध कराएं" },
  emailBody: "साइन इन करने का सुरक्षित लिंक अपने ईमेल पर पाएं।",
  inboxBodyTemplate: "हमने {email} पर साइन-इन ईमेल भेजा है। उसमें दिया लिंक खोलें। अगर ईमेल में 6 अंकों का कोड भी हो, तो उसे नीचे दर्ज कर सकते हैं।",
  emailLabel: "ईमेल पता",
  emailPlaceholder: "you@example.com",
  sendingAriaLabel: "साइन-इन ईमेल भेजा जा रहा है",
  sending: "ईमेल भेजा जा रहा है",
  sendLink: "साइन-इन लिंक भेजें",
  or: "या",
  google: "Google से जारी रखें",
  inboxHelp: "ईमेल का लिंक सीधे स्टूडियो खोलता है। दूसरे टैब में साइन इन पूरा होने पर यह टैब भी आगे बढ़ जाएगा।",
  checkingLink: "साइन-इन की जांच हो रही है",
  openedLink: "मैंने ईमेल का लिंक खोल लिया",
  optionalCodeDivider: "या कोड मिला हो तो दर्ज करें",
  codeLabel: "6 अंकों का कोड (वैकल्पिक)",
  codePlaceholder: "000000",
  verifyingAriaLabel: "कोड जांचा जा रहा है",
  verifying: "जांच हो रही है",
  verify: "जांचें और अंदर जाएं",
  differentEmail: "दूसरा ईमेल इस्तेमाल करें",
  linkNotReadyError: "इस टैब में अभी साइन-इन पूरा नहीं हुआ है। ईमेल का लिंक खोलें, या ईमेल में कोड मिला हो तो दर्ज करें।",
  sendError: "साइन-इन ईमेल नहीं भेजा जा सका। थोड़ी देर बाद फिर कोशिश करें।",
  networkError: "कनेक्शन नहीं हो पाया। अपना इंटरनेट कनेक्शन जांचें और फिर कोशिश करें।",
  rateLimitError: "साइन इन करने की बहुत कोशिशें हुई हैं। थोड़ा रुककर फिर कोशिश करें।",
  serviceUnavailableError: "अभी साइन-इन सेवा उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें।",
  invalidEmailError: "सही ईमेल पता दर्ज करें।",
  codeMismatchError: "यह कोड मेल नहीं खाया। जांचें और फिर कोशिश करें।",
  googleError: "Google साइन-इन उपलब्ध नहीं है। इसकी जगह अपना ईमेल इस्तेमाल करें।",
  workspaceLoadError: "आपका स्टूडियो खुल नहीं सका। आपका साइन-इन अभी भी सुरक्षित है। फिर खोलने के लिए दोबारा कोशिश करें।",
  retryWorkspace: "फिर कोशिश करें",
  legalNotice: "साइन इन के बाद आप चुनेंगे कि आपका AI क्या इस्तेमाल कर सकता है।",
  visualAlt: "हल्की चांदी जैसी रोशनी में चमकते घुमावदार कांच के पैनल",
  visualCaptions: { knowledge: "आपका ज्ञान।", voice: "आपकी आवाज़।", people: "आपके लोग।" },
  variant: {
    generic: { brandTag: "आपका निजी AI", introEyebrow: "", introTitle: "आपकी विशेषज्ञता। आपका अपना अंदाज़।", introBody: "अपने ज्ञान और आवाज़ वाला AI बनाएं, जो हर व्यक्ति से हुई बातों को याद रखे।" },
    teacher: { brandTag: "आपका निजी AI", introEyebrow: "", introTitle: "आपकी विशेषज्ञता। आपका अपना अंदाज़।", introBody: "अपने ज्ञान और आवाज़ वाला AI बनाएं, जो हर व्यक्ति से हुई बातों को याद रखे।" },
    test: { brandTag: "आंतरिक टेस्ट स्टूडियो", introEyebrow: "", introTitle: "अपनी सामग्री जोड़ें। फिर अपना AI जांचें।", introBody: "अपनी आवाज़, लेखन, वीडियो और संदर्भ के काम के उदाहरण अपलोड करें। फिर शुरुआती रूप सुनें, उससे बात करें और उसे ठीक करें।" },
  },
};
