DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
User processor
Foreground no
LogFile /tmp/clamd.log
LogTime no
LogClean no
MaxFileSize 70M
MaxScanSize 100M
StreamMaxLength 70M
ReadTimeout 180

