// Her meme collection — a few hundred Tenor search phrases she "knows",
// like any chronically-online Indian girl. The gif pipeline can fetch ANY
// search; this catalog is what keeps her vocabulary wide instead of cycling
// the same five reactions. A fresh random sample is injected into every
// prompt (memeMenu), so different turns surface different corners of it.

export const MEME_SEARCHES: string[] = [
  // ── Hera Pheri / Priyadarshan universe ──
  "hera pheri babu bhaiya",
  "paresh rawal phir se le aaya",
  "raju paisa double",
  "25 din me paisa double",
  "hera pheri yeh baburao ka style hai",
  "akshay kumar hera pheri laughing",
  "utha le re baba",
  "bhagam bhag paresh rawal",
  "dhamaal indrajeet",
  "welcome uncle majnu bhai",
  "phir hera pheri chalo",
  "hulchul laughing",
  "golmaal tusshar kapoor",
  "bol bachchan abhishek",
  "de dana dan akshay",
  "awara pagal deewana",
  // ── TMKOC ──
  "jethalal running",
  "jethalal babita ji",
  "jethalal crying",
  "daya ben garba",
  "champak chacha angry",
  "tmkoc nonsense",
  "jethalal ahahahaha",
  // ── Bollywood classic reactions ──
  "srk proud",
  "srk crying",
  "srk jai hind",
  "shahrukh khan arms open",
  "alia bhatt confused",
  "deepika crying",
  "deepika padukone laughing",
  "ranveer singh excited",
  "kareena poo main",
  "kareena kapoor eye roll",
  "jaya bachchan angry",
  "amitabh bachchan kbc confused",
  "amitabh bachchan clapping",
  "nana patekar",
  "akshay kumar confused",
  "akshay kumar clapping",
  "katrina kaif crying",
  "hrithik roshan dance",
  "govinda dance",
  "mithun dance",
  "rajinikanth style",
  "salman khan bhai",
  "aamir khan 3 idiots all izz well",
  "3 idiots chatur speech",
  "virus 3 idiots",
  "munna bhai jadoo ki jhappi",
  "circuit munna bhai",
  "sholay kitne aadmi the",
  "gabbar singh laughing",
  "basanti in dogs",
  "ddlj palat",
  "om shanti om ek chutki sindoor",
  "andaz apna apna crime master gogo",
  "andaz apna apna teja main hoon",
  "gangs of wasseypur permission",
  "faizal khan gangs of wasseypur",
  "sanjay mishra office office",
  "pankaj tripathi",
  "kader khan angry",
  "johnny lever laughing",
  "rajpal yadav chup",
  "rajpal yadav running",
  "vijay raaz kauwa biryani",
  "asrani jailer",
  "gajodhar bhaiya",
  "hera pheri devi prasad",
  // ── South cinema energy ──
  "allu arjun pushpa jhukega nahi",
  "pushpa flower nahi fire",
  "srivalli",
  "kgf yash walking",
  "bahubali katappa",
  "prabhas bahubali",
  "brahmanandam laughing",
  "brahmanandam shocked",
  "vijay thalapathy",
  "rowdy baby dance",
  "vadivelu laughing",
  "senthil goundamani",
  // ── Serials / saas-bahu drama ──
  "rasode me kaun tha",
  "kokilaben",
  "gopi bahu",
  "tulsi virani",
  "komolika entry",
  "naagin dance",
  "yeh rishta drama",
  "big boss pooja what is this behaviour",
  "sasural simar ka makkhi",
  // ── Reality TV / Shark Tank ──
  "ashneer grover bhai kya kar raha hai tu",
  "ashneer grover dogalapan",
  "aman gupta shark tank",
  "peyush bansal sasta",
  "namita thapar main out hu",
  "anupam mittal",
  "roadies raghu angry",
  "arnab goswami shouting",
  "kapil sharma laughing",
  "kapil sharma babaji ka thullu",
  "sidhu paaji thoko taali",
  "archana puran singh laughing",
  "krushna abhishek",
  "bharti singh laughing",
  // ── Creators / influencer memes ──
  "elvish yadav sigma",
  "elvish bhai",
  "puneet superstar",
  "lord puneet",
  "carryminati toh kaise hai aap log",
  "bb ki vines bancho",
  "ashish chanchlani",
  "thara bhai joginder",
  "dolly chaiwala",
  "tandoor wala baba",
  "hindustani bhau",
  "khan sir",
  "sandeep maheshwari",
  "technical guruji",
  // ── Viral moments / desi internet lore ──
  "moye moye",
  "just looking like a wow",
  "so beautiful so elegant",
  "chai pi lo frands",
  "ganji chudail",
  "bade harami ho beta",
  "aap chronology samajhiye",
  "mai samay hoon",
  "binod",
  "gormint aunty",
  "pawri ho rahi hai",
  "peela rang dekh ke",
  "khatam tata bye bye",
  "chaar baje wala",
  "friendship over",
  "ye bik gayi hai gormint",
  "jio dhan dhana dhan",
  "emotional damage",
  "adipurush jai shri ram",
  "dank indian meme",
  "desi mom slipper",
  "sharma ji ka beta",
  "rishtey mein toh hum tumhare baap",
  "toofan aa raha hai",
  "dila tod diya tune",
  "very sorry mai chahta hu",
  "hello kaun paytm karo",
  "jaake dekho na",
  "abey saale",
  "control uday control",
  "aata majhi satakli",
  "toh phir theek hai",
  "chinta mat karo",
  "kya karu main mar jau",
  "haan bhai haan",
  "nahi karna tha",
  "scam 1992 risk hai toh ishq hai",
  "harshad mehta",
  "mirzapur kaleen bhaiya",
  "munna bhaiya mirzapur",
  "guddu bhaiya",
  "panchayat sachiv ji",
  "panchayat dekh raha hai binod",
  "sacred games ganesh gaitonde",
  "kabhi kabhi lagta hai apun hi bhagwan hai",
  "family man srikant",
  "chellam sir",
  // ── Cricket ──
  "dhoni smile",
  "dhoni helicopter shot",
  "virat kohli angry",
  "virat kohli celebration",
  "rohit sharma laughing",
  "siraj crying",
  "rahul dravid angry",
  "wasim akram",
  "jasprit bumrah yorker",
  "hardik pandya",
  "india world cup celebration",
  "ben stokes bhasad",
  "ms dhoni calm",
  // ── Global staples (she's online, not just desi-online) ──
  "side eye cat",
  "crying cat thumbs up",
  "sad cat",
  "cat vibing",
  "screaming cat",
  "michael scott no",
  "michael scott thank you",
  "jim halpert look",
  "confused math lady",
  "this is fine dog",
  "drake hotline bling no yes",
  "spongebob mocking",
  "patrick star confused",
  "minion laughing",
  "skeleton waiting",
  "sad pablo escobar",
  "monkey puppet looking away",
  "shocked pikachu",
  "kermit sipping tea",
  "well well well",
  "homer disappears into bushes",
  "awkward seal",
  "eye roll gif",
  "slow clap",
  "mic drop",
  "chefs kiss",
  "facepalm",
  "popcorn eating",
  "typing furiously",
  "mind blown",
  "happy dance",
  "excited jumping",
  "peace out",
  "pretending to be shocked",
  "suspicious look",
  "judging you",
  "no words",
  "cringe",
  "run away",
  "hiding face",
  "crying laughing",
  "stop it get some help",
  "am i a joke to you",
  "it is what it is",
  "sigh gif",
  "leonardo dicaprio cheers",
  "leonardo dicaprio laughing",
  "will smith tada",
  "obama mic drop",
  "the rock eyebrow",
  "gordon ramsay idiot sandwich",
  "baby yoda sipping",
  "cat keyboard smash",
  "dog side eye",
  "hamster staring",
  "goofy ahh",
  "nail biting nervous",
  "sweating nervous",
  "chill pill",
  "love you gif",
  "virtual hug",
  "flying kiss",
  "good night gif",
  "good morning chai",
];

// a DAILY rotating sample — deterministic within a day so the system prompt
// stays byte-stable (Gemini's implicit prompt caching discounts a stable
// prefix ~75%; per-call randomness was silently disabling it), while still
// rotating corners of her collection day to day.
export function memeMenu(n = 40): string {
  // seeded shuffle (mulberry32) keyed to the calendar day
  const day = new Date().toDateString();
  let seed = 0;
  for (const c of day) seed = (seed * 31 + c.charCodeAt(0)) >>> 0;
  const rand = () => {
    seed = (seed + 0x6d2b79f5) >>> 0;
    let t = seed;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const pool = [...MEME_SEARCHES];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, n).join('", "');
}
