// The re-ingestion worker — the loop half of "stays current" (Gurukul WS-I).
//
// SPEC-GURUKUL.md §8 item 3, which is the whole specification of this file:
// "Stays-current is a loop, not an upload. Channel link → new-video detection
// → re-ingestion → PROPOSED claims/sheet deltas the expert approves — never
// silent self-update of a live persona."
//
// Per active watch: listNewVideos → captions-or-audio → transcribe →
// transcriptStats + draftFromTranscript (the wave-3 modules, reached through
// api/_engine.gen.js) → a PROPOSED delta on a `vy_ingest_run` row. Then it
// stops. A human moves it further or it never moves.
//
// ── the law this file exists to keep ─────────────────────────────────────
// NO STATEMENT IN THIS FILE NAMES `vy_teacher_sheet`. Not a write, not a
// read. That is stronger than the brief asks for and it is stronger on
// purpose: a worker that reads the published sheet in order to "compare" is
// one edit away from a worker that writes it, and the reviewer of that edit
// sees a diff to a query that was already there. evals/channel.mjs asserts
// the absence directly, over every statement the sweep issues, so the
// property is checked rather than intended.
//
// The second layer is migration 053's `vy_ingest_run_approval_gate`: a row
// cannot reach status='applied' without a named approver and a decision time.
// `applyIngestRunDelta` below is the only function in the tree that supplies
// them. The house rule for a harm the next turn does not undo is two
// independent layers, and the harm here is a clone of a real, named, living
// person changing what it says about itself because a video was uploaded.
//
// ── why the delta is ADDITIONS ONLY ──────────────────────────────────────
// The obvious richer design is to re-verify the existing phrase bank against
// each new video and propose RETIRING whatever no longer holds. It is wrong,
// and measurably so. `verifyPhraseBank`'s threshold is ≥5 occurrences in the
// held-out half; the held-out half of ONE forty-minute lecture is a few
// hundred tokens. Nearly every genuinely habitual verbalism would miss the
// threshold in nearly every single-video corpus, so a retirement lane would
// propose retiring almost the entire bank almost every week — a stream of
// confident-looking proposals generated by the size of the sample rather than
// by anything about the teacher. Retirement needs a corpus-level measurement
// across many videos; until that exists, this lane proposes only what one
// video can honestly evidence.
//
// ── fail closed per lane ─────────────────────────────────────────────────
// One video's failure is one run row with `status='failed'` and a code. It
// does not fail the watch, does not fail the sweep, and — the part that
// matters — does not advance `last_seen_video_id` past it. The cursor moves
// to the last SUCCESS and the listing is oldest-first, so the next sweep
// retries exactly the failed video and everything after it, in order.
import { randomUUID } from "node:crypto";
import { assertChannelProvider, channelWatch, ChannelError } from "./_channel/contracts.js";
import { assertAsrProvider } from "./_asr/contracts.js";
// WS-AF. Fail-soft by construction (see its own header): a report must never be
// able to break the thing it reports on, so nothing in this file branches on
// its return value.
import { recordActivity } from "./_replica-activity.js";
import { draftFromTranscript, transcriptStats } from "./_engine.gen.js";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** A jsonb ceiling, the reason api/_teacher-sheet-draft.js gives for its own:
 *  an unbounded jsonb body is an unbounded write, and a 2MB "delta" is never
 *  a delta. */
export const INGEST_DELTA_MAX_BYTES = 128 * 1024;

/** How many watches one cron tick may touch. Small, like the liveness sweep's
 *  `maxJobs: 2`: a sweep that tries to do everything on a serverless function
 *  gets killed mid-video, and a sweep killed mid-video leaves a run row in
 *  `fetched` that the next tick must reason about. Six-hourly ticks and a
 *  small batch drain a backlog within a day without any tick being long. */
export const DEFAULT_MAX_WATCHES = 3;
export const DEFAULT_MAX_VIDEOS_PER_WATCH = 5;

export class ChannelIngestError extends Error {
  constructor(code, status = 500, details) {
    super(code);
    this.code = code;
    this.status = status;
    if (details) this.details = details;
  }
}

/** Only ACTIVE watches are ever selected. `paused` and `revoked` are excluded
 *  in the WHERE clause rather than filtered in JS, which is the discipline
 *  api/_agentscope.js's measurement earns (`gate0-structural`: prompt
 *  instructions leaked 57-98%, the SQL predicate leaked 0 of 31,122). A
 *  revoked watch that reached JS could still be logged, partially rendered,
 *  or escape through a branch added later — and a revoked watch is a teacher
 *  who withdrew permission for their channel to be read. */
const DUE_WATCHES_SQL = `select watch_id, replica_id, owner_user_id, channel_url, provider,
         oauth_grant_ref, last_seen_video_id, status,
         attestation_id, backfill_state, backfill_after_video_id
    from vy_channel_watch
   where status = 'active'
   order by last_checked_at asc nulls first, created_at asc
   limit $1`;

function codeOf(error) {
  return String(error?.code || error?.message || "channel_ingest_failed").replace(/[^a-z0-9_.:-]/gi, "_").slice(0, 120);
}

function bounded(value) {
  const text = JSON.stringify(value ?? {});
  if (text.length <= INGEST_DELTA_MAX_BYTES) return text;
  // Truncation is the failure this repo has a name for and has already paid
  // for once (`silent-truncation`, and the crisis helplines that were eaten
  // off the end of a prompt). So an oversized delta is not trimmed — it is
  // replaced by a NAMED marker, and the run says so.
  return JSON.stringify({ oversized: true, bytes: text.length, note: "delta exceeded INGEST_DELTA_MAX_BYTES and was not stored" });
}

/** Opens (or re-opens) the run row for one video.
 *
 *  `on conflict do update ... where status='failed'` is the idempotence law
 *  in one clause: a video already carried to `transcribed`/`proposed`/
 *  `applied`/`rejected` returns NO ROW and is skipped, while a previous
 *  FAILURE is retried. The `where` on the update is what makes the difference
 *  — without it, a retry would reset a proposal a teacher was mid-review on.
 *
 *  WS-AF added `video_title`. The owner's question about this lane is "have we
 *  received the YT video", and `video_ref` holds `dQw4w9WgXcQ`. The title was
 *  already on the object the provider hands us and was simply dropped at the
 *  door, which left the one row that answers their question unreadable by them.
 *  `coalesce(nullif(excluded.video_title,''), vy_ingest_run.video_title)` on the
 *  retry path so a provider that stops returning titles cannot blank one we
 *  already have.
 */
async function openRun(db, watch, video, transcriptSource) {
  const rows = await db(
    `insert into vy_ingest_run (run_id, replica_id, owner_user_id, watch_id, video_ref, video_title, transcript_source, status)
     values ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5, $7, $6, 'fetched')
     on conflict (replica_id, video_ref) do update
        set status = 'fetched', failure_code = '', transcript_source = excluded.transcript_source,
            video_title = coalesce(nullif(excluded.video_title, ''), vy_ingest_run.video_title),
            updated_at = now()
      where vy_ingest_run.status = 'failed' and vy_ingest_run.owner_user_id = $3::uuid
     returning run_id, replica_id, owner_user_id, video_ref, video_title, status`,
    [randomUUID(), watch.replicaId, watch.ownerUserId, watch.watchId, video.videoId, transcriptSource,
      String(video.title || "").slice(0, 200)],
  );
  return rows[0] || null;
}

async function markRun(db, ownerUserId, runId, patch) {
  const rows = await db(
    `update vy_ingest_run
        set status = $3, transcript_source = coalesce($4, transcript_source),
            stats = coalesce($5::jsonb, stats), proposed_delta = coalesce($6::jsonb, proposed_delta),
            proposed_delta_count = coalesce($7, proposed_delta_count),
            failure_code = $8, updated_at = now()
      where run_id = $1::uuid and owner_user_id = $2::uuid and status not in ('applied','rejected')
      returning run_id, status, proposed_delta_count, failure_code`,
    [runId, ownerUserId, patch.status, patch.transcriptSource ?? null,
      patch.stats ? bounded(patch.stats) : null,
      patch.delta ? bounded(patch.delta) : null,
      Number.isInteger(patch.deltaCount) ? patch.deltaCount : null,
      String(patch.failureCode || "")],
  );
  return rows[0] || null;
}

/** The transcript, from whichever lane the provider can lawfully offer.
 *  Captions are preferred when they exist because they are free and already
 *  the owner's own text; ASR is the lane for everything else. The chosen lane
 *  is RECORDED on the row (`transcript_source`) rather than inferred later —
 *  a phrase-bank number measured off a caption file and one measured off an
 *  ASR transcript are not the same measurement, and a future comparison
 *  between two runs has to be able to tell. */
async function transcriptFor(channelProvider, asr, video, watch, deps = {}) {
  if (typeof channelProvider.fetchCaptions === "function") {
    const captions = await channelProvider.fetchCaptions(video, watch.oauthGrantRef);
    if (captions?.turns?.length) {
      return { source: "captions", turns: captions.turns, provider: channelProvider.name, model: captions.trackKind };
    }
  }
  // WS-S. The attestation is resolved HERE, lazily, at the one moment it is
  // needed — after captions have already failed and immediately before the
  // only operation that reads a teacher's media. Resolving it at the top of
  // the sweep would spend a query per watch per tick on a gate most ticks
  // never reach, and, worse, would let an attestation revoked DURING a sweep
  // still authorize the extraction that follows it.
  //
  // `deps.attestations` is optional: a deployment with no extraction service
  // has no resolver, passes null, and the OAuth provider's honest refusal is
  // what happens — a null here is never silently treated as permission.
  const attestation = typeof deps.attestations === "function" ? await deps.attestations(watch) : null;
  const audio = await channelProvider.fetchAudio(video, watch.oauthGrantRef, { watch, attestation });
  const result = await asr.transcribe(audio, "hi-IN");
  return { source: "asr", turns: result.turns, provider: result.provider, model: result.model };
}

/** transcriptStats over the WHOLE video, then draftFromTranscript over the
 *  parity split. Both are stored, and they are stored under different names,
 *  because they are different numbers: `stats.corpus` measures every teacher
 *  turn in the video, `delta.measurements` measures the half the candidates
 *  were mined from. A row that reported one as the other would state a
 *  measured-looking number that was never measured — the failure
 *  transcriptStats.ts's own header names when it explains why `tokenRatio`
 *  and `turnRatio` are spelled differently. */
function proposalFrom(turns) {
  const corpus = transcriptStats(turns);
  const drafted = draftFromTranscript(turns, (half) => transcriptStats(half, { teacherSpeaker: corpus.speaker.label }));
  return {
    stats: {
      corpus: {
        speaker: corpus.speaker,
        totalTurns: corpus.totalTurns,
        tokens: corpus.tokens,
        codeSwitch: corpus.codeSwitch,
        fillers: corpus.fillers.slice(0, 10),
        laughter: corpus.laughter,
        stretch: corpus.stretch.slice(0, 10),
      },
      phraseBank: {
        verified: drafted.phraseBank.verified,
        heldOutTokens: drafted.phraseBank.heldOutTokens,
        unverifiedReason: drafted.phraseBank.unverifiedReason ?? null,
      },
    },
    // ADDITIONS ONLY. See this file's header for the measurement argument
    // against a retirement lane fed by a single video.
    delta: {
      kind: "sheet-candidates/v1",
      additions: drafted.candidates,
      measurements: drafted.measurements,
      // Carried so the studio can show WHY a field is still empty without
      // re-running anything. `draftFromSignals` fills nothing from an
      // unconfirmed mine, which is the correct behaviour and also the
      // behaviour most likely to be mistaken for a broken pipeline.
      gapsForCandidateFields: drafted.gaps.filter((gap) => gap.field === "boardVerbalisms" || gap.field === "exSlangRepeat"),
    },
    deltaCount: drafted.candidates.length,
  };
}

async function ingestVideo(db, deps, watch, video) {
  const opened = await openRun(db, watch, video, "asr");
  // No row means the video already has a run that is not `failed` — the
  // idempotence case, and the correct answer is silence.
  if (!opened) return { videoId: video.videoId, skipped: true, ok: true };
  // WS-AF. The transitions, with their times. `vy_ingest_run` carries one
  // `updated_at`, so after the fact it can say a run is `proposed` and cannot
  // say when it stopped being `fetched` — which is the difference between "it
  // is working" and "it has been stuck on the transcribe hop for two hours".
  // `subject` is carried on every event so the trail stays readable after the
  // run row itself is gone.
  const subject = String(video.title || video.videoId || "").slice(0, 300);
  const trace = (state, reason) => recordActivity(db, {
    replicaId: watch.replicaId, ownerUserId: watch.ownerUserId,
    lane: "channel_video", jobRef: opened.run_id, subject, state, reason,
    // `queued` happens once per run. The dedupe key keeps a re-opened failed
    // run from stamping a second start over the first one's timestamp.
    dedupeKey: state === "queued" ? `channel_video:${opened.run_id}:queued` : "",
  });
  await trace("queued", "received from the channel");
  try {
    const transcript = await transcriptFor(deps.channelProvider, deps.asr, video, watch, deps);
    await markRun(db, watch.ownerUserId, opened.run_id, {
      status: "transcribed",
      transcriptSource: transcript.source,
      stats: { transcript: { provider: transcript.provider, model: transcript.model, turns: transcript.turns.length } },
    });
    await trace("running", `transcribed from ${transcript.source}`);
    const proposal = proposalFrom(transcript.turns);
    await markRun(db, watch.ownerUserId, opened.run_id, {
      status: "proposed",
      stats: { ...proposal.stats, transcript: { provider: transcript.provider, model: transcript.model, turns: transcript.turns.length } },
      delta: proposal.delta,
      deltaCount: proposal.deltaCount,
    });
    await trace("waiting_on_you", `${proposal.deltaCount} suggestions proposed`);
    return { videoId: video.videoId, runId: opened.run_id, ok: true, proposed: proposal.deltaCount };
  } catch (error) {
    const failureCode = codeOf(error);
    await markRun(db, watch.ownerUserId, opened.run_id, { status: "failed", failureCode })
      .catch(() => null);
    await trace("failed", failureCode);
    return { videoId: video.videoId, runId: opened.run_id, ok: false, failureCode };
  }
}

/** WS-AF. This function used to write `last_checked_at = now()` and nothing
 *  else, which made a channel that has failed its listing on every tick for a
 *  week indistinguishable from one that has been checked on every tick and had
 *  nothing new: both show a recent timestamp and there is no error anywhere a
 *  person can reach. That is `plausible-return-hides-a-dead-pipeline` with the
 *  clock as the plausible value.
 *
 *  It matters more on this lane than on any other, because the one failure this
 *  lane already PREDICTS lands exactly here:
 *  `docs/gurukul/youtube-extraction-posture.md` expects
 *  `channel_extract_extractor_bot_check` from a datacentre IP on the first real
 *  sweep, and the caller's catch below swallowed it into a timestamp.
 *
 *  So the outcome is recorded with the check: `checked` or `failed`, the reason
 *  when it failed, and how many videos the listing actually returned. Migration
 *  060's `vy_channel_watch_sweep_failure_named` refuses a failed sweep with no
 *  reason, so a future caller cannot re-introduce the silence by forgetting.
 */
async function touchWatch(db, watch, lastSeenVideoId, outcome = {}) {
  const state = outcome.failureCode ? "failed" : "checked";
  await db(
    `update vy_channel_watch
        set last_checked_at = now(),
            last_seen_video_id = case when $3 <> '' then $3 else last_seen_video_id end,
            last_sweep_state = $4,
            last_sweep_reason = $5,
            last_sweep_videos = $6::int4
      where watch_id = $1::uuid and owner_user_id = $2::uuid and status = 'active'`,
    [watch.watchId, watch.ownerUserId, String(lastSeenVideoId || ""),
      state, String(outcome.failureCode || ""), Math.max(0, Number(outcome.videos || 0))],
  );
}

async function sweepWatch(db, deps, row, maxVideos) {
  const watch = channelWatch(row);
  let videos;
  try {
    videos = await deps.channelProvider.listNewVideos(watch.channel, watch.lastSeenVideoId, watch.oauthGrantRef);
  } catch (error) {
    // A listing failure is the watch's failure, not any video's. It gets no
    // run row — there is no video to attach one to — and the cursor does not
    // move, so nothing is lost.
    //
    // WS-AF: it now also gets a NAMED outcome on the watch row and an activity
    // event, because until this line the only trace it left was a fresher
    // `last_checked_at`, and a fresher timestamp is what a successful check
    // looks like.
    const failureCode = codeOf(error);
    await touchWatch(db, watch, "", { failureCode }).catch(() => null);
    await recordActivity(db, {
      replicaId: watch.replicaId, ownerUserId: watch.ownerUserId,
      lane: "channel_watch", jobRef: watch.watchId, subject: watch.channel?.url || "",
      state: "failed", reason: failureCode,
    });
    return { watchId: watch.watchId, listed: 0, ingested: 0, failed: 0, failureCode };
  }
  const slice = videos.slice(0, Math.max(0, maxVideos));
  let cursor = "";
  let ingested = 0;
  let failed = 0;
  const runs = [];
  for (const video of slice) {
    const result = await ingestVideo(db, deps, watch, video);
    runs.push(result);
    if (!result.ok) { failed++; break; }   // stop at the first failure; order is the point
    cursor = video.videoId;
    if (!result.skipped) ingested++;
  }
  await touchWatch(db, watch, cursor, { videos: videos.length });
  await recordActivity(db, {
    replicaId: watch.replicaId, ownerUserId: watch.ownerUserId,
    lane: "channel_watch", jobRef: watch.watchId, subject: watch.channel?.url || "",
    state: "done", reason: `${videos.length} listed, ${ingested} taken in`,
  });
  const backfill = failed ? null : await backfillWatch(db, deps, watch, maxVideos);
  return { watchId: watch.watchId, listed: videos.length, ingested, failed, runs, backfill };
}

/** The back-catalogue lane (WS-S).
 *
 *  The forward lane answers "what is new". This one answers "how far back
 *  have we got", and it exists because a teacher's own back catalogue is by
 *  far the largest corpus this platform will ever have for one person — years
 *  of their own lectures, in their own voice, with their own explanations.
 *
 *  Three properties, and all three are why it is a SEPARATE lane rather than
 *  a wider slice of the forward one:
 *
 *  1. RESUMABLE. `backfill_after_video_id` advances only past a video that
 *     actually succeeded, and a tick takes at most `maxVideos`. A cron killed
 *     mid-lecture loses that lecture and nothing before it, and the next tick
 *     resumes exactly there. A "just raise the limit" design instead loses
 *     the whole page.
 *  2. SUBORDINATE. It runs only after the forward lane, and not at all if the
 *     forward lane failed. Staying current always beats catching up: a
 *     backfill that starved new-video detection would make the clone
 *     progressively more out of date the more history it had.
 *  3. IDEMPOTENT AGAINST THE OTHER CURSOR. The two walk in opposite
 *     directions over one channel and will eventually meet. The unique index
 *     on (replica_id, video_ref) makes the overlap a skip rather than a
 *     second ASR bill, and `openRun` returning no row is the mechanism —
 *     which is the same mechanism the forward lane's idempotence already
 *     relies on, tested by evals/channel.mjs.
 */
async function backfillWatch(db, deps, watch, maxVideos) {
  if (watch.backfillState !== "running") return null;
  if (typeof deps.channelProvider.listCatalogue !== "function") {
    // A deployment with no extraction service has no enumeration seam. That
    // is a lane that is ABSENT, not one that is broken, so it is reported and
    // the state is parked rather than marked failed.
    return { skipped: "catalogue_unavailable" };
  }
  const attestation = typeof deps.attestations === "function" ? await deps.attestations(watch) : null;
  if (!attestation) return { skipped: "attestation_unavailable" };

  let page;
  try {
    page = await deps.channelProvider.listCatalogue(watch.channel, watch.backfillAfterVideoId, {
      attestation,
      limit: Math.max(1, maxVideos),
    });
  } catch (error) {
    return { skipped: codeOf(error) };
  }
  let cursor = "";
  let ingested = 0;
  let failed = 0;
  for (const video of page.videos.slice(0, Math.max(0, maxVideos))) {
    const result = await ingestVideo(db, deps, watch, video);
    if (!result.ok) { failed++; break; }
    cursor = video.videoId;
    if (!result.skipped) ingested++;
  }
  // `exhausted` is reported by the enumeration, and it is only trusted when
  // the page was walked to its end without a failure. A catalogue marked done
  // while a video in it failed would strand that video forever, since nothing
  // walks backwards a second time.
  const done = page.exhausted && !failed && cursor === (page.videos[page.videos.length - 1]?.videoId || cursor);
  await db(
    `update vy_channel_watch
        set backfill_after_video_id = case when $3 <> '' then $3 else backfill_after_video_id end,
            backfill_state = case when $4 then 'done' else backfill_state end
      where watch_id = ($1)::uuid and owner_user_id = ($2)::uuid and backfill_state = 'running'`,
    [watch.watchId, watch.ownerUserId, cursor, Boolean(done)],
  );
  return { ingested, failed, exhausted: Boolean(done), listed: page.videos.length };
}

/**
 * One cron tick.
 *
 * `db`, `channelProvider` and `asr` are injected rather than imported, which
 * is `api/replica-claims.js` over `api/_replica-claims.js` — the split that
 * lets evals/channel.mjs drive THIS function with a fake db and fixture
 * providers. The DB is absent in this environment and the eval suite is
 * offline by contract, so a design reachable only from Neon would be a design
 * nothing tests.
 */
export async function runChannelIngestSweep(options = {}) {
  const db = options.db;
  if (typeof db !== "function") throw new ChannelIngestError("channel_ingest_db_required", 500);
  const channelProvider = assertChannelProvider(options.channelProvider);
  const asr = assertAsrProvider(options.asr);
  const maxWatches = Number.isInteger(options.maxWatches) ? options.maxWatches : DEFAULT_MAX_WATCHES;
  const maxVideos = Number.isInteger(options.maxVideosPerWatch) ? options.maxVideosPerWatch : DEFAULT_MAX_VIDEOS_PER_WATCH;

  const rows = await db(DUE_WATCHES_SQL, [Math.max(1, maxWatches)]);
  const watches = [];
  for (const row of rows) {
    try { watches.push(await sweepWatch(db, { channelProvider, asr, attestations: options.attestations }, row, maxVideos)); }
    catch (error) {
      // A malformed watch row (a grant ref that is not a uuid, a channel_url
      // that stopped parsing) must not take the sweep down with it.
      if (!(error instanceof ChannelError)) throw error;
      watches.push({ watchId: String(row?.watch_id || ""), listed: 0, ingested: 0, failed: 0, failureCode: codeOf(error) });
    }
  }
  return {
    watches: watches.length,
    ingested: watches.reduce((sum, watch) => sum + watch.ingested, 0),
    failed: watches.reduce((sum, watch) => sum + watch.failed, 0),
    detail: watches,
  };
}

/** What the studio review screen reads. Owner-scoped in the WHERE clause, and
 *  it never returns a run belonging to anyone else — the same predicate
 *  discipline every statement above uses. */
export async function listIngestRunsForReview(db, ownerUserId, replicaIdValue, limit = 50) {
  if (!UUID.test(String(ownerUserId || "")) || !UUID.test(String(replicaIdValue || ""))) {
    throw new ChannelIngestError("channel_ingest_identity_invalid", 400);
  }
  const rows = await db(
    `select run_id, video_ref, transcript_source, status, proposed_delta, proposed_delta_count,
            failure_code, created_at, updated_at
       from vy_ingest_run
      where replica_id = $1::uuid and owner_user_id = $2::uuid
      order by created_at desc limit $3`,
    [String(replicaIdValue).toLowerCase(), String(ownerUserId).toLowerCase(), Math.min(200, Math.max(1, limit))],
  );
  return rows.map((row) => ({
    run_id: row.run_id,
    video_ref: row.video_ref,
    transcript_source: row.transcript_source,
    status: row.status,
    proposed_delta: row.proposed_delta,
    proposed_delta_count: Number(row.proposed_delta_count),
    failure_code: row.failure_code,
    created_at: row.created_at,
    updated_at: row.updated_at,
  }));
}

/**
 * THE APPROVAL OP. The only function in this tree that writes
 * `status='applied'`, and it writes it together with the approver and the
 * decision time — which is what migration 053's `vy_ingest_run_approval_gate`
 * requires, so a future writer that sets the status alone is refused by the
 * database rather than by a code review.
 *
 * It transitions the RUN only. Merging an approved delta into a sheet draft
 * is `api/_teacher-sheet-draft.js`'s `saveOwnedTeacherSheetDraft`, which
 * already carries the publish gate, the phrase-bank check against a held-out
 * corpus, and the consent predicate. Doing it here would be a second place
 * that decides what a clone of a named person may say, and the drifted copy
 * would keep returning 200.
 *
 * WS-R112: a run whose SOURCE is a `vy_context_item` the creator has since
 * REFUSED (`decideReviewCard`'s 'remove_source' decision on an
 * 'instruction_shaped' card, `api/_review-queue.js`) may never reach
 * 'applied' - this IS the "sheet rebuild excludes it" law the workstream's
 * own brief asked to be read and fixed, not assumed already true. Reading
 * this function BEFORE that fix found it did not: it checked only
 * `vy_ingest_run.status`, never the mined item's own state, so a proposal
 * mined before a creator later removed its source could still be approved
 * after the removal. The `not exists` clause below closes that: for a run
 * whose `transcript_source = 'context_item'` (`api/_context-locker.js::
 * mineStored`'s own literal), it is blocked when the item named by
 * `video_ref` (`context:<item_id>`, that file's own convention) is
 * `refused`. A run from any OTHER transcript source (a channel video, for
 * instance) is untouched: the first clause of the `exists` is false for
 * those, so the `not exists` is trivially true and this predicate adds
 * nothing new for them.
 */
export async function applyIngestRunDelta(db, ownerUserId, runId, approvedByUserId) {
  if (!UUID.test(String(ownerUserId || "")) || !UUID.test(String(runId || "")) || !UUID.test(String(approvedByUserId || ""))) {
    throw new ChannelIngestError("channel_ingest_identity_invalid", 400);
  }
  const rows = await db(
    `update vy_ingest_run r
        set status = 'applied', approved_by_user_id = $3::uuid, decided_at = now(), updated_at = now()
      where r.run_id = $1::uuid and r.owner_user_id = $2::uuid and r.status = 'proposed'
        and not exists (
          select 1 from vy_context_item i
           where r.transcript_source = 'context_item'
             and i.owner_user_id = r.owner_user_id
             and i.item_id::text = split_part(r.video_ref, ':', 2)
             and i.status = 'refused'
        )
      returning r.run_id, r.status, r.proposed_delta, r.proposed_delta_count, r.approved_by_user_id, r.decided_at`,
    [String(runId).toLowerCase(), String(ownerUserId).toLowerCase(), String(approvedByUserId).toLowerCase()],
  );
  if (!rows[0]) throw new ChannelIngestError("channel_ingest_run_not_approvable", 409);
  return rows[0];
}

/** The other half of a decision. A rejected run is KEPT, 051's reason: the
 *  row is the record that this video was looked at and declined, and without
 *  it the next sweep would re-propose it forever. */
export async function rejectIngestRun(db, ownerUserId, runId, decidedByUserId) {
  if (!UUID.test(String(ownerUserId || "")) || !UUID.test(String(runId || "")) || !UUID.test(String(decidedByUserId || ""))) {
    throw new ChannelIngestError("channel_ingest_identity_invalid", 400);
  }
  const rows = await db(
    `update vy_ingest_run
        set status = 'rejected', approved_by_user_id = $3::uuid, decided_at = now(), updated_at = now()
      where run_id = $1::uuid and owner_user_id = $2::uuid and status = 'proposed'
      returning run_id, status, decided_at`,
    [String(runId).toLowerCase(), String(ownerUserId).toLowerCase(), String(decidedByUserId).toLowerCase()],
  );
  if (!rows[0]) throw new ChannelIngestError("channel_ingest_run_not_approvable", 409);
  return rows[0];
}
