// Mining a context item into CITED sheet-draft deltas (Gurukul WS-AB).
//
// The statistical pass is not re-implemented here. `draftFromTranscript` and
// `transcriptStats` come from `api/_engine.gen.js`, bundled from the real
// TypeScript, and are the same two functions `api/_channel-ingest.js` runs on a
// lecture — because a second definition of "what did we measure about how this
// person talks" would drift, and the drifted copy would keep returning 200.
// What this file adds is the half the channel lane never needed: PROVENANCE.
//
// ── a delta that cannot be checked is not evidence ───────────────────────
// Every addition this file emits names the item it came from AND the character
// span inside that item's stored text. Not "from your files" — from item
// 7f3c…, characters 4180–4245, spoken by you. Three properties fall out, and
// all three are asserted by evals/contextlocker.mjs rather than intended:
//
//   1. RESOLVABLE. `body.slice(start, end)` really contains the fragment. A
//      fabricated citation — right item, wrong span — must FAIL, and the suite
//      drives exactly that negative control. Without it, "cited" is a label a
//      pipeline can print while measuring nothing, which is
//      `plausible-return-hides-a-dead-pipeline` wearing a provenance badge.
//   2. ATTRIBUTED. The cited span's speaker is the OWNER. For a chat export
//      that is the whole ballgame: the wrong-speaker control mines an export
//      with the other party declared as the owner and asserts that not one
//      citation lands on the real owner's messages.
//   3. ADDITIONS ONLY. Same rule, same reason as the channel lane's: one
//      document's held-out half is a few thousand tokens, and a retirement lane
//      fed by it would propose retiring almost everything almost every time —
//      a stream of confident proposals generated by sample size.
//
// ── mining nothing is a RESULT, and it is named ──────────────────────────
// Three ordinary items mine zero proposals, and each says which:
//
//   not_owner_authored_no_style_evidence   an article, or a document the owner
//                                          declared is not their own writing.
//                                          Somebody else's phrases are the one
//                                          thing that must never enter a clone.
//   speaker_unattributed_no_style_evidence a chat export with no declared owner
//                                          speaker. An unattributable export
//                                          contributes style evidence from
//                                          nothing, and averaging over everyone
//                                          in the room is not a smaller version
//                                          of the right answer, it is a
//                                          different and wrong one.
//   no_candidates_cleared_held_out         the pass ran and nothing met the
//                                          >=5-occurrence rule. The honest
//                                          answer to a short document.
//
// None of them is a failure and none of them is silence.
import { draftFromTranscript, transcriptStats } from "./_engine.gen.js";
import { MAX_CITATIONS_PER_CANDIDATE } from "./_context/limits.js";

/** The speaker label owner turns are relabelled to before the statistical pass
 *  sees them. A constant rather than the owner's real name: `_obs.js`'s law is
 *  counts, labels and decisions — never a person's name — and this string ends
 *  up inside a stored jsonb delta. */
export const OWNER_SPEAKER_LABEL = "owner";

/** Formats whose text is somebody else's by default, whatever the owner ticks.
 *  An article the owner found interesting is a TOPIC signal, not a voice one,
 *  and there is no checkbox that makes a journalist's sentences into the
 *  owner's habits. */
const NEVER_OWNER_AUTHORED = new Set(["article"]);

/** Word-boundary match for a fragment inside a span. Unicode-aware `\p{L}`
 *  rather than `\b`, because Devanagari is in this corpus and `\b` treats every
 *  Devanagari character as a non-word character in a non-unicode regex —
 *  `romanised-lexicon-meets-devanagari-asr` is the same mistake one layer up. */
function fragmentRegex(fragment) {
  const escaped = String(fragment).replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
  return new RegExp(`(?<![\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`, "giu");
}

/**
 * THE CITATION INTEGRITY PREDICATE.
 *
 * Exported and used by BOTH the miner (before a citation is emitted) and
 * evals/contextlocker.mjs (over every citation in a stored delta). One
 * definition on purpose: a checker that re-implements the rule it is checking
 * agrees with the implementation's bugs, which is `subset-check-is-green-by-
 * construction`.
 *
 * @returns `true` when the span really contains the fragment.
 */
export function citationResolves(body, citation, fragment) {
  if (!citation || typeof citation !== "object") return false;
  const { start, end } = citation.span || {};
  if (!Number.isInteger(start) || !Number.isInteger(end)) return false;
  if (start < 0 || end > body.length || end <= start) return false;
  return fragmentRegex(fragment).test(body.slice(start, end));
}

/** Every owner-attributed span, in document order. This is the ONLY place a
 *  segment becomes an owner turn, so the rule "somebody else's words are never
 *  mined" has one gate rather than one per format. */
function ownerSegments(extraction, options) {
  if (NEVER_OWNER_AUTHORED.has(extraction.format)) return { segments: [], reason: "not_owner_authored_no_style_evidence" };

  if (extraction.format === "whatsapp_export") {
    const declared = String(options.ownerSpeaker || "").trim();
    if (!declared) return { segments: [], reason: "speaker_unattributed_no_style_evidence" };
    const mine = extraction.segments.filter((s) => s.speaker === declared);
    if (!mine.length) return { segments: [], reason: "declared_speaker_not_in_export" };
    return { segments: mine, reason: "" };
  }

  if (options.authorship !== "mine") return { segments: [], reason: "not_owner_authored_no_style_evidence" };
  return { segments: extraction.segments, reason: "" };
}

/** Up to three resolvable citations for one fragment, searched over the owner's
 *  spans only. A citation that does not resolve is DROPPED here rather than
 *  emitted and hoped about — and a candidate left with zero citations is
 *  dropped with it, because an uncited addition is exactly the thing this lane
 *  exists to make impossible. */
function citationsFor(body, segments, fragment, itemId) {
  const out = [];
  for (const seg of segments) {
    if (out.length >= MAX_CITATIONS_PER_CANDIDATE) break;
    const re = fragmentRegex(fragment);
    if (!re.test(seg.text)) continue;
    const citation = {
      item_id: itemId,
      span: { start: seg.start, end: seg.end },
      speaker: seg.speaker || OWNER_SPEAKER_LABEL,
    };
    if (citationResolves(body, citation, fragment)) out.push(citation);
  }
  return out;
}

const fieldFor = (fragment) => (String(fragment).includes(" ") ? "boardVerbalisms" : "exSlangRepeat");

/**
 * Mine one extracted item.
 *
 * @param item        `{ item_id, format, source_name, extractor }`
 * @param extraction  `{ body, segments, format, extractor }`
 * @param options     `{ authorship: "mine"|"not_mine", ownerSpeaker }`
 * @returns `{ mined, reason, delta, deltaCount, stats }` — `mined:false` with a
 *          NAMED reason is a normal, complete answer.
 */
export function mineContextItem(item, extraction, options = {}) {
  const body = extraction.body;
  const { segments, reason } = ownerSegments(extraction, options);

  const itemFacts = {
    item_id: item.item_id,
    format: extraction.format,
    extractor: extraction.extractor,
    chars: body.length,
    segments: extraction.segments.length,
    owner_segments: segments.length,
    // The span the whole item covers, so even a zero-proposal item's
    // measurements carry a citation. "Every delta names an item and a span" has
    // no exception clause; a measurement over nothing names an empty span.
    span: { start: 0, end: body.length },
  };

  if (!segments.length) {
    return {
      mined: false,
      reason,
      deltaCount: 0,
      stats: { item: itemFacts },
      delta: { kind: "context-sheet-candidates/v1", item: itemFacts, additions: [], measurements: null, notMinedReason: reason },
    };
  }

  const turns = segments.map((s) => ({ speaker: OWNER_SPEAKER_LABEL, text: s.text }));
  const corpus = transcriptStats(turns);
  const drafted = draftFromTranscript(turns, (half) =>
    transcriptStats(half, { teacherSpeaker: OWNER_SPEAKER_LABEL }),
  );

  const additions = [];
  for (const candidate of drafted.candidates) {
    const citations = citationsFor(body, segments, candidate.fragment, item.item_id);
    if (!citations.length) continue;   // uncited additions do not exist in this lane
    additions.push({
      field: fieldFor(candidate.fragment),
      fragment: candidate.fragment,
      occurrences: candidate.count ?? candidate.occurrences ?? citations.length,
      citations,
    });
  }

  return {
    mined: true,
    reason: additions.length ? "" : "no_candidates_cleared_held_out",
    deltaCount: additions.length,
    stats: {
      item: itemFacts,
      corpus: {
        speaker: corpus.speaker,
        totalTurns: corpus.totalTurns,
        tokens: corpus.tokens,
        codeSwitch: corpus.codeSwitch,
        fillers: corpus.fillers.slice(0, 10),
        laughter: corpus.laughter,
        stretch: corpus.stretch.slice(0, 10),
      },
      phraseBank: {
        verified: drafted.phraseBank.verified,
        heldOutTokens: drafted.phraseBank.heldOutTokens,
        unverifiedReason: drafted.phraseBank.unverifiedReason ?? null,
      },
    },
    delta: {
      kind: "context-sheet-candidates/v1",
      item: itemFacts,
      // ADDITIONS ONLY — see this file's header.
      additions,
      measurements: { ...drafted.measurements, citation: { item_id: item.item_id, span: itemFacts.span } },
      gapsForCandidateFields: drafted.gaps.filter(
        (gap) => gap.field === "boardVerbalisms" || gap.field === "exSlangRepeat",
      ),
      ...(additions.length ? {} : { notMinedReason: "no_candidates_cleared_held_out" }),
    },
  };
}

/**
 * The whole-delta integrity check, over a delta and the body it cites.
 *
 * Runs at WRITE time in `api/_context-locker.js` — not only in the eval —
 * because the property that matters is "no unresolvable citation was ever
 * STORED", and a check that lives only in a test is a check the production path
 * does not have. Returns the list of violations; empty means clean.
 */
export function citationViolations(delta, body) {
  const bad = [];
  for (const addition of delta?.additions || []) {
    if (!addition.citations?.length) { bad.push({ fragment: addition.fragment, code: "uncited_addition" }); continue; }
    for (const citation of addition.citations) {
      if (!citation.item_id) bad.push({ fragment: addition.fragment, code: "citation_names_no_item" });
      else if (!citationResolves(body, citation, addition.fragment)) {
        bad.push({ fragment: addition.fragment, code: "citation_span_does_not_contain_fragment", span: citation.span });
      }
    }
  }
  const measurementCitation = delta?.measurements?.citation;
  if (delta?.measurements && (!measurementCitation?.item_id || !Number.isInteger(measurementCitation?.span?.end))) {
    bad.push({ code: "measurements_uncited" });
  }
  return bad;
}
